import ExplicitUnirational.Cert.AxiomAudit
import ExplicitUnirational.Cert.Discriminant
import ExplicitUnirational.Cert.Invariants
import ExplicitUnirational.Cert.NineCycle
import ExplicitUnirational.Cert.NonicF5
import ExplicitUnirational.Cert.OcticF7
import ExplicitUnirational.Cert.OcticQ
import ExplicitUnirational.Cert.QuarticDiscriminants
import ExplicitUnirational.Cert.Rabin
import ExplicitUnirational.Cert.SexticF5
import ExplicitUnirational.CubicPencil.Incidence
import ExplicitUnirational.DelPezzo.Surface
import ExplicitUnirational.Divisors.Bridge
import ExplicitUnirational.Divisors.ClassGroup
import ExplicitUnirational.Divisors.NSLattice
import ExplicitUnirational.Foundation
import ExplicitUnirational.FunctionField.Dominance
import ExplicitUnirational.FunctionField.GeometricIntegrality
import ExplicitUnirational.FunctionField.MonodromyS9
import ExplicitUnirational.FunctionField.MulThree
import ExplicitUnirational.FunctionField.MulThreeCert
import ExplicitUnirational.FunctionField.PencilRationality
import ExplicitUnirational.FunctionField.ResidualDegree
import ExplicitUnirational.FunctionField.TangentResidual
import ExplicitUnirational.FunctionField.TorsorDescent
import ExplicitUnirational.FunctionField.TowerBProducts
import ExplicitUnirational.FunctionField.Unirationality
import ExplicitUnirational.FunctionField.WeierstrassOnCurve
import ExplicitUnirational.FunctionField.Trivialization
import ExplicitUnirational.GenericDegree
import ExplicitUnirational.Weierstrass.Fibres
import ExplicitUnirational.WeightedProjective.Basic
import ExplicitUnirational.WeightedProjective.Integrality
import ExplicitUnirational.WeightedProjective.Jacobian
/-!
# ExplicitUnirational
Formalization of explicit unirational degree-one del Pezzo surfaces of arithmetic Picard rank one.
-/
