module

public import ExplicitUnirational.Cert.AxiomAudit
public import ExplicitUnirational.Cert.Discriminant
public import ExplicitUnirational.Cert.Invariants
public import ExplicitUnirational.Cert.NineCycle
public import ExplicitUnirational.Cert.NonicF5
public import ExplicitUnirational.Cert.OcticF7
public import ExplicitUnirational.Cert.OcticQ
public import ExplicitUnirational.Cert.QuarticDiscriminants
public import ExplicitUnirational.Cert.Rabin
public import ExplicitUnirational.Cert.SexticF5
public import ExplicitUnirational.CubicPencil.Incidence
public import ExplicitUnirational.DelPezzo.Surface
public import ExplicitUnirational.Divisors.Bridge
public import ExplicitUnirational.Divisors.ClassGroup
public import ExplicitUnirational.Divisors.NSLattice
public import ExplicitUnirational.Foundation
public import ExplicitUnirational.FunctionField.GeometricIntegrality
public import ExplicitUnirational.FunctionField.MonodromyS9
public import ExplicitUnirational.FunctionField.MulThree
public import ExplicitUnirational.FunctionField.MulThreeCert
public import ExplicitUnirational.FunctionField.PencilRationality
public import ExplicitUnirational.FunctionField.ResidualDegree
public import ExplicitUnirational.FunctionField.TangentResidual
public import ExplicitUnirational.FunctionField.YSplit
public import ExplicitUnirational.FunctionField.TorsorDescent
public import ExplicitUnirational.FunctionField.Trivialization
public import ExplicitUnirational.GenericDegree
public import ExplicitUnirational.Weierstrass.Fibres
public import ExplicitUnirational.WeightedProjective.Basic
public import ExplicitUnirational.WeightedProjective.Integrality
public import ExplicitUnirational.WeightedProjective.Jacobian
/-!
# ExplicitUnirational
Formalization of explicit unirational degree-one del Pezzo surfaces of arithmetic Picard rank one.
-/
