/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.Cert.Rabin
public import Mathlib.Tactic.ComputeDegree
public import Mathlib.Tactic.LinearCombination

/-!
# Irreducibility of the nonic over `F₅` (note Appendix A)

Note Proposition 4.1: on `Z = 1` the base scheme of the reduced pencil is cut out
by `Y = X^3` and `R(X) = X^9 + X^6 + X - 1 = 0`. Irreducibility of `R` is what makes
the base scheme a single reduced closed point of degree 9.

The Frobenius ladder is generated by exact arithmetic in `F_q[X]/(f)` and re-checked
here: each rung is `r_k ^ q = f * s_k + r_(k+1)`, closed by rewriting the `q`-th power
as `X ↦ X ^ q` (`Rabin.pow_card_eq_expand`) and then a `linear_combination` against the
characteristic. Coprimality is certified by an explicit Bézout pair.
-/

noncomputable section

open Polynomial

namespace ExplicitUnirational.Cert

section NonicF5

private instance : Fact (Nat.Prime 5) := ⟨by decide⟩

private lemma hq : (5 : (ZMod 5)[X]) = 0 := by
  simpa using CharP.cast_eq_zero ((ZMod 5)[X]) 5

private lemma card_zmod : Nat.card (ZMod 5) = 5 := Nat.card_zmod 5

/-- `R = X^9 + X^6 + X - 1`, the base-scheme polynomial of note Proposition 4.1. -/
public def R : (ZMod 5)[X] := X ^ 9 + X ^ 6 + X + 4

public lemma R_monic : R.Monic := by
  unfold R; monicity!

public lemma R_natDegree : R.natDegree = 9 := by
  unfold R; compute_degree!

private def s0 : (ZMod 5)[X] := 0
private def s1 : (ZMod 5)[X] := X ^ 16 + 4 * X ^ 13 + X ^ 10 + 4 * X ^ 8 + 2 * X ^ 5 + 4 * X ^ 4 + 2 * X ^ 2 + 2 * X + 1
private def s2 : (ZMod 5)[X] := 2 * X ^ 31 + 3 * X ^ 28 + 3 * X ^ 26 + 2 * X ^ 25 + 2 * X ^ 21 + 2 * X ^ 20 + 3 * X ^ 19 + 4 * X ^ 17 + 2 * X ^ 16 + X ^ 14 + X ^ 13 + 2 * X ^ 11 + 2 * X ^ 10 + X ^ 9 + X ^ 6 + X ^ 4 + 2 * X ^ 3 + 4
private def s3 : (ZMod 5)[X] := 4 * X ^ 26 + X ^ 23 + 2 * X ^ 21 + 4 * X ^ 20 + 4 * X ^ 18 + X ^ 14 + 3 * X ^ 13 + 3 * X ^ 12 + 2 * X ^ 11 + 3 * X ^ 10 + X ^ 9 + 3 * X ^ 8 + 2 * X ^ 7 + 3 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 2
private def s4 : (ZMod 5)[X] := 2 * X ^ 31 + 3 * X ^ 28 + 3 * X ^ 26 + 2 * X ^ 25 + 3 * X ^ 21 + 2 * X ^ 20 + 3 * X ^ 19 + 4 * X ^ 18 + 4 * X ^ 17 + 2 * X ^ 16 + X ^ 15 + X ^ 14 + 4 * X ^ 10 + 2 * X ^ 8 + 2 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 5 + 3 * X ^ 4 + 3 * X ^ 3 + 2 * X ^ 2 + X
private def s5 : (ZMod 5)[X] := 3 * X ^ 31 + 2 * X ^ 28 + 4 * X ^ 26 + 3 * X ^ 25 + 3 * X ^ 23 + 3 * X ^ 21 + 2 * X ^ 19 + 3 * X ^ 18 + X ^ 17 + 4 * X ^ 16 + 4 * X ^ 15 + 2 * X ^ 14 + 3 * X ^ 13 + 4 * X ^ 12 + X ^ 11 + X ^ 10 + 3 * X ^ 9 + X ^ 8 + 4 * X ^ 7 + 3 * X ^ 5 + 3 * X ^ 3 + 2 * X ^ 2 + 4 * X + 4
private def s6 : (ZMod 5)[X] := 3 * X ^ 21 + 2 * X ^ 18 + 4 * X ^ 16 + 3 * X ^ 15 + 3 * X ^ 13 + 2 * X ^ 11 + 2 * X ^ 9 + 4 * X ^ 8 + X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 2 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 2
private def s7 : (ZMod 5)[X] := 4 * X ^ 31 + X ^ 28 + 4 * X ^ 25 + X ^ 23 + 2 * X ^ 21 + 3 * X ^ 20 + X ^ 19 + 3 * X ^ 18 + 3 * X ^ 17 + 4 * X ^ 16 + X ^ 15 + 3 * X ^ 14 + 4 * X ^ 13 + 3 * X ^ 12 + 4 * X ^ 10 + 2 * X ^ 9 + 4 * X ^ 8 + 4 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 4 + X ^ 2 + 3
private def s8 : (ZMod 5)[X] := 4 * X ^ 31 + X ^ 28 + X ^ 26 + 4 * X ^ 25 + 4 * X ^ 20 + X ^ 19 + 4 * X ^ 18 + 3 * X ^ 17 + 3 * X ^ 16 + X ^ 15 + 2 * X ^ 14 + 2 * X ^ 13 + 3 * X ^ 11 + X ^ 9 + 2 * X ^ 8 + 2 * X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 4

private lemma step0 : (X : (ZMod 5)[X]) ^ 5
    = R * s0 + (X ^ 5) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [expand_X]
  unfold R s0
  linear_combination (0) * hq

private lemma step1 : (X ^ 5 : (ZMod 5)[X]) ^ 5
    = R * s1 + (2 * X ^ 8 + 3 * X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + X + 1) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_pow, expand_X]
  unfold R s1
  linear_combination (-X ^ 22 - X ^ 19 - X ^ 17 - X ^ 16 - 2 * X ^ 14 - 4 * X ^ 13 - X ^ 11 - 2 * X ^ 10 - X ^ 9 - 4 * X ^ 8 - X ^ 7 - X ^ 6 - 3 * X ^ 5 - 4 * X ^ 4 - X ^ 3 - 2 * X ^ 2 - 2 * X - 1) * hq

private lemma step2 : (2 * X ^ 8 + 3 * X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + X + 1 : (ZMod 5)[X]) ^ 5
    = R * s2 + (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 + X) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat, map_one]
  unfold R s2
  linear_combination (-X ^ 37 - X ^ 34 - X ^ 32 - 2 * X ^ 31 - X ^ 29 - 3 * X ^ 28 - X ^ 27 - 4 * X ^ 26 - 2 * X ^ 25 - X ^ 23 - X ^ 22 - 2 * X ^ 21 - 2 * X ^ 20 - 3 * X ^ 19 - X ^ 18 - 4 * X ^ 17 - 2 * X ^ 16 - X ^ 14 - X ^ 13 - X ^ 12 - 2 * X ^ 11 - 2 * X ^ 10 - 2 * X ^ 9 - X ^ 7 - 2 * X ^ 6 - 2 * X ^ 4 - 2 * X ^ 3 - X - 3) * hq

private lemma step3 : (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 + X : (ZMod 5)[X]) ^ 5
    = R * s3 + (2 * X ^ 8 + 3 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + 2 * X ^ 4 + 2 * X ^ 3 + 2 * X + 2) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold R s3
  linear_combination (-X ^ 32 - X ^ 29 - 2 * X ^ 27 - 4 * X ^ 26 - X ^ 24 - X ^ 23 - X ^ 22 - 3 * X ^ 21 - 3 * X ^ 20 - 2 * X ^ 19 - 4 * X ^ 18 - X ^ 17 - X ^ 16 - 2 * X ^ 14 - 4 * X ^ 13 - 3 * X ^ 12 - 3 * X ^ 11 - 4 * X ^ 10 - 2 * X ^ 9 - 4 * X ^ 8 - 3 * X ^ 7 - X ^ 6 - X ^ 5 - 3 * X ^ 4 - 2 * X ^ 3 - 4 * X ^ 2 - 4 * X - 2) * hq

private lemma step4 : (2 * X ^ 8 + 3 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + 2 * X ^ 4 + 2 * X ^ 3 + 2 * X + 2 : (ZMod 5)[X]) ^ 5
    = R * s4 + (3 * X ^ 8 + 4 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + X ^ 3 + X ^ 2 + X + 2) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold R s4
  linear_combination (-X ^ 37 - X ^ 34 - X ^ 32 - 2 * X ^ 31 - X ^ 29 - 3 * X ^ 28 - 2 * X ^ 27 - 4 * X ^ 26 - 2 * X ^ 25 - X ^ 24 - X ^ 23 - X ^ 22 - 3 * X ^ 21 - 2 * X ^ 20 - 4 * X ^ 19 - 4 * X ^ 18 - 4 * X ^ 17 - 3 * X ^ 16 - X ^ 15 - 2 * X ^ 14 - X ^ 13 - X ^ 12 - 2 * X ^ 11 - 4 * X ^ 10 - X ^ 9 - 3 * X ^ 8 - 3 * X ^ 7 - 3 * X ^ 6 - 4 * X ^ 5 - 3 * X ^ 4 - 3 * X ^ 3 - 2 * X ^ 2 - X) * hq

private lemma step5 : (3 * X ^ 8 + 4 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + X ^ 3 + X ^ 2 + X + 2 : (ZMod 5)[X]) ^ 5
    = R * s5 + (3 * X ^ 6 + 4 * X ^ 5 + 2 * X ^ 4 + X ^ 3 + 3 * X ^ 2 + 1) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold R s5
  linear_combination (-X ^ 37 - X ^ 34 - 2 * X ^ 32 - 3 * X ^ 31 - X ^ 29 - 2 * X ^ 28 - 2 * X ^ 27 - 4 * X ^ 26 - 3 * X ^ 25 - 2 * X ^ 24 - 3 * X ^ 23 - 2 * X ^ 22 - 4 * X ^ 21 - X ^ 20 - 3 * X ^ 19 - 4 * X ^ 18 - 2 * X ^ 17 - 5 * X ^ 16 - 4 * X ^ 15 - 3 * X ^ 14 - 4 * X ^ 13 - 4 * X ^ 12 - 2 * X ^ 11 - 2 * X ^ 10 - 4 * X ^ 9 - 2 * X ^ 8 - 4 * X ^ 7 - 2 * X ^ 6 - 3 * X ^ 5 - X ^ 4 - 3 * X ^ 3 - 3 * X ^ 2 - 4 * X - 3) * hq

private lemma step6 : (3 * X ^ 6 + 4 * X ^ 5 + 2 * X ^ 4 + X ^ 3 + 3 * X ^ 2 + 1 : (ZMod 5)[X]) ^ 5
    = R * s6 + (4 * X ^ 8 + 2 * X ^ 6 + X ^ 5 + X ^ 4 + 2 * X ^ 3 + 2 * X + 3) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat, map_one]
  unfold R s6
  linear_combination (-X ^ 27 - X ^ 24 - 2 * X ^ 22 - 3 * X ^ 21 - X ^ 19 - 2 * X ^ 18 - 2 * X ^ 17 - 4 * X ^ 16 - 3 * X ^ 15 - 2 * X ^ 14 - 3 * X ^ 13 - X ^ 12 - 3 * X ^ 11 - X ^ 10 - 3 * X ^ 9 - 5 * X ^ 8 - 2 * X ^ 7 - 3 * X ^ 6 - 3 * X ^ 5 - 2 * X ^ 4 - 2 * X ^ 3 - 4 * X ^ 2 - 4 * X - 2) * hq

private lemma step7 : (4 * X ^ 8 + 2 * X ^ 6 + X ^ 5 + X ^ 4 + 2 * X ^ 3 + 2 * X + 3 : (ZMod 5)[X]) ^ 5
    = R * s7 + (4 * X ^ 8 + X ^ 7 + 2 * X ^ 4 + 4 * X ^ 3 + X ^ 2 + 2 * X + 1) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold R s7
  linear_combination (-X ^ 37 - X ^ 34 - X ^ 32 - 4 * X ^ 31 - X ^ 29 - X ^ 28 - X ^ 27 - 2 * X ^ 26 - 4 * X ^ 25 - X ^ 24 - 2 * X ^ 23 - 2 * X ^ 22 - 3 * X ^ 21 - 3 * X ^ 20 - 3 * X ^ 19 - 4 * X ^ 18 - 4 * X ^ 17 - 5 * X ^ 16 - 2 * X ^ 15 - 4 * X ^ 14 - 5 * X ^ 13 - 3 * X ^ 12 - X ^ 11 - 4 * X ^ 10 - 3 * X ^ 9 - 5 * X ^ 8 - 4 * X ^ 7 - 3 * X ^ 6 - 2 * X ^ 4 - X ^ 3 - X ^ 2 - X - 2) * hq

private lemma step8 : (4 * X ^ 8 + X ^ 7 + 2 * X ^ 4 + 4 * X ^ 3 + X ^ 2 + 2 * X + 1 : (ZMod 5)[X]) ^ 5
    = R * s8 + (X) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat, map_one]
  unfold R s8
  linear_combination (-X ^ 37 - X ^ 34 - X ^ 32 - 4 * X ^ 31 - X ^ 29 - X ^ 28 - X ^ 27 - 3 * X ^ 26 - 4 * X ^ 25 - X ^ 24 - X ^ 23 - X ^ 22 - X ^ 21 - 4 * X ^ 20 - 2 * X ^ 19 - 4 * X ^ 18 - 4 * X ^ 17 - 3 * X ^ 16 - X ^ 15 - 3 * X ^ 14 - 2 * X ^ 13 - X ^ 12 - 3 * X ^ 11 - 2 * X ^ 9 - 2 * X ^ 8 - 2 * X ^ 7 - 3 * X ^ 6 - 2 * X ^ 5 - X - 3) * hq

/-- Rung 0 of the ladder: `X ^ (q ^ 0) = X`. -/
private lemma rung0 : R ∣ X ^ (Nat.card (ZMod 5) ^ 0) - X := by simp

private lemma rung1 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 1) - (X ^ 5) := by
  refine Rabin.dvd_sub_step (s := s0) rung0 ?_
  rw [card_zmod]; exact step0

private lemma rung2 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 2) - (2 * X ^ 8 + 3 * X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + X + 1) := by
  refine Rabin.dvd_sub_step (s := s1) rung1 ?_
  rw [card_zmod]; exact step1

private lemma rung3 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 3) - (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 + X) := by
  refine Rabin.dvd_sub_step (s := s2) rung2 ?_
  rw [card_zmod]; exact step2

private lemma rung4 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 4) - (2 * X ^ 8 + 3 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + 2 * X ^ 4 + 2 * X ^ 3 + 2 * X + 2) := by
  refine Rabin.dvd_sub_step (s := s3) rung3 ?_
  rw [card_zmod]; exact step3

private lemma rung5 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 5) - (3 * X ^ 8 + 4 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + X ^ 3 + X ^ 2 + X + 2) := by
  refine Rabin.dvd_sub_step (s := s4) rung4 ?_
  rw [card_zmod]; exact step4

private lemma rung6 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 6) - (3 * X ^ 6 + 4 * X ^ 5 + 2 * X ^ 4 + X ^ 3 + 3 * X ^ 2 + 1) := by
  refine Rabin.dvd_sub_step (s := s5) rung5 ?_
  rw [card_zmod]; exact step5

private lemma rung7 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 7) - (4 * X ^ 8 + 2 * X ^ 6 + X ^ 5 + X ^ 4 + 2 * X ^ 3 + 2 * X + 3) := by
  refine Rabin.dvd_sub_step (s := s6) rung6 ?_
  rw [card_zmod]; exact step6

private lemma rung8 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 8) - (4 * X ^ 8 + X ^ 7 + 2 * X ^ 4 + 4 * X ^ 3 + X ^ 2 + 2 * X + 1) := by
  refine Rabin.dvd_sub_step (s := s7) rung7 ?_
  rw [card_zmod]; exact step7

private lemma rung9 :
    R ∣ X ^ (Nat.card (ZMod 5) ^ 9) - (X) := by
  refine Rabin.dvd_sub_step (s := s8) rung8 ?_
  rw [card_zmod]; exact step8

private lemma ladder : R ∣ X ^ (Nat.card (ZMod 5) ^ 9) - X := rung9

/-- Bézout certificate for the prime `3 ∣ 9`: `gcd(f, X^(q^3) - X) = 1`. -/
private lemma bezout3 : IsCoprime R (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3) :=
  ⟨4 * X ^ 6 + 2 * X ^ 5 + 2 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 4, 4 * X ^ 8 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 + 3 * X ^ 2 + X + 1, by
    unfold R
    linear_combination (4 * X ^ 15 + 2 * X ^ 14 + 2 * X ^ 13 + 5 * X ^ 12 + 6 * X ^ 11 + 6 * X ^ 10 + 5 * X ^ 9 + 6 * X ^ 8 + 6 * X ^ 7 + 8 * X ^ 6 + 4 * X ^ 5 + 3 * X ^ 4 + 2 * X ^ 3 + 4 * X ^ 2 + 4 * X + 3) * hq⟩

private lemma coprime3 : IsCoprime R (X ^ (Nat.card (ZMod 5) ^ 3) - X) := by
  refine Rabin.isCoprime_of_reduction (r := (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 : (ZMod 5)[X])) ?_ bezout3
  have e : ((X : (ZMod 5)[X]) ^ (Nat.card (ZMod 5) ^ 3) - X) - (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3)
      = X ^ (Nat.card (ZMod 5) ^ 3) - (4 * X ^ 7 + 2 * X ^ 6 + 4 * X ^ 4 + 2 * X ^ 3 + X) := by
    linear_combination (0) * hq
  rw [e]
  exact rung3

/-- Note Proposition 4.1: the base scheme of the reduced pencil is `Spec F_{5^9}`. -/
public theorem irreducible_R : Irreducible R := by
  refine Rabin.irreducible_of_rabin R_monic ?_ ?_ ?_
  · rw [R_natDegree]; norm_num
  · rw [R_natDegree]; exact ladder
  · intro l hl hdvd
    rw [R_natDegree] at hdvd ⊢
    have hpow : l ∣ 3 ^ 2 := by simpa using hdvd
    have : l = 3 :=
      (Nat.prime_dvd_prime_iff_eq hl (by decide)).1 (hl.dvd_of_dvd_pow hpow)
    subst this
    exact coprime3

end NonicF5

end ExplicitUnirational.Cert
