/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.Cert.Rabin
public import Mathlib.Tactic.ComputeDegree
public import Mathlib.Tactic.LinearCombination

/-!
# Irreducibility of the octic over `F₇` (note Appendix A)

Note eq. (3.14) reduces mod 7 to `5z^8 + z^7 + 2z^6 + 5z^5 + 5z^4 + 6z^3 + 2z^2 + z + 5`;
multiplying by 3 makes it monic. Irreducibility here plus Gauss's lemma gives
irreducibility of `q₈` over `ℚ` (note §3.2).

The Frobenius ladder is generated by exact arithmetic in `F_q[X]/(f)` and re-checked
here: each rung is `r_k ^ q = f * s_k + r_(k+1)`, closed by rewriting the `q`-th power
as `X ↦ X ^ q` (`Rabin.pow_card_eq_expand`) and then a `linear_combination` against the
characteristic. Coprimality is certified by an explicit Bézout pair.
-/

noncomputable section

open Polynomial

namespace ExplicitUnirational.Cert

section OcticF7

private instance : Fact (Nat.Prime 7) := ⟨by decide⟩

private lemma hq : (7 : (ZMod 7)[X]) = 0 := by
  simpa using CharP.cast_eq_zero ((ZMod 7)[X]) 7

private lemma card_zmod : Nat.card (ZMod 7) = 7 := Nat.card_zmod 7

/-- The monic reduction mod 7 of the octic `q₈` of note eq. (3.14), scaled by 3. -/
public def f8 : (ZMod 7)[X] := X ^ 8 + 3 * X ^ 7 + 6 * X ^ 6 + X ^ 5 + X ^ 4 + 4 * X ^ 3 + 6 * X ^ 2 + 3 * X + 1

public lemma f8_monic : f8.Monic := by
  unfold f8; monicity!

public lemma f8_natDegree : f8.natDegree = 8 := by
  unfold f8; compute_degree!

private def s0 : (ZMod 7)[X] := 0
private def s1 : (ZMod 7)[X] := X ^ 41 + 4 * X ^ 40 + 3 * X ^ 39 + X ^ 38 + 2 * X ^ 37 + 5 * X ^ 36 + 3 * X ^ 35 + 3 * X ^ 34 + X ^ 33 + 6 * X ^ 31 + 6 * X ^ 30 + 3 * X ^ 29 + 4 * X ^ 28 + 3 * X ^ 27 + 5 * X ^ 26 + 4 * X ^ 25 + 4 * X ^ 24 + 3 * X ^ 23 + 5 * X ^ 22 + 4 * X ^ 21 + 4 * X ^ 20 + 3 * X ^ 19 + 3 * X ^ 18 + 2 * X ^ 17 + X ^ 16 + 5 * X ^ 15 + 5 * X ^ 14 + 4 * X ^ 13 + 4 * X ^ 12 + 3 * X ^ 11 + 3 * X ^ 9 + 6 * X ^ 8 + 6 * X ^ 7 + 2 * X ^ 6 + 6 * X ^ 5 + 3 * X ^ 4 + 3 * X ^ 2 + X
private def s2 : (ZMod 7)[X] := X ^ 41 + 4 * X ^ 40 + 3 * X ^ 39 + X ^ 38 + 2 * X ^ 37 + 5 * X ^ 36 + 3 * X ^ 35 + 3 * X ^ 34 + X ^ 33 + 6 * X ^ 31 + 6 * X ^ 30 + 3 * X ^ 29 + 4 * X ^ 28 + 3 * X ^ 27 + 5 * X ^ 26 + 4 * X ^ 25 + 4 * X ^ 24 + 3 * X ^ 23 + 5 * X ^ 22 + 4 * X ^ 21 + X ^ 19 + 5 * X ^ 18 + 5 * X ^ 17 + 6 * X ^ 15 + 5 * X ^ 13 + 3 * X ^ 12 + 3 * X ^ 10 + 5 * X ^ 9 + 3 * X ^ 8 + X ^ 7 + 2 * X ^ 6 + 3 * X ^ 5 + 4 * X ^ 4 + X ^ 2 + 4 * X + 4
private def s3 : (ZMod 7)[X] := 5 * X ^ 41 + 6 * X ^ 40 + X ^ 39 + 5 * X ^ 38 + 3 * X ^ 37 + 4 * X ^ 36 + X ^ 35 + X ^ 33 + 4 * X ^ 32 + X ^ 31 + 3 * X ^ 29 + 3 * X ^ 28 + 6 * X ^ 27 + 2 * X ^ 25 + X ^ 24 + 4 * X ^ 23 + 6 * X ^ 22 + 5 * X ^ 21 + 4 * X ^ 20 + 3 * X ^ 19 + 5 * X ^ 18 + 3 * X ^ 17 + 4 * X ^ 16 + 6 * X ^ 15 + 5 * X ^ 14 + 5 * X ^ 13 + 2 * X ^ 12 + 6 * X ^ 11 + 3 * X ^ 10 + 3 * X ^ 9 + 5 * X ^ 8 + 4 * X ^ 7 + 6 * X ^ 6 + 3 * X ^ 5 + X ^ 4 + 4 * X ^ 2 + 2 * X + 2
private def s4 : (ZMod 7)[X] := 2 * X ^ 41 + X ^ 40 + 6 * X ^ 39 + 2 * X ^ 38 + 4 * X ^ 37 + 3 * X ^ 36 + 6 * X ^ 35 + 2 * X ^ 34 + 2 * X ^ 32 + X ^ 31 + 4 * X ^ 30 + 3 * X ^ 28 + 3 * X ^ 27 + X ^ 22 + 5 * X ^ 21 + 2 * X ^ 20 + 2 * X ^ 19 + 4 * X ^ 18 + 2 * X ^ 16 + 3 * X ^ 15 + 2 * X ^ 14 + X ^ 13 + 4 * X ^ 12 + 4 * X ^ 11 + 3 * X ^ 10 + 3 * X ^ 8 + 2 * X ^ 7 + 4 * X ^ 6 + X ^ 5 + 4 * X ^ 4 + 5 * X ^ 2 + 6 * X + 2
private def s5 : (ZMod 7)[X] := 2 * X ^ 34 + X ^ 33 + 6 * X ^ 32 + 2 * X ^ 31 + 4 * X ^ 30 + 3 * X ^ 29 + 6 * X ^ 28 + 6 * X ^ 26 + 3 * X ^ 25 + 6 * X ^ 24 + 4 * X ^ 22 + 4 * X ^ 21 + 5 * X ^ 20 + 2 * X ^ 19 + 3 * X ^ 18 + 3 * X ^ 17 + 4 * X ^ 16 + 3 * X ^ 13 + 2 * X ^ 12 + X ^ 11 + 2 * X ^ 10 + 3 * X ^ 9 + 2 * X ^ 8 + 3 * X ^ 7 + 5 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 5 * X ^ 2 + 2 * X + 3
private def s6 : (ZMod 7)[X] := 6 * X ^ 41 + 3 * X ^ 40 + 4 * X ^ 39 + 6 * X ^ 38 + 5 * X ^ 37 + 2 * X ^ 36 + 4 * X ^ 35 + 5 * X ^ 34 + 3 * X ^ 33 + 3 * X ^ 32 + 2 * X ^ 31 + 3 * X ^ 30 + 2 * X ^ 29 + 6 * X ^ 28 + 4 * X ^ 27 + 5 * X ^ 26 + X ^ 25 + 6 * X ^ 24 + 4 * X ^ 23 + 4 * X ^ 22 + 5 * X ^ 21 + 3 * X ^ 20 + 2 * X ^ 19 + 5 * X ^ 18 + 4 * X ^ 17 + 3 * X ^ 16 + 5 * X ^ 14 + 2 * X ^ 13 + 4 * X ^ 12 + 2 * X ^ 11 + 5 * X ^ 10 + 4 * X ^ 9 + 2 * X ^ 8 + 4 * X ^ 7 + X ^ 5 + 5 * X ^ 4 + 3 * X ^ 3 + 6 * X ^ 2 + X + 5
private def s7 : (ZMod 7)[X] := 6 * X ^ 41 + 3 * X ^ 40 + 4 * X ^ 39 + 6 * X ^ 38 + 5 * X ^ 37 + 2 * X ^ 36 + 4 * X ^ 35 + 6 * X ^ 34 + 6 * X ^ 32 + 3 * X ^ 31 + 5 * X ^ 30 + 2 * X ^ 28 + 2 * X ^ 27 + 3 * X ^ 22 + X ^ 21 + 3 * X ^ 20 + X ^ 19 + 3 * X ^ 18 + 4 * X ^ 17 + X ^ 15 + 4 * X ^ 14 + X ^ 13 + 2 * X ^ 12 + 5 * X ^ 11 + 5 * X ^ 10 + 3 * X ^ 9 + X ^ 7 + 2 * X ^ 6 + 5 * X ^ 5 + 4 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 5 * X + 5

private lemma step0 : (X : (ZMod 7)[X]) ^ 7
    = f8 * s0 + (X ^ 7) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [expand_X]
  unfold f8 s0
  linear_combination (0) * hq

private lemma step1 : (X ^ 7 : (ZMod 7)[X]) ^ 7
    = f8 * s1 + (X ^ 7 + 3 * X ^ 4 + 6 * X ^ 3 + X ^ 2 + 6 * X) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_pow, expand_X]
  unfold f8 s1
  linear_combination (-X ^ 48 - 3 * X ^ 47 - 5 * X ^ 46 - 4 * X ^ 45 - 4 * X ^ 44 - 8 * X ^ 43 - 12 * X ^ 42 - 10 * X ^ 41 - 8 * X ^ 40 - 8 * X ^ 39 - 11 * X ^ 38 - 15 * X ^ 37 - 13 * X ^ 36 - 9 * X ^ 35 - 11 * X ^ 34 - 15 * X ^ 33 - 17 * X ^ 32 - 15 * X ^ 31 - 14 * X ^ 30 - 14 * X ^ 29 - 16 * X ^ 28 - 15 * X ^ 27 - 14 * X ^ 26 - 13 * X ^ 25 - 13 * X ^ 24 - 12 * X ^ 23 - 12 * X ^ 22 - 14 * X ^ 21 - 13 * X ^ 20 - 11 * X ^ 19 - 11 * X ^ 18 - 12 * X ^ 17 - 12 * X ^ 16 - 15 * X ^ 15 - 16 * X ^ 14 - 13 * X ^ 13 - 10 * X ^ 12 - 14 * X ^ 11 - 14 * X ^ 10 - 12 * X ^ 9 - 12 * X ^ 8 - 10 * X ^ 7 - 6 * X ^ 6 - 4 * X ^ 5 - 4 * X ^ 4 - 3 * X ^ 3 - X ^ 2 - X) * hq

private lemma step2 : (X ^ 7 + 3 * X ^ 4 + 6 * X ^ 3 + X ^ 2 + 6 * X : (ZMod 7)[X]) ^ 7
    = f8 * s2 + (5 * X ^ 7 + 6 * X ^ 6 + X ^ 5 + 5 * X ^ 4 + 6 * X ^ 3 + 5 * X ^ 2 + 5 * X + 3) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold f8 s2
  linear_combination (-X ^ 48 - 3 * X ^ 47 - 5 * X ^ 46 - 4 * X ^ 45 - 4 * X ^ 44 - 8 * X ^ 43 - 12 * X ^ 42 - 10 * X ^ 41 - 8 * X ^ 40 - 8 * X ^ 39 - 11 * X ^ 38 - 15 * X ^ 37 - 13 * X ^ 36 - 9 * X ^ 35 - 11 * X ^ 34 - 15 * X ^ 33 - 17 * X ^ 32 - 15 * X ^ 31 - 14 * X ^ 30 - 14 * X ^ 29 - 15 * X ^ 28 - 13 * X ^ 27 - 10 * X ^ 26 - 12 * X ^ 25 - 15 * X ^ 24 - 12 * X ^ 23 - 7 * X ^ 22 - 10 * X ^ 21 - 11 * X ^ 20 - 13 * X ^ 19 - 10 * X ^ 18 - 9 * X ^ 17 - 11 * X ^ 16 - 13 * X ^ 15 - 9 * X ^ 14 - 7 * X ^ 13 - 10 * X ^ 12 - 12 * X ^ 11 - 10 * X ^ 10 - 6 * X ^ 9 - 8 * X ^ 8 - 11 * X ^ 7 - 10 * X ^ 6 - 4 * X ^ 5 - 5 * X ^ 4 - 7 * X ^ 3 - 6 * X ^ 2 - 3 * X - 1) * hq

private lemma step3 : (5 * X ^ 7 + 6 * X ^ 6 + X ^ 5 + 5 * X ^ 4 + 6 * X ^ 3 + 5 * X ^ 2 + 5 * X + 3 : (ZMod 7)[X]) ^ 7
    = f8 * s3 + (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 6 * X + 1) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold f8 s3
  linear_combination (-3 * X ^ 48 - 7 * X ^ 47 - 7 * X ^ 46 - 5 * X ^ 45 - 10 * X ^ 44 - 13 * X ^ 43 - 12 * X ^ 42 - 9 * X ^ 41 - 9 * X ^ 40 - 10 * X ^ 39 - 10 * X ^ 38 - 5 * X ^ 37 - 4 * X ^ 36 - 8 * X ^ 35 - 10 * X ^ 34 - 9 * X ^ 33 - 5 * X ^ 32 - 8 * X ^ 31 - 11 * X ^ 30 - 14 * X ^ 29 - 12 * X ^ 28 - 11 * X ^ 27 - 11 * X ^ 26 - 14 * X ^ 25 - 17 * X ^ 24 - 16 * X ^ 23 - 16 * X ^ 22 - 16 * X ^ 21 - 16 * X ^ 20 - 15 * X ^ 19 - 15 * X ^ 18 - 18 * X ^ 17 - 16 * X ^ 16 - 15 * X ^ 15 - 15 * X ^ 14 - 16 * X ^ 13 - 15 * X ^ 12 - 12 * X ^ 11 - 11 * X ^ 10 - 12 * X ^ 9 - 14 * X ^ 8 - 9 * X ^ 7 - 6 * X ^ 6 - 4 * X ^ 5 - 5 * X ^ 4 - 5 * X ^ 3 - 4 * X ^ 2 - 2 * X) * hq

private lemma step4 : (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 6 * X + 1 : (ZMod 7)[X]) ^ 7
    = f8 * s4 + (2 * X ^ 6 + X ^ 5 + 3 * X ^ 4 + 4 * X ^ 3 + 2 * X + 6) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat, map_one]
  unfold f8 s4
  linear_combination (-X ^ 48 - 3 * X ^ 47 - 4 * X ^ 46 - 7 * X ^ 45 - 6 * X ^ 44 - 9 * X ^ 43 - 11 * X ^ 42 - 14 * X ^ 41 - 10 * X ^ 40 - 9 * X ^ 39 - 11 * X ^ 38 - 11 * X ^ 37 - 9 * X ^ 36 - 5 * X ^ 35 - 7 * X ^ 34 - 7 * X ^ 33 - 5 * X ^ 32 - 4 * X ^ 31 - 5 * X ^ 30 - 5 * X ^ 29 - 5 * X ^ 28 - 6 * X ^ 27 - 4 * X ^ 26 - 5 * X ^ 25 - 8 * X ^ 24 - 8 * X ^ 23 - 9 * X ^ 22 - 9 * X ^ 21 - 8 * X ^ 20 - 7 * X ^ 19 - 10 * X ^ 18 - 10 * X ^ 17 - 8 * X ^ 16 - 7 * X ^ 15 - 10 * X ^ 14 - 11 * X ^ 13 - 10 * X ^ 12 - 7 * X ^ 11 - 9 * X ^ 10 - 9 * X ^ 9 - 13 * X ^ 8 - 11 * X ^ 7 - 8 * X ^ 6 - 6 * X ^ 5 - 9 * X ^ 4 - 9 * X ^ 3 - 5 * X ^ 2 - 2 * X - 1) * hq

private lemma step5 : (2 * X ^ 6 + X ^ 5 + 3 * X ^ 4 + 4 * X ^ 3 + 2 * X + 6 : (ZMod 7)[X]) ^ 7
    = f8 * s5 + (6 * X ^ 7 + X ^ 6 + 4 * X ^ 5 + 6 * X ^ 4 + 6 * X ^ 2 + 3 * X + 3) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold f8 s5
  linear_combination (-X ^ 41 - 3 * X ^ 40 - 4 * X ^ 39 - 7 * X ^ 38 - 6 * X ^ 37 - 9 * X ^ 36 - 11 * X ^ 35 - 14 * X ^ 34 - 11 * X ^ 33 - 15 * X ^ 32 - 14 * X ^ 31 - 14 * X ^ 30 - 10 * X ^ 29 - 14 * X ^ 28 - 15 * X ^ 27 - 14 * X ^ 26 - 10 * X ^ 25 - 12 * X ^ 24 - 13 * X ^ 23 - 12 * X ^ 22 - 7 * X ^ 21 - 8 * X ^ 20 - 10 * X ^ 19 - 8 * X ^ 18 - 5 * X ^ 17 - 6 * X ^ 16 - 8 * X ^ 15 - 8 * X ^ 14 - 9 * X ^ 13 - 10 * X ^ 12 - 8 * X ^ 11 - 8 * X ^ 10 - 12 * X ^ 9 - 13 * X ^ 8 - 9 * X ^ 7 - 7 * X ^ 6 - 7 * X ^ 5 - 8 * X ^ 4 - 6 * X ^ 3 - 5 * X ^ 2 - 2 * X) * hq

private lemma step6 : (6 * X ^ 7 + X ^ 6 + 4 * X ^ 5 + 6 * X ^ 4 + 6 * X ^ 2 + 3 * X + 3 : (ZMod 7)[X]) ^ 7
    = f8 * s6 + (6 * X ^ 7 + 2 * X ^ 6 + 6 * X ^ 5 + 4 * X ^ 4 + 2 * X ^ 3 + 3 * X ^ 2 + 5 * X + 5) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold f8 s6
  linear_combination (-3 * X ^ 48 - 7 * X ^ 47 - 6 * X ^ 46 - 8 * X ^ 45 - 12 * X ^ 44 - 14 * X ^ 43 - 13 * X ^ 42 - 16 * X ^ 41 - 17 * X ^ 40 - 14 * X ^ 39 - 12 * X ^ 38 - 12 * X ^ 37 - 13 * X ^ 36 - 12 * X ^ 35 - 14 * X ^ 34 - 12 * X ^ 33 - 12 * X ^ 32 - 12 * X ^ 31 - 17 * X ^ 30 - 16 * X ^ 29 - 14 * X ^ 28 - 14 * X ^ 27 - 14 * X ^ 26 - 14 * X ^ 25 - 16 * X ^ 24 - 14 * X ^ 23 - 11 * X ^ 22 - 10 * X ^ 21 - 14 * X ^ 20 - 12 * X ^ 19 - 11 * X ^ 18 - 10 * X ^ 17 - 13 * X ^ 16 - 12 * X ^ 15 - 10 * X ^ 14 - 11 * X ^ 13 - 10 * X ^ 12 - 11 * X ^ 11 - 13 * X ^ 10 - 11 * X ^ 9 - 10 * X ^ 8 - 9 * X ^ 7 - 12 * X ^ 6 - 10 * X ^ 5 - 9 * X ^ 4 - 7 * X ^ 3 - 6 * X ^ 2 - 3 * X - 1) * hq

private lemma step7 : (6 * X ^ 7 + 2 * X ^ 6 + 6 * X ^ 5 + 4 * X ^ 4 + 2 * X ^ 3 + 3 * X ^ 2 + 5 * X + 5 : (ZMod 7)[X]) ^ 7
    = f8 * s7 + (X) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold f8 s7
  linear_combination (-3 * X ^ 48 - 7 * X ^ 47 - 6 * X ^ 46 - 8 * X ^ 45 - 12 * X ^ 44 - 14 * X ^ 43 - 13 * X ^ 42 - 16 * X ^ 41 - 17 * X ^ 40 - 13 * X ^ 39 - 15 * X ^ 38 - 14 * X ^ 37 - 13 * X ^ 36 - 8 * X ^ 35 - 11 * X ^ 34 - 10 * X ^ 33 - 7 * X ^ 32 - 4 * X ^ 31 - 4 * X ^ 30 - 4 * X ^ 29 - 4 * X ^ 28 - 3 * X ^ 27 - 4 * X ^ 26 - 5 * X ^ 25 - 8 * X ^ 24 - 8 * X ^ 23 - 6 * X ^ 22 - 7 * X ^ 21 - 10 * X ^ 20 - 8 * X ^ 19 - 8 * X ^ 18 - 11 * X ^ 17 - 11 * X ^ 16 - 8 * X ^ 15 - 7 * X ^ 14 - 11 * X ^ 13 - 13 * X ^ 12 - 12 * X ^ 11 - 8 * X ^ 10 - 7 * X ^ 9 - 12 * X ^ 8 - 14 * X ^ 7 - 12 * X ^ 6 - 7 * X ^ 5 - 8 * X ^ 4 - 9 * X ^ 3 - 7 * X ^ 2 - 3 * X) * hq

/-- Rung 0 of the ladder: `X ^ (q ^ 0) = X`. -/
private lemma rung0 : f8 ∣ X ^ (Nat.card (ZMod 7) ^ 0) - X := by simp

private lemma rung1 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 1) - (X ^ 7) := by
  refine Rabin.dvd_sub_step (s := s0) rung0 ?_
  rw [card_zmod]; exact step0

private lemma rung2 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 2) - (X ^ 7 + 3 * X ^ 4 + 6 * X ^ 3 + X ^ 2 + 6 * X) := by
  refine Rabin.dvd_sub_step (s := s1) rung1 ?_
  rw [card_zmod]; exact step1

private lemma rung3 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 3) - (5 * X ^ 7 + 6 * X ^ 6 + X ^ 5 + 5 * X ^ 4 + 6 * X ^ 3 + 5 * X ^ 2 + 5 * X + 3) := by
  refine Rabin.dvd_sub_step (s := s2) rung2 ?_
  rw [card_zmod]; exact step2

private lemma rung4 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 4) - (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 6 * X + 1) := by
  refine Rabin.dvd_sub_step (s := s3) rung3 ?_
  rw [card_zmod]; exact step3

private lemma rung5 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 5) - (2 * X ^ 6 + X ^ 5 + 3 * X ^ 4 + 4 * X ^ 3 + 2 * X + 6) := by
  refine Rabin.dvd_sub_step (s := s4) rung4 ?_
  rw [card_zmod]; exact step4

private lemma rung6 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 6) - (6 * X ^ 7 + X ^ 6 + 4 * X ^ 5 + 6 * X ^ 4 + 6 * X ^ 2 + 3 * X + 3) := by
  refine Rabin.dvd_sub_step (s := s5) rung5 ?_
  rw [card_zmod]; exact step5

private lemma rung7 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 7) - (6 * X ^ 7 + 2 * X ^ 6 + 6 * X ^ 5 + 4 * X ^ 4 + 2 * X ^ 3 + 3 * X ^ 2 + 5 * X + 5) := by
  refine Rabin.dvd_sub_step (s := s6) rung6 ?_
  rw [card_zmod]; exact step6

private lemma rung8 :
    f8 ∣ X ^ (Nat.card (ZMod 7) ^ 8) - (X) := by
  refine Rabin.dvd_sub_step (s := s7) rung7 ?_
  rw [card_zmod]; exact step7

private lemma ladder : f8 ∣ X ^ (Nat.card (ZMod 7) ^ 8) - X := rung8

/-- Bézout certificate for the prime `2 ∣ 8`: `gcd(f, X^(q^4) - X) = 1`. -/
private lemma bezout2 : IsCoprime f8 (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 5 * X + 1) :=
  ⟨6 * X ^ 6 + 2 * X ^ 5 + 5 * X ^ 4 + 3 * X ^ 3 + 5 * X ^ 2 + 2, 4 * X ^ 7 + 5 * X ^ 6 + 5 * X ^ 4 + 6 * X ^ 3 + X ^ 2 + 6 * X + 6, by
    unfold f8
    linear_combination (2 * X ^ 14 + 6 * X ^ 13 + 10 * X ^ 12 + 8 * X ^ 11 + 13 * X ^ 10 + 19 * X ^ 9 + 23 * X ^ 8 + 20 * X ^ 7 + 22 * X ^ 6 + 19 * X ^ 5 + 15 * X ^ 4 + 13 * X ^ 3 + 12 * X ^ 2 + 6 * X + 1) * hq⟩

private lemma coprime2 : IsCoprime f8 (X ^ (Nat.card (ZMod 7) ^ 4) - X) := by
  refine Rabin.isCoprime_of_reduction (r := (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 5 * X + 1 : (ZMod 7)[X])) ?_ bezout2
  have e : ((X : (ZMod 7)[X]) ^ (Nat.card (ZMod 7) ^ 4) - X) - (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 5 * X + 1)
      = X ^ (Nat.card (ZMod 7) ^ 4) - (2 * X ^ 7 + 3 * X ^ 6 + 2 * X ^ 5 + 3 * X ^ 3 + 6 * X ^ 2 + 6 * X + 1) := by
    linear_combination (0) * hq
  rw [e]
  exact rung4

/-- Note Appendix A, "The octic over F7": `f₈` is irreducible over `F₇`. -/
public theorem irreducible_f8 : Irreducible f8 := by
  refine Rabin.irreducible_of_rabin f8_monic ?_ ?_ ?_
  · rw [f8_natDegree]; norm_num
  · rw [f8_natDegree]; exact ladder
  · intro l hl hdvd
    rw [f8_natDegree] at hdvd ⊢
    have hpow : l ∣ 2 ^ 3 := by simpa using hdvd
    have : l = 2 :=
      (Nat.prime_dvd_prime_iff_eq hl (by decide)).1 (hl.dvd_of_dvd_pow hpow)
    subst this
    exact coprime2

end OcticF7

end ExplicitUnirational.Cert
