/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import Mathlib.Algebra.Polynomial.Derivative
public import Mathlib.Algebra.Polynomial.Eval.Defs
public import Mathlib.Algebra.Polynomial.RingDivision
public import Mathlib.FieldTheory.RatFunc.Basic
public import Mathlib.FieldTheory.Separable
public import Mathlib.RingTheory.Coprime.Basic
public import Mathlib.Tactic.ComputeDegree
public import Mathlib.Tactic.NormNum
public import Mathlib.Tactic.Ring

/-!
# Quartic discriminants of the C(t) family (computed here; not in [CLOP])

On the chart `u = 1`, the factors `Q±` of the Weierstrass discriminant of the pencil of
`[CLOP §4.2]` dehomogenize to monic quartics in `z`:

```
  q±(z) = z⁴ + 27 t² z³ ± 2 z² + 1.
```

We treat these as elements of `(ℚ[t])[z] = (Polynomial ℚ)[X]`, with outer variable `z`
and coefficient ring `Polynomial ℚ` in the parameter `t`.

## Deliverables

1. **Resultant / coprimality.** Explicit Bézout identity
   `A · q₊ + B · q₋ = 256`, hence `IsCoprime q₊ q₋` over `(ℚ[t])[z]`
   (since `256` is a unit in `ℚ ⊂ ℚ[t]`).
2. **Discriminants of `q±`.** The standard monic-quartic discriminant formula
   evaluated on the coefficients of `q±`, proved by `ring`.
3. **Nonvanishing and squarefreeness.** Each discriminant is a nonzero polynomial in `t`.
   Mapping to `ℚ(t)[z]` and clearing the nonzero disc factor of a Bézout identity for
   `(q±, q±')` yields `Separable` (hence `Squarefree`) of each `q±` over `ℚ(t)`.
-/

noncomputable section

open Polynomial

namespace ExplicitUnirational.Cert.QuarticDiscriminants

/-! ## The dehomogenized quartics `q± ∈ (ℚ[t])[z]` -/

/-- The parameter `t` as a constant (in `z`) coefficient polynomial. -/
public noncomputable def T : (Polynomial ℚ)[X] :=
  C (X : Polynomial ℚ)

/-- `q₊(z) = z⁴ + 27 t² z³ + 2 z² + 1`, the dehomogenization of `Q₊` at `u = 1`. -/
public noncomputable def qplus : (Polynomial ℚ)[X] :=
  X ^ 4 + 27 * T ^ 2 * X ^ 3 + 2 * X ^ 2 + 1

/-- `q₋(z) = z⁴ + 27 t² z³ − 2 z² + 1`, the dehomogenization of `Q₋` at `u = 1`. -/
public noncomputable def qminus : (Polynomial ℚ)[X] :=
  X ^ 4 + 27 * T ^ 2 * X ^ 3 - 2 * X ^ 2 + 1

/-! ## Resultant certificate via Bézout -/

/-- Bézout cofactor of `q₊` for the identity `A · q₊ + B · q₋ = 256`.
Generated by the extended Euclidean algorithm over `ℚ(t)[z]` and cleared of
denominators. -/
public noncomputable def resBezoutA : (Polynomial ℚ)[X] :=
  -1728 * T ^ 2 * X - 64 * X ^ 2 + 128

/-- Bézout cofactor of `q₋` for the identity `A · q₊ + B · q₋ = 256`. -/
public noncomputable def resBezoutB : (Polynomial ℚ)[X] :=
  1728 * T ^ 2 * X + 64 * X ^ 2 + 128

/-- The resultant of `q₊` and `q₋` is `256`, witnessed by an explicit
Bézout identity (preferred form for downstream coprimality). -/
public theorem res_qplus_qminus :
    resBezoutA * qplus + resBezoutB * qminus = 256 := by
  unfold resBezoutA resBezoutB qplus qminus T
  ring

/-- Coprimality of `q₊` and `q₋` over `(ℚ[t])[z]`. Since `256 ∈ ℚˣ`, the Bézout
identity scales to a unital combination. -/
public theorem isCoprime_qplus_qminus : IsCoprime qplus qminus := by
  refine ⟨C (C (1 / 256 : ℚ)) * resBezoutA, C (C (1 / 256 : ℚ)) * resBezoutB, ?_⟩
  have h := res_qplus_qminus
  -- Scale the identity by `1/256`.
  calc
    (C (C (1 / 256 : ℚ)) * resBezoutA) * qplus
        + (C (C (1 / 256 : ℚ)) * resBezoutB) * qminus
        = C (C (1 / 256 : ℚ)) * (resBezoutA * qplus + resBezoutB * qminus) := by ring
    _ = C (C (1 / 256 : ℚ)) * 256 := by rw [h]
    _ = 1 := by
      -- `256 = C (C 256)` as a nested polynomial numeral.
      have h256 : (256 : (Polynomial ℚ)[X]) = C (C (256 : ℚ)) := by
        simp only [map_ofNat]
      rw [h256, ← map_mul, ← map_mul]
      norm_num

/-! ## Monic quartic discriminant formula and `disc(q±)` -/

/-- Standard discriminant of the monic quartic `X⁴ + a X³ + b X² + c X + d`, as a
polynomial identity in the four coefficients. Agrees with Mathlib's `Polynomial.discr`
on monic degree-4 polynomials over any commutative ring (we use the closed formula
directly because Mathlib only expands `discr` through degree 3). -/
public noncomputable def monicQuarticDisc (a b c d : Polynomial ℚ) : Polynomial ℚ :=
  -27 * a ^ 4 * d ^ 2 + 18 * a ^ 3 * b * c * d - 4 * a ^ 3 * c ^ 3
    - 4 * a ^ 2 * b ^ 3 * d + a ^ 2 * b ^ 2 * c ^ 2 + 144 * a ^ 2 * b * d ^ 2
    - 6 * a ^ 2 * c ^ 2 * d - 80 * a * b ^ 2 * c * d + 18 * a * b * c ^ 3
    - 192 * a * c * d ^ 2 + 16 * b ^ 4 * d - 4 * b ^ 3 * c ^ 2 - 128 * b ^ 2 * d ^ 2
    + 144 * b * c ^ 2 * d - 27 * c ^ 4 + 256 * d ^ 3

/-- Discriminant of `q₊` as a polynomial in `t` (coefficients of `q₊`). -/
public noncomputable def disc_qplus : Polynomial ℚ :=
  monicQuarticDisc (27 * X ^ 2) 2 0 1

/-- Discriminant of `q₋` as a polynomial in `t` (coefficients of `q₋`). -/
public noncomputable def disc_qminus : Polynomial ℚ :=
  monicQuarticDisc (27 * X ^ 2) (-2) 0 1

/-- `disc(q₊) = −729 t⁴ (19683 t⁴ − 256)`. -/
public theorem disc_qplus_eq :
    disc_qplus = -729 * X ^ 4 * (19683 * X ^ 4 - 256) := by
  unfold disc_qplus monicQuarticDisc
  ring

/-- `disc(q₋) = −729 t⁴ (19683 t⁴ + 256)`. -/
public theorem disc_qminus_eq :
    disc_qminus = -729 * X ^ 4 * (19683 * X ^ 4 + 256) := by
  unfold disc_qminus monicQuarticDisc
  ring

/-! ## Nonvanishing in `ℚ[t]` (hence in `ℚ(t)`) -/

/-- The discriminant of `q₊` is a nonzero polynomial in `t`. -/
public theorem disc_qplus_ne_zero : disc_qplus ≠ 0 := by
  rw [disc_qplus_eq]
  intro h
  have h1 : (eval (1 : ℚ) (-729 * X ^ 4 * (19683 * X ^ 4 - 256) : Polynomial ℚ)) = 0 := by
    simpa using congrArg (eval (1 : ℚ)) h
  simp only [eval_mul, eval_pow, eval_X, eval_sub, eval_ofNat, eval_neg] at h1
  norm_num at h1

/-- The discriminant of `q₋` is a nonzero polynomial in `t`. -/
public theorem disc_qminus_ne_zero : disc_qminus ≠ 0 := by
  rw [disc_qminus_eq]
  intro h
  have h1 : (eval (1 : ℚ) (-729 * X ^ 4 * (19683 * X ^ 4 + 256) : Polynomial ℚ)) = 0 := by
    simpa using congrArg (eval (1 : ℚ)) h
  simp only [eval_mul, eval_pow, eval_X, eval_add, eval_ofNat, eval_neg] at h1
  norm_num at h1

/-- The resultant constant `256` is nonzero (trivial, recorded for the discriminant/resultant package). -/
public theorem res_qplus_qminus_ne_zero :
    (256 : Polynomial ℚ) ≠ 0 := by
  norm_num

/-! ## Squarefreeness of `q±` over `ℚ(t)` -/

/-- Coefficient map `ℚ[t] → ℚ(t)`. -/
private noncomputable abbrev toFF : Polynomial ℚ →+* RatFunc ℚ :=
  algebraMap (Polynomial ℚ) (RatFunc ℚ)

/-- `q₊` viewed in `ℚ(t)[z]`. -/
public noncomputable def qplusFF : (RatFunc ℚ)[X] :=
  qplus.map toFF

/-- `q₋` viewed in `ℚ(t)[z]`. -/
public noncomputable def qminusFF : (RatFunc ℚ)[X] :=
  qminus.map toFF

/-- Intermediate disc factor appearing in the Euclidean algorithm for `(q₊, q₊')`,
as a constant (in `z`) polynomial: `27 t² (19683 t⁴ − 256)`. -/
private noncomputable def sepFactorPlus : (Polynomial ℚ)[X] :=
  27 * T ^ 2 * (19683 * T ^ 4 - 256)

/-- Intermediate disc factor for `(q₋, q₋')`: `27 t² (19683 t⁴ + 256)`. -/
private noncomputable def sepFactorMinus : (Polynomial ℚ)[X] :=
  27 * T ^ 2 * (19683 * T ^ 4 + 256)

/-- The same factor as an element of `ℚ[t]`. -/
private noncomputable def sepFactorPlus_coeff : Polynomial ℚ :=
  27 * X ^ 2 * (19683 * X ^ 4 - 256)

private noncomputable def sepFactorMinus_coeff : Polynomial ℚ :=
  27 * X ^ 2 * (19683 * X ^ 4 + 256)

private theorem sepFactorPlus_eq_C : sepFactorPlus = C sepFactorPlus_coeff := by
  unfold sepFactorPlus sepFactorPlus_coeff T
  simp only [map_mul, map_sub, map_pow, map_ofNat]

private theorem sepFactorMinus_eq_C : sepFactorMinus = C sepFactorMinus_coeff := by
  unfold sepFactorMinus sepFactorMinus_coeff T
  simp only [map_mul, map_add, map_pow, map_ofNat]

private theorem sepFactorPlus_coeff_ne_zero : sepFactorPlus_coeff ≠ 0 := by
  unfold sepFactorPlus_coeff
  intro h
  have h1 : (eval (1 : ℚ) (27 * X ^ 2 * (19683 * X ^ 4 - 256) : Polynomial ℚ)) = 0 := by
    simpa using congrArg (eval (1 : ℚ)) h
  simp only [eval_mul, eval_pow, eval_X, eval_sub, eval_ofNat] at h1
  norm_num at h1

private theorem sepFactorMinus_coeff_ne_zero : sepFactorMinus_coeff ≠ 0 := by
  unfold sepFactorMinus_coeff
  intro h
  have h1 : (eval (1 : ℚ) (27 * X ^ 2 * (19683 * X ^ 4 + 256) : Polynomial ℚ)) = 0 := by
    simpa using congrArg (eval (1 : ℚ)) h
  simp only [eval_mul, eval_pow, eval_X, eval_add, eval_ofNat] at h1
  norm_num at h1

/-- Explicit formal derivative of `q₊` (avoids `C n` vs numeral issues under `ring`). -/
private noncomputable def qplusDeriv : (Polynomial ℚ)[X] :=
  4 * X ^ 3 + 81 * T ^ 2 * X ^ 2 + 4 * X

/-- Explicit formal derivative of `q₋`. -/
private noncomputable def qminusDeriv : (Polynomial ℚ)[X] :=
  4 * X ^ 3 + 81 * T ^ 2 * X ^ 2 - 4 * X

private theorem derivative_qplus : derivative qplus = qplusDeriv := by
  unfold qplus qplusDeriv T
  simp only [derivative_add, derivative_mul, derivative_pow, derivative_C,
    derivative_X, derivative_one, derivative_ofNat, map_natCast, mul_zero, zero_mul, add_zero,
    zero_add, mul_one]
  ring

private theorem derivative_qminus : derivative qminus = qminusDeriv := by
  unfold qminus qminusDeriv T
  simp only [derivative_add, derivative_sub, derivative_mul, derivative_pow, derivative_C,
    derivative_X, derivative_one, derivative_ofNat, map_natCast, mul_zero, zero_mul, add_zero,
    zero_add, mul_one]
  ring

/-- Bézout cofactor of `q₊` for separability: `A · q₊ + B · q₊' = sepFactorPlus`. -/
private noncomputable def sepBezoutA_plus : (Polynomial ℚ)[X] :=
  -432 * T ^ 2 * X ^ 2 + (17496 * T ^ 4 - 256) * X + 531441 * T ^ 6 - 6912 * T ^ 2

/-- Bézout cofactor of `q₊'` for separability. -/
private noncomputable def sepBezoutB_plus : (Polynomial ℚ)[X] :=
  108 * T ^ 2 * X ^ 3 + (64 - 3645 * T ^ 4) * X ^ 2
    + (-177147 * T ^ 6 + 2268 * T ^ 2) * X + 64 - 4374 * T ^ 4

private theorem sep_bezout_plus :
    sepBezoutA_plus * qplus + sepBezoutB_plus * derivative qplus
      = sepFactorPlus := by
  rw [derivative_qplus]
  -- Keep `T` folded so both sides share the same atom for `ring`.
  unfold sepBezoutA_plus sepBezoutB_plus qplus qplusDeriv sepFactorPlus
  ring

/-- Bézout cofactor of `q₋` for separability. -/
private noncomputable def sepBezoutA_minus : (Polynomial ℚ)[X] :=
  -432 * T ^ 2 * X ^ 2 + (17496 * T ^ 4 + 256) * X + 531441 * T ^ 6 + 6912 * T ^ 2

/-- Bézout cofactor of `q₋'` for separability. -/
private noncomputable def sepBezoutB_minus : (Polynomial ℚ)[X] :=
  108 * T ^ 2 * X ^ 3 + (-3645 * T ^ 4 - 64) * X ^ 2
    + (-177147 * T ^ 6 - 2268 * T ^ 2) * X + 4374 * T ^ 4 + 64

private theorem sep_bezout_minus :
    sepBezoutA_minus * qminus + sepBezoutB_minus * derivative qminus
      = sepFactorMinus := by
  rw [derivative_qminus]
  unfold sepBezoutA_minus sepBezoutB_minus qminus qminusDeriv sepFactorMinus
  ring

private theorem toFF_ne_zero {p : Polynomial ℚ} (hp : p ≠ 0) : toFF p ≠ 0 := by
  -- `algebraMap : ℚ[t] → ℚ(t)` is injective (localization of a domain).
  simpa [toFF, map_zero] using
    (IsFractionRing.injective (Polynomial ℚ) (RatFunc ℚ)).ne (f := algebraMap _ _) hp

/-- `q₊` is separable over `ℚ(t)`, hence has distinct roots in a splitting field. -/
public theorem separable_qplusFF : qplusFF.Separable := by
  rw [separable_def]
  set D : RatFunc ℚ := toFF sepFactorPlus_coeff
  have hD0 : D ≠ 0 := toFF_ne_zero sepFactorPlus_coeff_ne_zero
  -- Transport the polynomial Bézout identity along `map toFF`.
  have hmap :
      (sepBezoutA_plus.map toFF) * qplusFF
        + (sepBezoutB_plus.map toFF) * derivative qplusFF
        = C D := by
    have h := congrArg (map toFF) sep_bezout_plus
    -- Rewrite the RHS via `sepFactorPlus = C sepFactorPlus_coeff`.
    rw [sepFactorPlus_eq_C] at h
    simpa [qplusFF, D, map_add, map_mul, derivative_map, map_C] using h
  refine ⟨C D⁻¹ * sepBezoutA_plus.map toFF, C D⁻¹ * sepBezoutB_plus.map toFF, ?_⟩
  calc
    (C D⁻¹ * sepBezoutA_plus.map toFF) * qplusFF
        + (C D⁻¹ * sepBezoutB_plus.map toFF) * derivative qplusFF
        = C D⁻¹ * ((sepBezoutA_plus.map toFF) * qplusFF
            + (sepBezoutB_plus.map toFF) * derivative qplusFF) := by ring
    _ = C D⁻¹ * C D := by rw [hmap]
    _ = C (D⁻¹ * D) := by simp [map_mul]
    _ = C 1 := by simp [hD0]
    _ = 1 := by simp

/-- `q₋` is separable over `ℚ(t)`. -/
public theorem separable_qminusFF : qminusFF.Separable := by
  rw [separable_def]
  set D : RatFunc ℚ := toFF sepFactorMinus_coeff
  have hD0 : D ≠ 0 := toFF_ne_zero sepFactorMinus_coeff_ne_zero
  have hmap :
      (sepBezoutA_minus.map toFF) * qminusFF
        + (sepBezoutB_minus.map toFF) * derivative qminusFF
        = C D := by
    have h := congrArg (map toFF) sep_bezout_minus
    rw [sepFactorMinus_eq_C] at h
    simpa [qminusFF, D, map_add, map_mul, derivative_map, map_C] using h
  refine ⟨C D⁻¹ * sepBezoutA_minus.map toFF, C D⁻¹ * sepBezoutB_minus.map toFF, ?_⟩
  calc
    (C D⁻¹ * sepBezoutA_minus.map toFF) * qminusFF
        + (C D⁻¹ * sepBezoutB_minus.map toFF) * derivative qminusFF
        = C D⁻¹ * ((sepBezoutA_minus.map toFF) * qminusFF
            + (sepBezoutB_minus.map toFF) * derivative qminusFF) := by ring
    _ = C D⁻¹ * C D := by rw [hmap]
    _ = C (D⁻¹ * D) := by simp [map_mul]
    _ = C 1 := by simp [hD0]
    _ = 1 := by simp

/-- Squarefreeness of `q₊` over `ℚ(t)`. -/
public theorem squarefree_qplusFF : Squarefree qplusFF :=
  separable_qplusFF.squarefree

/-- Squarefreeness of `q₋` over `ℚ(t)`. -/
public theorem squarefree_qminusFF : Squarefree qminusFF :=
  separable_qminusFF.squarefree

/-- Coprimality of `q₊` and `q₋` over `ℚ(t)` (transport of the integral Bézout identity). -/
public theorem isCoprime_qplusFF_qminusFF : IsCoprime qplusFF qminusFF := by
  obtain ⟨A, B, h⟩ := isCoprime_qplus_qminus
  refine ⟨A.map toFF, B.map toFF, ?_⟩
  have h' := congrArg (map toFF) h
  simpa [qplusFF, qminusFF, map_add, map_mul, map_one] using h'

end ExplicitUnirational.Cert.QuarticDiscriminants

#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.res_qplus_qminus
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.isCoprime_qplus_qminus
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.disc_qplus_eq
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.disc_qminus_eq
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.disc_qplus_ne_zero
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.disc_qminus_ne_zero
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.separable_qplusFF
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.separable_qminusFF
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.squarefree_qplusFF
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.squarefree_qminusFF
#print axioms ExplicitUnirational.Cert.QuarticDiscriminants.isCoprime_qplusFF_qminusFF
