/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.Cert.Rabin
public import Mathlib.Tactic.ComputeDegree
public import Mathlib.Tactic.LinearCombination

/-!
# Irreducibility of the sextic over `F₅` (explicit Rabin/Bézout certificate)

The reduction `q₈ mod 5 = 2 (z+2)^2 d₆(z)` and the sextic factor `d₆` are computed here
(not in [CLOP]). The six simple roots of `d₆` form one closed point of degree 6 on the
base, giving the six nodal members of `[CLOP Lemma 4.1]`.

The Frobenius ladder is generated by exact arithmetic in `F_q[X]/(f)` and re-checked
here: each rung is `r_k ^ q = f * s_k + r_(k+1)`, closed by rewriting the `q`-th power
as `X ↦ X ^ q` (`Rabin.pow_card_eq_expand`) and then a `linear_combination` against the
characteristic. Coprimality is certified by an explicit Bézout pair.
-/

noncomputable section

open Polynomial

namespace ExplicitUnirational.Cert

section SexticF5

private instance : Fact (Nat.Prime 5) := ⟨by decide⟩

private lemma hq : (5 : (ZMod 5)[X]) = 0 := by
  simpa using CharP.cast_eq_zero ((ZMod 5)[X]) 5

private lemma card_zmod : Nat.card (ZMod 5) = 5 := Nat.card_zmod 5

/-- `d₆ = X^6 - X^4 + X^3 - X - 1`, the degree-6 factor of `q₈` mod 5. -/
public def d6 : (ZMod 5)[X] := X ^ 6 + 4 * X ^ 4 + X ^ 3 + 4 * X + 4

public lemma d6_monic : d6.Monic := by
  unfold d6; monicity!

public lemma d6_natDegree : d6.natDegree = 6 := by
  unfold d6; compute_degree!

private def s0 : (ZMod 5)[X] := 0
private def s1 : (ZMod 5)[X] := X ^ 19 + X ^ 17 + 4 * X ^ 16 + X ^ 15 + 4 * X ^ 14 + 3 * X ^ 13 + 4 * X ^ 12 + 4 * X ^ 11 + X ^ 10 + 4 * X ^ 8 + X ^ 7 + 2 * X ^ 6 + 2 * X ^ 5 + 2 * X ^ 4 + 4 * X ^ 3
private def s2 : (ZMod 5)[X] := 4 * X ^ 19 + 4 * X ^ 17 + X ^ 16 + 4 * X ^ 15 + 2 * X ^ 14 + 2 * X ^ 13 + 2 * X ^ 12 + 3 * X ^ 9 + 4 * X ^ 8 + 2 * X ^ 7 + 3 * X ^ 6 + 3 * X ^ 5 + 4 * X ^ 4 + 2 * X ^ 3 + 2 * X ^ 2 + 3 * X + 1
private def s3 : (ZMod 5)[X] := 3 * X ^ 19 + 3 * X ^ 17 + 2 * X ^ 16 + 3 * X ^ 15 + X ^ 14 + 4 * X ^ 13 + X ^ 12 + 3 * X ^ 11 + 2 * X ^ 10 + 4 * X ^ 9 + 4 * X ^ 8 + 2 * X ^ 7 + 4 * X ^ 6 + 3 * X ^ 5 + 3 * X ^ 4 + 2 * X ^ 3 + X ^ 2 + 1
private def s4 : (ZMod 5)[X] := 4 * X ^ 19 + 4 * X ^ 17 + X ^ 16 + 4 * X ^ 15 + 2 * X ^ 14 + 2 * X ^ 13 + 2 * X ^ 12 + X ^ 9 + 4 * X ^ 8 + X ^ 5 + 2 * X ^ 4 + X ^ 3 + 4 * X
private def s5 : (ZMod 5)[X] := 3 * X ^ 19 + 3 * X ^ 17 + 2 * X ^ 16 + 3 * X ^ 15 + X ^ 14 + 4 * X ^ 13 + X ^ 12 + 3 * X ^ 11 + 2 * X ^ 10 + 2 * X ^ 9 + 4 * X ^ 8 + X ^ 6 + X ^ 5 + 4 * X ^ 4 + X ^ 3 + 2 * X ^ 2 + 3 * X + 3

private lemma step0 : (X : (ZMod 5)[X]) ^ 5
    = d6 * s0 + (X ^ 5) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [expand_X]
  unfold d6 s0
  linear_combination (0) * hq

private lemma step1 : (X ^ 5 : (ZMod 5)[X]) ^ 5
    = d6 * s1 + (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_pow, expand_X]
  unfold d6 s1
  linear_combination (-X ^ 23 - X ^ 22 - X ^ 21 - 5 * X ^ 20 - 3 * X ^ 19 - 5 * X ^ 18 - 8 * X ^ 17 - 8 * X ^ 16 - 8 * X ^ 15 - 8 * X ^ 14 - 6 * X ^ 13 - 10 * X ^ 12 - 6 * X ^ 11 - 3 * X ^ 10 - 6 * X ^ 9 - 6 * X ^ 8 - 6 * X ^ 7 - 4 * X ^ 6 - 4 * X ^ 5 - 5 * X ^ 4 - 4 * X ^ 3) * hq

private lemma step2 : (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3 : (ZMod 5)[X]) ^ 5
    = d6 * s2 + (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 4 * X + 1) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold d6 s2
  linear_combination (-4 * X ^ 23 - X ^ 22 - 4 * X ^ 21 - 5 * X ^ 20 - 7 * X ^ 19 - 6 * X ^ 18 - 6 * X ^ 17 - 6 * X ^ 16 - 5 * X ^ 15 - 4 * X ^ 14 - 6 * X ^ 13 - 6 * X ^ 12 - 3 * X ^ 11 - 6 * X ^ 10 - 9 * X ^ 9 - 9 * X ^ 8 - 7 * X ^ 7 - 7 * X ^ 6 - 9 * X ^ 5 - 7 * X ^ 4 - 4 * X ^ 3 - 4 * X ^ 2 - 4 * X - 1) * hq

private lemma step3 : (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 4 * X + 1 : (ZMod 5)[X]) ^ 5
    = d6 * s3 + (4 * X ^ 5 + X ^ 4 + 2 * X ^ 3 + X ^ 2 + X + 2) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat, map_one]
  unfold d6 s3
  linear_combination (-3 * X ^ 23 - X ^ 22 - 3 * X ^ 21 - 4 * X ^ 20 - 6 * X ^ 19 - 4 * X ^ 18 - 8 * X ^ 17 - 6 * X ^ 16 - 6 * X ^ 15 - 7 * X ^ 14 - 8 * X ^ 13 - 8 * X ^ 12 - 7 * X ^ 11 - 9 * X ^ 10 - 10 * X ^ 9 - 8 * X ^ 8 - 7 * X ^ 7 - 7 * X ^ 6 - 5 * X ^ 5 - 5 * X ^ 4 - 3 * X ^ 3 - X ^ 2 - X - 1) * hq

private lemma step4 : (4 * X ^ 5 + X ^ 4 + 2 * X ^ 3 + X ^ 2 + X + 2 : (ZMod 5)[X]) ^ 5
    = d6 * s4 + (3 * X ^ 5 + 4 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 2) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold d6 s4
  linear_combination (-4 * X ^ 23 - X ^ 22 - 4 * X ^ 21 - 5 * X ^ 20 - 7 * X ^ 19 - 6 * X ^ 18 - 6 * X ^ 17 - 6 * X ^ 16 - 5 * X ^ 15 - 4 * X ^ 14 - 4 * X ^ 13 - 5 * X ^ 12 - X ^ 11 - X ^ 10 - 5 * X ^ 9 - 5 * X ^ 8 - 2 * X ^ 7 - X ^ 6 - 6 * X ^ 5 - 4 * X ^ 4 - X ^ 3 - 4 * X ^ 2 - 4 * X) * hq

private lemma step5 : (3 * X ^ 5 + 4 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 2 : (ZMod 5)[X]) ^ 5
    = d6 * s5 + (X) := by
  rw [Rabin.pow_card_eq_expand]
  simp only [map_add, map_mul, map_pow, expand_X, map_ofNat]
  unfold d6 s5
  linear_combination (-3 * X ^ 23 - X ^ 22 - 3 * X ^ 21 - 4 * X ^ 20 - 6 * X ^ 19 - 4 * X ^ 18 - 8 * X ^ 17 - 6 * X ^ 16 - 6 * X ^ 15 - 7 * X ^ 14 - 6 * X ^ 13 - 7 * X ^ 12 - 5 * X ^ 11 - 4 * X ^ 10 - 6 * X ^ 9 - 7 * X ^ 8 - 3 * X ^ 7 - 4 * X ^ 6 - 6 * X ^ 5 - 7 * X ^ 4 - 3 * X ^ 3 - 4 * X ^ 2 - 5 * X - 2) * hq

/-- Rung 0 of the ladder: `X ^ (q ^ 0) = X`. -/
private lemma rung0 : d6 ∣ X ^ (Nat.card (ZMod 5) ^ 0) - X := by simp

private lemma rung1 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 1) - (X ^ 5) := by
  refine Rabin.dvd_sub_step (s := s0) rung0 ?_
  rw [card_zmod]; exact step0

private lemma rung2 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 2) - (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3) := by
  refine Rabin.dvd_sub_step (s := s1) rung1 ?_
  rw [card_zmod]; exact step1

private lemma rung3 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 3) - (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 4 * X + 1) := by
  refine Rabin.dvd_sub_step (s := s2) rung2 ?_
  rw [card_zmod]; exact step2

private lemma rung4 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 4) - (4 * X ^ 5 + X ^ 4 + 2 * X ^ 3 + X ^ 2 + X + 2) := by
  refine Rabin.dvd_sub_step (s := s3) rung3 ?_
  rw [card_zmod]; exact step3

private lemma rung5 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 5) - (3 * X ^ 5 + 4 * X ^ 4 + X ^ 3 + 4 * X ^ 2 + 4 * X + 2) := by
  refine Rabin.dvd_sub_step (s := s4) rung4 ?_
  rw [card_zmod]; exact step4

private lemma rung6 :
    d6 ∣ X ^ (Nat.card (ZMod 5) ^ 6) - (X) := by
  refine Rabin.dvd_sub_step (s := s5) rung5 ?_
  rw [card_zmod]; exact step5

private lemma ladder : d6 ∣ X ^ (Nat.card (ZMod 5) ^ 6) - X := rung6

/-- Bézout certificate for the prime `2 ∣ 6`: `gcd(f, X^(q^3) - X) = 1`. -/
private lemma bezout2 : IsCoprime d6 (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 3 * X + 1) :=
  ⟨3 * X ^ 4 + X ^ 3 + X ^ 2 + X + 4, 4 * X ^ 5 + X ^ 4 + 2 * X ^ 3 + 2 * X ^ 2, by
    unfold d6
    linear_combination (3 * X ^ 10 + 4 * X ^ 9 + 7 * X ^ 8 + 5 * X ^ 7 + 7 * X ^ 6 + 6 * X ^ 5 + 8 * X ^ 4 + 4 * X ^ 3 + 2 * X ^ 2 + 4 * X + 3) * hq⟩

private lemma coprime2 : IsCoprime d6 (X ^ (Nat.card (ZMod 5) ^ 3) - X) := by
  refine Rabin.isCoprime_of_reduction (r := (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 3 * X + 1 : (ZMod 5)[X])) ?_ bezout2
  have e : ((X : (ZMod 5)[X]) ^ (Nat.card (ZMod 5) ^ 3) - X) - (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 3 * X + 1)
      = X ^ (Nat.card (ZMod 5) ^ 3) - (3 * X ^ 5 + 4 * X ^ 4 + 3 * X ^ 3 + 4 * X + 1) := by
    linear_combination (0) * hq
  rw [e]
  exact rung3

/-- Bézout certificate for the prime `3 ∣ 6`: `gcd(f, X^(q^2) - X) = 1`. -/
private lemma bezout3 : IsCoprime d6 (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3 + 4 * X) :=
  ⟨2 * X ^ 4 + 4 * X ^ 3 + X + 4, 2 * X ^ 5 + X ^ 4 + 2 * X ^ 3 + 4 * X, by
    unfold d6
    linear_combination (2 * X ^ 10 + 2 * X ^ 9 + 5 * X ^ 8 + 5 * X ^ 7 + 8 * X ^ 6 + 4 * X ^ 5 + 13 * X ^ 4 + 4 * X ^ 3 + 4 * X ^ 2 + 4 * X + 3) * hq⟩

private lemma coprime3 : IsCoprime d6 (X ^ (Nat.card (ZMod 5) ^ 2) - X) := by
  refine Rabin.isCoprime_of_reduction (r := (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3 + 4 * X : (ZMod 5)[X])) ?_ bezout3
  have e : ((X : (ZMod 5)[X]) ^ (Nat.card (ZMod 5) ^ 2) - X) - (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3 + 4 * X)
      = X ^ (Nat.card (ZMod 5) ^ 2) - (4 * X ^ 5 + X ^ 4 + 4 * X ^ 3) := by
    linear_combination (-X) * hq
  rw [e]
  exact rung2

/-- `d₆` is irreducible over `F₅`. -/
public theorem irreducible_d6 : Irreducible d6 := by
  refine Rabin.irreducible_of_rabin d6_monic ?_ ?_ ?_
  · rw [d6_natDegree]; norm_num
  · rw [d6_natDegree]; exact ladder
  · intro l hl hdvd
    rw [d6_natDegree] at hdvd ⊢
    have hle : l ≤ 6 := Nat.le_of_dvd (by norm_num) hdvd
    have hge : 2 ≤ l := hl.two_le
    interval_cases l
    · exact coprime2
    · exact coprime3
    · exact absurd hdvd (by decide)
    · exact absurd hdvd (by decide)
    · exact absurd hl (by decide)

end SexticF5

end ExplicitUnirational.Cert
