/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.FunctionField.Unirationality
import all ExplicitUnirational.FunctionField.TangentResidual
import all ExplicitUnirational.FunctionField.PencilRationality
public import Mathlib.RingTheory.AlgebraicIndependent.Defs
public import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
public import Mathlib.RingTheory.Polynomial.UniqueFactorization
public import Mathlib.FieldTheory.RatFunc.Basic

/-!
# Dominance of the unirational parametrization

`FunctionField/Unirationality.lean` builds a `ℚ`-algebra homomorphism
`surfaceCoordRingToPlane` from the affine coordinate ring

    ℚ[ξ, η, z] / (4η² − 4ξ³ − 4z²(3−z)ξ − z·P(z))

of the note's Weierstrass model (3.7) into the plane function field
`ℚ(x, y) = Frac ℚ[x, y]`, sending

    z ↦ ζ = −f₀aff/f₁aff,    ξ ↦ Θ/H²,    η ↦ J/(2H³).

This module proves that homomorphism is **injective** — the field embedding
`K(S) ↪ ℚ(x, y)`, equivalently dominance of the rational map `𝔸² ⤏ S`.

## Contents

* `transcendental_planeZeta` — the pencil parameter `ζ` is transcendental over `ℚ`
  (`ℚ[x, y]` is integrally closed, and `f₁aff ∤ f₀aff`).
* `algebraicIndependent_planeZeta_xiPlane` — `{ζ, ξ}` is algebraically independent
  over `ℚ`.  The fibre `ζ = 0` of the pencil is the cuspidal cubic `y = x³`, which is
  rational (`t ↦ (t, t³)`); on its generic point `Θ ↦ 1` and `H ↦ 3t`, so `ξ ↦ 1/(9t²)`,
  transcendental over `ℚ`, while `ζ ↦ 0`.  A relation `P(ζ, ξ) = 0` therefore forces
  `z ∣ P`, and dividing by `ζ ≠ 0` and inducting gives `P = 0`.
* `surfaceToPlane_eq_zero_iff` — the kernel of the evaluation is exactly the ideal
  generated by the surface polynomial.
* `surfaceCoordRingToPlane_injective`, `surfaceFunctionFieldToPlane_injective` — the
  two forms of the conclusion.

The denominator bookkeeping is done once and for all by `exists_clear`, an induction
over `MvPolynomial (Fin 3) ℚ`; no explicit `z`-expansion of the covariants `Θ`
(119 terms, `z`-degree 8) or `H` is ever needed.

## What is *not* proved here

* Nothing about the **degree** of the map: the note's `deg α_λ = 9` is not used and
  not reproved.  Only nonconstancy (dominance) is established.
* Nothing about the **weighted hypersurface** `S_Q ⊂ P(1,1,2,3)` of
  `DelPezzo/Surface.lean`.  Identifying `K(S)` with the function field of `S_Q` is a
  separate birationality statement between the two models, and it is *not* formalized.
  The statements here are about the affine Weierstrass model (3.7) only.
* No scheme-theoretic notion of unirationality, and no statement over any base field
  other than `ℚ`.
-/

@[expose] public section

noncomputable section

open MvPolynomial

namespace ExplicitUnirational

local notation "ι₂" => algebraMap (MvPolynomial (Fin 2) ℚ) (FunctionField.planeField ℚ)

instance : IsScalarTower ℚ (MvPolynomial (Fin 2) ℚ) (FunctionField.planeField ℚ) :=
  FunctionField.isScalarTower_planeField

/-! ## Step 1: the pencil parameter is transcendental over `ℚ` -/

public theorem planeZeta_mul_f₁aff : planeZeta * ι₂ f₁aff = ι₂ (-f₀aff) := by
  have h : ι₂ f₁aff ≠ 0 := by
    rw [Ne, IsFractionRing.to_map_eq_zero_iff]; exact f₁aff_ne_zero
  show FunctionField.pencilParameter f₀aff f₁aff * _ = _
  unfold FunctionField.pencilParameter
  rw [div_mul_cancel₀ _ h, map_neg]

/-- The pencil parameter `ζ = −f₀/f₁` is transcendental over `ℚ`. -/
public theorem transcendental_planeZeta : Transcendental ℚ planeZeta := by
  intro halg
  -- `ζ` is integral over `ℚ`, hence over `ℚ[x, y]`
  have hintQ : IsIntegral ℚ planeZeta := halg.isIntegral
  have hint : IsIntegral (MvPolynomial (Fin 2) ℚ) planeZeta := hintQ.tower_top
  -- `ℚ[x, y]` is a UFD, hence integrally closed in its fraction field
  obtain ⟨a, ha⟩ := IsIntegrallyClosed.isIntegral_iff.mp hint
  have h1 : ι₂ (a * f₁aff) = ι₂ (-f₀aff) := by
    rw [map_mul, ha]; exact planeZeta_mul_f₁aff
  have h2 : a * f₁aff = -f₀aff :=
    IsFractionRing.injective (MvPolynomial (Fin 2) ℚ) (FunctionField.planeField ℚ) h1
  -- evaluate at `(x, y) = (1, 0)`, where `f₁ = 0` but `-f₀ = 1`
  have h3 := congrArg (eval ![(1 : ℚ), 0]) h2
  simp [f₀aff, f₁aff] at h3

public theorem planeZeta_ne_zero : planeZeta ≠ 0 := by
  intro h
  have h1 : ι₂ (-f₀aff) = 0 := by rw [← planeZeta_mul_f₁aff, h, zero_mul]
  rw [IsFractionRing.to_map_eq_zero_iff] at h1
  have h2 := congrArg (eval ![(0 : ℚ), 1]) h1
  simp [f₀aff] at h2

/-! ## Step 2: the residue along the cuspidal fibre `ζ = 0`

The fibre `ζ = 0` of the pencil is the cuspidal cubic `y = x³`, which is rational:
it is parametrized by `t ↦ (t, t³)`.  Restricting a plane rational function to that
fibre is the "residue" used below; on the generic point of the fibre one has
`ζ ↦ 0` and `ξ = Θ/H² ↦ 1/(9t²)`, and the latter is transcendental over `ℚ`. -/

/-- Restriction of plane polynomials to the cuspidal fibre: `x ↦ t`, `y ↦ t³`. -/
public def rhoCurve : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] Polynomial ℚ :=
  aeval ![Polynomial.X, Polynomial.X ^ 3]

/-- Evaluation of ambient polynomials at the generic point of the fibre `ζ = 0`:
`(x, y, z) ↦ (t, t³, 0)`. -/
public def curveEval : MvPolynomial (Fin 3) ℚ →ₐ[ℚ] Polynomial ℚ :=
  aeval ![Polynomial.X, Polynomial.X ^ 3, 0]

@[simp] public theorem rhoCurve_X0 : rhoCurve (X 0) = Polynomial.X := by simp [rhoCurve]
@[simp] public theorem rhoCurve_X1 : rhoCurve (X 1) = Polynomial.X ^ 3 := by simp [rhoCurve]
@[simp] public theorem curveEval_X0 : curveEval (X 0) = Polynomial.X := by simp [curveEval]
@[simp] public theorem curveEval_X1 : curveEval (X 1) = Polynomial.X ^ 3 := by simp [curveEval]
@[simp] public theorem curveEval_X2 : curveEval (X 2) = 0 := by simp [curveEval]

public theorem rhoCurve_f₀aff : rhoCurve f₀aff = 0 := by
  simp [f₀aff]

public theorem rhoCurve_f₁aff :
    rhoCurve f₁aff = Polynomial.X ^ 9 + Polynomial.X ^ 6 + Polynomial.X - 1 := by
  simp [f₁aff]; ring

public theorem rhoCurve_f₁aff_ne_zero : rhoCurve f₁aff ≠ 0 := by
  intro h
  have h0 : Polynomial.eval 0 (rhoCurve f₁aff) = 0 := by rw [h]; simp
  rw [rhoCurve_f₁aff] at h0
  simp at h0

/-- The Hessian covariant restricted to the fibre `ζ = 0`: `H(t, t³, 0) = 3t`. -/
public theorem curveEval_hessAff : curveEval hessAff = 3 * Polynomial.X := by
  simp [hessAff, map_ofNat]

/-- The covariant `Θ` restricted to the fibre `ζ = 0`: `Θ(t, t³, 0) = 1`. -/
public theorem curveEval_thetaAff : curveEval thetaAff = 1 := by
  simp [thetaAff, map_ofNat]

/-! ### Clearing denominators along `z ↦ ζ`

Every value `toPlane p` of the substitution `z ↦ ζ = −f₀/f₁` becomes a *polynomial*
after multiplying by a power of `f₁`, and the same power of `rhoCurve f₁aff` relates
the residue of `toPlane p` to `curveEval p`.  This is proved by induction on `p`, so no
explicit `z`-expansion of the covariants is needed. -/

public theorem exists_clear (p : MvPolynomial (Fin 3) ℚ) :
    ∃ (n : ℕ) (r : MvPolynomial (Fin 2) ℚ),
      toPlane p * ι₂ f₁aff ^ n = ι₂ r ∧
      curveEval p * rhoCurve f₁aff ^ n = rhoCurve r := by
  induction p using MvPolynomial.induction_on with
  | C a =>
      refine ⟨0, MvPolynomial.C a, ?_, ?_⟩
      · rw [pow_zero, mul_one, ← MvPolynomial.algebraMap_eq, ← MvPolynomial.algebraMap_eq,
          AlgHom.commutes, ← IsScalarTower.algebraMap_apply]
      · rw [pow_zero, mul_one, ← MvPolynomial.algebraMap_eq, ← MvPolynomial.algebraMap_eq,
          AlgHom.commutes, AlgHom.commutes]
  | add p q hp hq =>
      obtain ⟨n, r, h1, h2⟩ := hp
      obtain ⟨m, s, k1, k2⟩ := hq
      refine ⟨n + m, r * f₁aff ^ m + s * f₁aff ^ n, ?_, ?_⟩
      · rw [map_add, map_add, map_mul, map_mul, map_pow, map_pow, ← h1, ← k1]; ring
      · rw [map_add, map_add, map_mul, map_mul, map_pow, map_pow, ← h2, ← k2]; ring
  | mul_X p i hp =>
      obtain ⟨n, r, h1, h2⟩ := hp
      have hi : i = 0 ∨ i = 1 ∨ i = 2 := by fin_cases i <;> decide
      rcases hi with rfl | rfl | rfl
      · refine ⟨n, r * X 0, ?_, ?_⟩
        · rw [map_mul, map_mul, toPlane_X0, ← h1, planeX]; ring
        · rw [map_mul, map_mul, curveEval_X0, rhoCurve_X0, ← h2]; ring
      · refine ⟨n, r * X 1, ?_, ?_⟩
        · rw [map_mul, map_mul, toPlane_X1, ← h1, planeY]; ring
        · rw [map_mul, map_mul, curveEval_X1, rhoCurve_X1, ← h2]; ring
      · refine ⟨n + 1, r * -f₀aff, ?_, ?_⟩
        · rw [map_mul, map_mul, toPlane_X2, ← h1, ← planeZeta_mul_f₁aff]; ring
        · rw [map_mul, map_mul, curveEval_X2, map_neg, rhoCurve_f₀aff, ← h2]; ring

/-- If a plane rational function built from `x`, `y`, `ζ` vanishes, so does its
restriction to the fibre `ζ = 0`. -/
public theorem curveEval_eq_zero_of_toPlane_eq_zero {p : MvPolynomial (Fin 3) ℚ}
    (h : toPlane p = 0) : curveEval p = 0 := by
  obtain ⟨n, r, h1, h2⟩ := exists_clear p
  rw [h, zero_mul] at h1
  have hr : r = 0 := by
    have h1' := h1.symm
    rwa [IsFractionRing.to_map_eq_zero_iff] at h1'
  rw [hr, map_zero] at h2
  rcases mul_eq_zero.mp h2 with h3 | h3
  · exact h3
  · exact absurd h3 (pow_ne_zero _ rhoCurve_f₁aff_ne_zero)

/-! ### The residue of `ξ` on the fibre

`ξ = Θ/H²` restricts to `1/(9t²)` on the cuspidal fibre, which is transcendental
over `ℚ`. -/

local notation "rc" => algebraMap (Polynomial ℚ) (RatFunc ℚ)

/-- The value of `ξ` at the generic point of the fibre `ζ = 0`, namely `1/(9t²)`. -/
public def residueXi : RatFunc ℚ := (rc ((9 : Polynomial ℚ) * Polynomial.X ^ 2))⁻¹

public theorem nine_X_sq_ne_zero : ((9 : Polynomial ℚ) * Polynomial.X ^ 2) ≠ 0 := by
  intro h
  have := congrArg (Polynomial.coeff · 2) h
  simp at this

public theorem transcendental_residueXi : Transcendental ℚ residueXi := by
  have hinj : Function.Injective (algebraMap (Polynomial ℚ) (RatFunc ℚ)) :=
    IsFractionRing.injective _ _
  have h9 : (9 : ℚ) ≠ 0 := by norm_num
  have h9C : ((9 : Polynomial ℚ) * Polynomial.X ^ 2)
      = Polynomial.C (9 : ℚ) * Polynomial.X ^ 2 := by
    rw [map_ofNat]
  have hpoly : Transcendental ℚ ((9 : Polynomial ℚ) * Polynomial.X ^ 2) := by
    rw [h9C]
    refine Polynomial.transcendental _ ?_ ?_
    · rw [Polynomial.natDegree_C_mul_X_pow 2 (9 : ℚ) h9]; norm_num
    · rw [Polynomial.leadingCoeff_C_mul_X_pow]
      exact mem_nonZeroDivisors_of_ne_zero h9
  have halg : Transcendental ℚ (rc ((9 : Polynomial ℚ) * Polynomial.X ^ 2)) :=
    (transcendental_algebraMap_iff (A := RatFunc ℚ) hinj).mpr hpoly
  intro hcon
  unfold residueXi at hcon
  rw [IsAlgebraic.inv_iff] at hcon
  exact halg hcon

/-- `ξ` is the quotient of two plane polynomials whose residues on the cuspidal fibre
are nonzero, with quotient `1/(9t²)`. -/
public theorem exists_xi_rep :
    ∃ a b : MvPolynomial (Fin 2) ℚ,
      xiPlane * ι₂ b = ι₂ a ∧ rhoCurve a ≠ 0 ∧
        rhoCurve b = (9 : Polynomial ℚ) * Polynomial.X ^ 2 * rhoCurve a := by
  obtain ⟨nT, rT, hT1, hT2⟩ := exists_clear thetaAff
  obtain ⟨nH, rH, hH1, hH2⟩ := exists_clear hessAff
  rw [curveEval_thetaAff, one_mul] at hT2
  rw [curveEval_hessAff] at hH2
  have hHne : toPlane hessAff ≠ 0 := toPlane_hessAff_ne_zero
  refine ⟨rT * f₁aff ^ (nH * 2), f₁aff ^ nT * rH ^ 2, ?_, ?_, ?_⟩
  · rw [map_mul, map_mul, map_pow, map_pow, map_pow, ← hH1, ← hT1]
    unfold xiPlane
    field_simp
    ring
  · rw [map_mul, map_pow, ← hT2]
    exact mul_ne_zero (pow_ne_zero _ rhoCurve_f₁aff_ne_zero)
      (pow_ne_zero _ rhoCurve_f₁aff_ne_zero)
  · rw [map_mul, map_mul, map_pow, map_pow, map_pow, ← hT2, ← hH2]
    ring

/-! ### Clearing denominators for a two-variable relation -/

public theorem exists_clear_pair (a b : MvPolynomial (Fin 2) ℚ)
    (hab : xiPlane * ι₂ b = ι₂ a)
    (hres : residueXi * rc (rhoCurve b) = rc (rhoCurve a))
    (P : MvPolynomial (Fin 2) ℚ) :
    ∃ (n m : ℕ) (r : MvPolynomial (Fin 2) ℚ),
      aeval ![planeZeta, xiPlane] P * ι₂ f₁aff ^ n * ι₂ b ^ m = ι₂ r ∧
      aeval ![(0 : RatFunc ℚ), residueXi] P * rc (rhoCurve f₁aff) ^ n * rc (rhoCurve b) ^ m
        = rc (rhoCurve r) := by
  induction P using MvPolynomial.induction_on with
  | C c =>
      refine ⟨0, 0, MvPolynomial.C c, ?_, ?_⟩
      · rw [pow_zero, pow_zero, mul_one, mul_one, ← MvPolynomial.algebraMap_eq,
          AlgHom.commutes, ← IsScalarTower.algebraMap_apply]
      · rw [pow_zero, pow_zero, mul_one, mul_one, ← MvPolynomial.algebraMap_eq,
          AlgHom.commutes, AlgHom.commutes, ← IsScalarTower.algebraMap_apply]
  | add p q hp hq =>
      obtain ⟨n, m, r, h1, h2⟩ := hp
      obtain ⟨n', m', r', k1, k2⟩ := hq
      refine ⟨n + n', m + m', r * f₁aff ^ n' * b ^ m' + r' * f₁aff ^ n * b ^ m, ?_, ?_⟩
      · simp only [map_add, map_mul, map_pow]
        linear_combination (ι₂ f₁aff ^ n' * ι₂ b ^ m') * h1 + (ι₂ f₁aff ^ n * ι₂ b ^ m) * k1
      · simp only [map_add, map_mul, map_pow]
        linear_combination (rc (rhoCurve f₁aff) ^ n' * rc (rhoCurve b) ^ m') * h2
          + (rc (rhoCurve f₁aff) ^ n * rc (rhoCurve b) ^ m) * k2
  | mul_X p i hp =>
      obtain ⟨n, m, r, h1, h2⟩ := hp
      have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
      rcases hi with rfl | rfl
      · refine ⟨n + 1, m, r * -f₀aff, ?_, ?_⟩
        · simp only [map_mul, aeval_X, Matrix.cons_val_zero]
          rw [← h1, ← planeZeta_mul_f₁aff]; ring
        · simp only [map_mul, aeval_X, Matrix.cons_val_zero, map_neg, rhoCurve_f₀aff]
          simp
      · refine ⟨n, m + 1, r * a, ?_, ?_⟩
        · simp only [map_mul, aeval_X, Matrix.cons_val_one, Matrix.cons_val_zero]
          rw [← h1, ← hab]; ring
        · simp only [map_mul, aeval_X, Matrix.cons_val_one, Matrix.cons_val_zero]
          rw [← h2, ← hres]; ring

public theorem residue_eq_zero {a b : MvPolynomial (Fin 2) ℚ}
    (hab : xiPlane * ι₂ b = ι₂ a)
    (hres : residueXi * rc (rhoCurve b) = rc (rhoCurve a))
    (hb : rhoCurve b ≠ 0)
    {P : MvPolynomial (Fin 2) ℚ} (h : aeval ![planeZeta, xiPlane] P = 0) :
    aeval ![(0 : RatFunc ℚ), residueXi] P = 0 := by
  have hinj : Function.Injective (algebraMap (Polynomial ℚ) (RatFunc ℚ)) :=
    IsFractionRing.injective _ _
  obtain ⟨n, m, r, h1, h2⟩ := exists_clear_pair a b hab hres P
  rw [h, zero_mul, zero_mul] at h1
  have hr : r = 0 := by
    have h1' := h1.symm
    rwa [IsFractionRing.to_map_eq_zero_iff] at h1'
  rw [hr, map_zero, map_zero] at h2
  have hF : rc (rhoCurve f₁aff) ≠ 0 := fun hc => rhoCurve_f₁aff_ne_zero (hinj (by simpa using hc))
  have hB : rc (rhoCurve b) ≠ 0 := fun hc => hb (hinj (by simpa using hc))
  rcases mul_eq_zero.mp h2 with h3 | h3
  · rcases mul_eq_zero.mp h3 with h4 | h4
    · exact h4
    · exact absurd h4 (pow_ne_zero _ hF)
  · exact absurd h3 (pow_ne_zero _ hB)

/-! ### From the residue relation to divisibility by `X 0` -/

/-- Setting the first variable to zero. -/
public def projX0 : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] Polynomial ℚ :=
  aeval ![0, Polynomial.X]

public theorem aeval_residue_eq (P : MvPolynomial (Fin 2) ℚ) :
    aeval ![(0 : RatFunc ℚ), residueXi] P = Polynomial.aeval residueXi (projX0 P) := by
  have hcomp : (Polynomial.aeval (R := ℚ) residueXi).comp projX0
      = aeval ![(0 : RatFunc ℚ), residueXi] := by
    apply MvPolynomial.algHom_ext
    intro i
    have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
    rcases hi with rfl | rfl <;> simp [projX0]
  rw [← hcomp]; rfl

public theorem X0_dvd_sub_emb (P : MvPolynomial (Fin 2) ℚ) :
    (X 0 : MvPolynomial (Fin 2) ℚ) ∣
      P - Polynomial.aeval (X 1 : MvPolynomial (Fin 2) ℚ) (projX0 P) := by
  induction P using MvPolynomial.induction_on with
  | C c => simp [projX0]
  | add p q hp hq =>
      obtain ⟨c, hc⟩ := hp
      obtain ⟨d, hd⟩ := hq
      refine ⟨c + d, ?_⟩
      rw [map_add, map_add]
      linear_combination hc + hd
  | mul_X p i hp =>
      have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
      rcases hi with rfl | rfl
      · refine ⟨p, ?_⟩
        have hz : projX0 (p * X 0) = 0 := by simp [projX0]
        rw [hz, map_zero, sub_zero]; ring
      · obtain ⟨c, hc⟩ := hp
        refine ⟨c * X 1, ?_⟩
        have hz : projX0 (p * X 1) = projX0 p * Polynomial.X := by simp [projX0]
        rw [hz, map_mul, Polynomial.aeval_X, ← sub_mul, hc]; ring

public theorem X0_dvd_of_residue {P : MvPolynomial (Fin 2) ℚ}
    (h : aeval ![(0 : RatFunc ℚ), residueXi] P = 0) : (X 0 : MvPolynomial (Fin 2) ℚ) ∣ P := by
  rw [aeval_residue_eq] at h
  have hp0 : projX0 P = 0 := by
    by_contra hc
    exact transcendental_residueXi ⟨projX0 P, hc, h⟩
  have hd := X0_dvd_sub_emb P
  rw [hp0, map_zero, sub_zero] at hd
  exact hd

/-! ## Step 3: algebraic independence of the pencil parameter and `ξ` -/

/-- **The two coordinates `ζ` and `ξ` are algebraically independent over `ℚ`.**
Equivalently, the rational map `𝔸² ⤏ 𝔸²`, `(x, y) ↦ (ζ, ξ)`, is dominant. -/
public theorem algebraicIndependent_planeZeta_xiPlane :
    AlgebraicIndependent ℚ ![planeZeta, xiPlane] := by
  obtain ⟨a, b, hab, hane, hres0⟩ := exists_xi_rep
  have hb : rhoCurve b ≠ 0 := by
    rw [hres0]; exact mul_ne_zero nine_X_sq_ne_zero hane
  have h9 : rc ((9 : Polynomial ℚ) * Polynomial.X ^ 2) ≠ 0 := fun hc =>
    nine_X_sq_ne_zero
      (IsFractionRing.injective (Polynomial ℚ) (RatFunc ℚ) (by simpa using hc))
  have hres : residueXi * rc (rhoCurve b) = rc (rhoCurve a) := by
    rw [hres0, map_mul]
    unfold residueXi
    exact inv_mul_cancel_left₀ h9 _
  rw [algebraicIndependent_iff]
  have key : ∀ (n : ℕ) (P : MvPolynomial (Fin 2) ℚ), P.degreeOf 0 ≤ n →
      aeval ![planeZeta, xiPlane] P = 0 → P = 0 := by
    intro n
    induction n with
    | zero =>
        intro P hdeg h
        obtain ⟨Q, hQ⟩ := X0_dvd_of_residue (residue_eq_zero hab hres hb h)
        by_cases hQ0 : Q = 0
        · rw [hQ, hQ0, mul_zero]
        · exfalso
          have hd : P.degreeOf 0 = Q.degreeOf 0 + 1 := by
            rw [hQ, mul_comm]
            exact (degreeOf_mul_X_eq_degreeOf_add_one_iff 0 Q).mpr hQ0
          omega
    | succ n ih =>
        intro P hdeg h
        obtain ⟨Q, hQ⟩ := X0_dvd_of_residue (residue_eq_zero hab hres hb h)
        by_cases hQ0 : Q = 0
        · rw [hQ, hQ0, mul_zero]
        · exfalso
          have hQz : aeval ![planeZeta, xiPlane] Q = 0 := by
            rw [hQ, map_mul] at h
            simp only [aeval_X, Matrix.cons_val_zero] at h
            rcases mul_eq_zero.mp h with h' | h'
            · exact absurd h' planeZeta_ne_zero
            · exact h'
          have hd : P.degreeOf 0 = Q.degreeOf 0 + 1 := by
            rw [hQ, mul_comm]
            exact (degreeOf_mul_X_eq_degreeOf_add_one_iff 0 Q).mpr hQ0
          exact hQ0 (ih Q (by omega) hQz)
  intro P hP
  exact key (P.degreeOf 0) P le_rfl hP

#print axioms transcendental_planeZeta
#print axioms algebraicIndependent_planeZeta_xiPlane

/-! ## Step 4: injectivity of the coordinate-ring homomorphism

`weierstrassSurfaceAff` is quadratic in `η` with unit leading coefficient, so every
ambient polynomial is congruent mod it to one of the form `a(ξ, z)·η + b(ξ, z)`.
Such a class dies in `ℚ(x, y)` only if `a = b = 0`: squaring the relation and using
the Weierstrass equation turns it into a *polynomial* identity in `ℚ[ξ, z]`, which
`{ζ, ξ}`-independence then transports to `ℚ[ξ, z]` itself, where a degree-parity
argument in `ξ` finishes. -/

/-- The `(ξ, z)`-coordinates inside the ambient `(ξ, η, z)`: `X 0 ↦ X 0`, `X 1 ↦ X 2`. -/
public def injXiZ : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] MvPolynomial (Fin 3) ℚ :=
  aeval ![X 0, X 2]

@[simp] public theorem injXiZ_X0 : injXiZ (X 0) = X 0 := by simp [injXiZ]
@[simp] public theorem injXiZ_X1 : injXiZ (X 1) = X 2 := by simp [injXiZ]

/-- The `η`-free part of the affine Weierstrass surface polynomial, in the
coordinates `X 0 = ξ`, `X 1 = z`. -/
public def surfaceTail : MvPolynomial (Fin 2) ℚ :=
  -(4 * (X 0) ^ 3) - 4 * ((X 1) ^ 2 * (3 - X 1)) * (X 0)
    - (X 1) * (4 * (X 1) ^ 4 - 23 * (X 1) ^ 3 - 18 * (X 1) ^ 2 + (X 1) - 4)

public theorem weierstrassSurfaceAff_eq_add :
    weierstrassSurfaceAff = 4 * (X 1 : MvPolynomial (Fin 3) ℚ) ^ 2 + injXiZ surfaceTail := by
  simp only [weierstrassSurfaceAff, surfaceTail, injXiZ, map_sub, map_neg, map_add, map_mul,
    map_pow, map_ofNat, aeval_X, Matrix.cons_val_zero, Matrix.cons_val_one]
  ring

/-- Division with remainder by the surface polynomial in the variable `η`.
The power of `4` keeps everything integral. -/
public theorem exists_eta_division (p : MvPolynomial (Fin 3) ℚ) :
    ∃ (n : ℕ) (q : MvPolynomial (Fin 3) ℚ) (a b : MvPolynomial (Fin 2) ℚ),
      4 ^ n * p = q * weierstrassSurfaceAff + injXiZ a * X 1 + injXiZ b := by
  induction p using MvPolynomial.induction_on with
  | C c => exact ⟨0, 0, 0, MvPolynomial.C c, by simp⟩
  | add p p' hp hp' =>
      obtain ⟨n, q, a, b, h⟩ := hp
      obtain ⟨m, q', a', b', h'⟩ := hp'
      refine ⟨n + m, 4 ^ m * q + 4 ^ n * q', 4 ^ m * a + 4 ^ n * a', 4 ^ m * b + 4 ^ n * b', ?_⟩
      have e1 : (4 : MvPolynomial (Fin 3) ℚ) ^ (n + m) * (p + p')
          = 4 ^ m * (4 ^ n * p) + 4 ^ n * (4 ^ m * p') := by ring
      rw [e1, h, h']
      simp only [map_add, map_mul, map_pow, map_ofNat]
      ring
  | mul_X p i hp =>
      obtain ⟨n, q, a, b, h⟩ := hp
      have hi : i = 0 ∨ i = 1 ∨ i = 2 := by fin_cases i <;> decide
      rcases hi with rfl | rfl | rfl
      · refine ⟨n, q * X 0, a * X 0, b * X 0, ?_⟩
        have e : (4 : MvPolynomial (Fin 3) ℚ) ^ n * (p * X 0) = (4 ^ n * p) * X 0 := by ring
        rw [e, h]
        simp only [map_mul, injXiZ_X0]
        ring
      · refine ⟨n + 1, 4 * q * X 1 + injXiZ a, 4 * b, -(a * surfaceTail), ?_⟩
        have e : (4 : MvPolynomial (Fin 3) ℚ) ^ (n + 1) * (p * X 1)
            = 4 * (4 ^ n * p) * X 1 := by ring
        rw [e, h]
        simp only [map_mul, map_neg, map_ofNat]
        rw [weierstrassSurfaceAff_eq_add]
        ring
      · refine ⟨n, q * X 2, a * X 1, b * X 1, ?_⟩
        have e : (4 : MvPolynomial (Fin 3) ℚ) ^ n * (p * X 2) = (4 ^ n * p) * X 2 := by ring
        rw [e, h]
        simp only [map_mul, injXiZ_X1]
        ring

/-! ### Independence in the order `(ξ, z)` -/

public theorem injective_aeval_xi_zeta :
    Function.Injective (aeval ![xiPlane, planeZeta] :
      MvPolynomial (Fin 2) ℚ →ₐ[ℚ] FunctionField.planeField ℚ) := by
  have hswap : Function.Injective
      (rename (Equiv.swap (0 : Fin 2) 1) : MvPolynomial (Fin 2) ℚ → MvPolynomial (Fin 2) ℚ) :=
    rename_injective _ (Equiv.injective _)
  have hcomp : ∀ P : MvPolynomial (Fin 2) ℚ,
      aeval ![xiPlane, planeZeta] P
        = aeval ![planeZeta, xiPlane] (rename (Equiv.swap (0 : Fin 2) 1) P) := by
    have hc : (aeval ![planeZeta, xiPlane] : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] _).comp
        (rename (Equiv.swap (0 : Fin 2) 1)) = aeval ![xiPlane, planeZeta] := by
      apply MvPolynomial.algHom_ext
      intro i
      have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
      rcases hi with rfl | rfl <;>
        simp [Equiv.swap_apply_left, Equiv.swap_apply_right]
    intro P
    rw [← hc]; rfl
  intro P Q hPQ
  rw [hcomp, hcomp] at hPQ
  exact hswap (algebraicIndependent_planeZeta_xiPlane hPQ)

public theorem surfaceToPlane_injXiZ (a : MvPolynomial (Fin 2) ℚ) :
    surfaceToPlane (injXiZ a) = aeval ![xiPlane, planeZeta] a := by
  have hc : surfaceToPlane.comp injXiZ = aeval ![xiPlane, planeZeta] := by
    apply MvPolynomial.algHom_ext
    intro i
    have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
    rcases hi with rfl | rfl <;> simp [injXiZ, surfaceToPlane]
  rw [← hc]; rfl

/-- The Weierstrass relation in the form used below. -/
public theorem four_etaPlane_sq :
    4 * etaPlane ^ 2 + aeval ![xiPlane, planeZeta] surfaceTail = 0 := by
  have h := surfaceToPlane_vanishes
  rw [weierstrassSurfaceAff_eq_add, map_add, map_mul, map_pow, map_ofNat,
    surfaceToPlane_injXiZ] at h
  have he : surfaceToPlane (X 1) = etaPlane := by simp [surfaceToPlane]
  rw [he] at h
  exact h

/-! ### Setting `z = 0` in the `(ξ, z)`-plane -/

/-- Setting the second variable (`z`) to zero. -/
public def projX1 : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] Polynomial ℚ :=
  aeval ![Polynomial.X, 0]

public theorem projX1_surfaceTail : projX1 surfaceTail = -(4 * Polynomial.X ^ 3) := by
  simp [projX1, surfaceTail, map_ofNat]

public theorem X1_dvd_sub_emb (P : MvPolynomial (Fin 2) ℚ) :
    (X 1 : MvPolynomial (Fin 2) ℚ) ∣
      P - Polynomial.aeval (X 0 : MvPolynomial (Fin 2) ℚ) (projX1 P) := by
  induction P using MvPolynomial.induction_on with
  | C c => simp [projX1]
  | add p q hp hq =>
      obtain ⟨c, hc⟩ := hp
      obtain ⟨d, hd⟩ := hq
      refine ⟨c + d, ?_⟩
      rw [map_add, map_add]
      linear_combination hc + hd
  | mul_X p i hp =>
      have hi : i = 0 ∨ i = 1 := by fin_cases i <;> decide
      rcases hi with rfl | rfl
      · obtain ⟨c, hc⟩ := hp
        refine ⟨c * X 0, ?_⟩
        have hz : projX1 (p * X 0) = projX1 p * Polynomial.X := by simp [projX1]
        rw [hz, map_mul, Polynomial.aeval_X, ← sub_mul, hc]; ring
      · refine ⟨p, ?_⟩
        have hz : projX1 (p * X 1) = 0 := by simp [projX1]
        rw [hz, map_zero, sub_zero]; ring

public theorem X1_dvd_of_projX1_eq_zero {P : MvPolynomial (Fin 2) ℚ} (h : projX1 P = 0) :
    (X 1 : MvPolynomial (Fin 2) ℚ) ∣ P := by
  have hd := X1_dvd_sub_emb P
  rwa [h, map_zero, sub_zero] at hd

private theorem eq_zero_of_sq_eq_sq_mul_X_cube {P Q : Polynomial ℚ}
    (h : Q ^ 2 = P ^ 2 * Polynomial.X ^ 3) : P = 0 ∧ Q = 0 := by
  by_cases hP : P = 0
  · subst hP
    simp at h
    exact ⟨rfl, h⟩
  · exfalso
    have hR : P ^ 2 * Polynomial.X ^ 3 ≠ 0 :=
      mul_ne_zero (pow_ne_zero _ hP) (pow_ne_zero _ Polynomial.X_ne_zero)
    have hQ : Q ≠ 0 := by
      intro hq; rw [hq, zero_pow (by norm_num)] at h; exact hR h.symm
    have hdeg := congrArg Polynomial.natDegree h
    rw [Polynomial.natDegree_pow, Polynomial.natDegree_mul (pow_ne_zero _ hP)
      (pow_ne_zero _ Polynomial.X_ne_zero), Polynomial.natDegree_pow,
      Polynomial.natDegree_X_pow] at hdeg
    omega

/-- If `a·η + b = 0` in `ℚ(x, y)` with `a, b` polynomials in `(ξ, z)`, then `z` divides
both `a` and `b`. -/
private theorem eta_relation_dvd {a b : MvPolynomial (Fin 2) ℚ}
    (hrel : aeval ![xiPlane, planeZeta] a * etaPlane + aeval ![xiPlane, planeZeta] b = 0) :
    (X 1 : MvPolynomial (Fin 2) ℚ) ∣ a ∧ (X 1 : MvPolynomial (Fin 2) ℚ) ∣ b := by
  set ψ := (aeval ![xiPlane, planeZeta] : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] _) with hψ
  -- squaring the relation and using the Weierstrass equation
  have hpoly : ψ (4 * b ^ 2 + a ^ 2 * surfaceTail) = 0 := by
    have hw := four_etaPlane_sq
    simp only [map_add, map_mul, map_pow, map_ofNat]
    have hb : ψ b = -(ψ a * etaPlane) := by linear_combination hrel
    rw [hb]
    linear_combination (ψ a) ^ 2 * hw
  have hid : 4 * b ^ 2 + a ^ 2 * surfaceTail = 0 := by
    have := injective_aeval_xi_zeta (by rw [hpoly, map_zero] : ψ _ = ψ 0)
    exact this
  -- set `z = 0`
  have hz := congrArg projX1 hid
  rw [map_add, map_mul, map_mul, map_pow, map_pow, map_ofNat, projX1_surfaceTail,
    map_zero] at hz
  have h4 : (4 : Polynomial ℚ) * (projX1 b ^ 2 - projX1 a ^ 2 * Polynomial.X ^ 3) = 0 := by
    linear_combination hz
  have hsq : projX1 b ^ 2 = projX1 a ^ 2 * Polynomial.X ^ 3 :=
    sub_eq_zero.mp (by
      rcases mul_eq_zero.mp h4 with h | h
      · exact absurd h (by norm_num)
      · exact h)
  obtain ⟨ha0, hb0⟩ := eq_zero_of_sq_eq_sq_mul_X_cube hsq
  exact ⟨X1_dvd_of_projX1_eq_zero ha0, X1_dvd_of_projX1_eq_zero hb0⟩

private theorem eta_relation_eq_zero : ∀ (N : ℕ) (a b : MvPolynomial (Fin 2) ℚ),
    a.degreeOf 1 + b.degreeOf 1 ≤ N →
    aeval ![xiPlane, planeZeta] a * etaPlane + aeval ![xiPlane, planeZeta] b = 0 →
    a = 0 ∧ b = 0 := by
  intro N
  induction N with
  | zero =>
      intro a b hdeg hrel
      obtain ⟨⟨a', ha'⟩, ⟨b', hb'⟩⟩ := eta_relation_dvd hrel
      constructor
      · by_contra ha0
        have : a.degreeOf 1 = a'.degreeOf 1 + 1 := by
          rw [ha', mul_comm]
          exact (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 a').mpr
            (fun hc => ha0 (by rw [ha', hc, mul_zero]))
        omega
      · by_contra hb0
        have : b.degreeOf 1 = b'.degreeOf 1 + 1 := by
          rw [hb', mul_comm]
          exact (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 b').mpr
            (fun hc => hb0 (by rw [hb', hc, mul_zero]))
        omega
  | succ N ih =>
      intro a b hdeg hrel
      obtain ⟨⟨a', ha'⟩, ⟨b', hb'⟩⟩ := eta_relation_dvd hrel
      by_cases hab : a = 0 ∧ b = 0
      · exact hab
      · exfalso
        have hrel' : aeval ![xiPlane, planeZeta] a' * etaPlane
            + aeval ![xiPlane, planeZeta] b' = 0 := by
          have hz : aeval ![xiPlane, planeZeta] (X 1 : MvPolynomial (Fin 2) ℚ)
              = planeZeta := by simp
          rw [ha', hb', map_mul, map_mul, hz] at hrel
          have := mul_eq_zero.mp (by linear_combination hrel :
            planeZeta * (aeval ![xiPlane, planeZeta] a' * etaPlane
              + aeval ![xiPlane, planeZeta] b') = 0)
          rcases this with h | h
          · exact absurd h planeZeta_ne_zero
          · exact h
        have hda : a'.degreeOf 1 ≤ a.degreeOf 1 := by
          rcases eq_or_ne a' 0 with rfl | h
          · simp
          · rw [ha', mul_comm, (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 a').mpr h]; omega
        have hdb : b'.degreeOf 1 ≤ b.degreeOf 1 := by
          rcases eq_or_ne b' 0 with rfl | h
          · simp
          · rw [hb', mul_comm, (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 b').mpr h]; omega
        have hstrict : a'.degreeOf 1 + b'.degreeOf 1 < a.degreeOf 1 + b.degreeOf 1 := by
          rcases not_and_or.mp hab with h | h
          · have ha'0 : a' ≠ 0 := fun hc => h (by rw [ha', hc, mul_zero])
            rw [ha', mul_comm, (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 a').mpr ha'0]
            omega
          · have hb'0 : b' ≠ 0 := fun hc => h (by rw [hb', hc, mul_zero])
            rw [hb', mul_comm, (degreeOf_mul_X_eq_degreeOf_add_one_iff 1 b').mpr hb'0]
            omega
        obtain ⟨ha0, hb0⟩ := ih a' b' (by omega) hrel'
        exact hab ⟨by rw [ha', ha0, mul_zero], by rw [hb', hb0, mul_zero]⟩

/-- **The kernel of the evaluation is exactly the surface ideal.** -/
public theorem surfaceToPlane_eq_zero_iff {p : MvPolynomial (Fin 3) ℚ} :
    surfaceToPlane p = 0 ↔ p ∈ Ideal.span {weierstrassSurfaceAff} := by
  constructor
  · intro h
    obtain ⟨n, q, a, b, hdiv⟩ := exists_eta_division p
    have hval : aeval ![xiPlane, planeZeta] a * etaPlane
        + aeval ![xiPlane, planeZeta] b = 0 := by
      have h4 : surfaceToPlane (4 ^ n * p) = 0 := by rw [map_mul, h, mul_zero]
      rw [hdiv] at h4
      simp only [map_add, map_mul, surfaceToPlane_injXiZ, surfaceToPlane_vanishes,
        mul_zero, zero_add] at h4
      have he : surfaceToPlane (X 1) = etaPlane := by simp [surfaceToPlane]
      rw [he] at h4
      exact h4
    obtain ⟨ha, hb⟩ :=
      eta_relation_eq_zero (a.degreeOf 1 + b.degreeOf 1) a b le_rfl hval
    rw [ha, hb] at hdiv
    simp only [map_zero, zero_mul, add_zero] at hdiv
    rw [Ideal.mem_span_singleton]
    refine ⟨MvPolynomial.C (((4 : ℚ) ^ n)⁻¹) * q, ?_⟩
    have h4 : (4 : MvPolynomial (Fin 3) ℚ) ^ n = MvPolynomial.C ((4 : ℚ) ^ n) := by
      rw [map_pow, map_ofNat]
    have hu : MvPolynomial.C (((4 : ℚ) ^ n)⁻¹) * (4 : MvPolynomial (Fin 3) ℚ) ^ n = 1 := by
      rw [h4, ← map_mul, inv_mul_cancel₀ (by positivity), map_one]
    calc p = MvPolynomial.C (((4 : ℚ) ^ n)⁻¹) * (4 ^ n * p) := by
            rw [← mul_assoc, hu, one_mul]
      _ = weierstrassSurfaceAff * (MvPolynomial.C (((4 : ℚ) ^ n)⁻¹) * q) := by
            rw [hdiv]; ring
  · intro h
    rw [Ideal.mem_span_singleton] at h
    obtain ⟨c, rfl⟩ := h
    rw [map_mul, surfaceToPlane_vanishes, zero_mul]

/-- **Unirationality of the note's Weierstrass surface, field-theoretic form.**

The `ℚ`-algebra homomorphism from the affine coordinate ring of the Weierstrass
model (3.7) to the rational function field `ℚ(x, y)` in two variables is *injective*.
Equivalently: it is a field embedding `K(S) ↪ ℚ(x, y)` of the function field of the
surface into a purely transcendental extension of `ℚ` of the same transcendence
degree, i.e. the rational map `𝔸² ⤏ S` given by

    z = −f₀/f₁,   ξ = Θ/H²,   η = J/(2H³)

is *dominant*.

What this asserts: the affine coordinate ring `ℚ[ξ, η, z]/(4η² − 4ξ³ − 4z²(3−z)ξ − z·P(z))`
of the note's model (3.7) embeds into `ℚ(x, y)` by the displayed formulas.

What this does *not* assert: nothing about the *degree* of the map (the note's degree
9 is not used here); nothing about the weighted hypersurface `S_Q ⊂ P(1,1,2,3)` of
`DelPezzo/Surface.lean` — identifying `K(S)` with the function field of `S_Q` is a
separate birationality statement that is *not* formalized; and no scheme-theoretic
statement of unirationality. -/
public theorem surfaceCoordRingToPlane_injective :
    Function.Injective surfaceCoordRingToPlane := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [surfaceCoordRingToPlane_mk] at hx
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact surfaceToPlane_eq_zero_iff.mp hx

/-! ## Step 5: packaging — the function field embedding -/

/-- The affine coordinate ring of the note's Weierstrass model (3.7). -/
public abbrev surfaceCoordRing : Type :=
  MvPolynomial (Fin 3) ℚ ⧸ Ideal.span {weierstrassSurfaceAff}

/-- The affine Weierstrass surface is integral: its coordinate ring embeds in a field. -/
public instance : IsDomain surfaceCoordRing :=
  Function.Injective.isDomain surfaceCoordRingToPlane surfaceCoordRingToPlane_injective

/-- The function field of the note's Weierstrass model (3.7). -/
public abbrev surfaceFunctionField : Type := FractionRing surfaceCoordRing

/-- The induced map on function fields. -/
public noncomputable def surfaceFunctionFieldToPlane :
    surfaceFunctionField →+* FunctionField.planeField ℚ :=
  IsFractionRing.lift (g := (surfaceCoordRingToPlane : surfaceCoordRing →+* _))
    surfaceCoordRingToPlane_injective

public theorem surfaceFunctionFieldToPlane_algebraMap (x : surfaceCoordRing) :
    surfaceFunctionFieldToPlane (algebraMap surfaceCoordRing surfaceFunctionField x)
      = surfaceCoordRingToPlane x :=
  IsFractionRing.lift_algebraMap surfaceCoordRingToPlane_injective x

/-- **Unirationality of the note's Weierstrass surface, function-field form.**

The function field `K(S)` of the affine Weierstrass model (3.7) embeds into the
rational function field `ℚ(x, y)` in two variables, by

    z ↦ ζ = −f₀aff/f₁aff,   ξ ↦ Θ/H²,   η ↦ J/(2H³)

(`surfaceFunctionFieldToPlane_algebraMap`).  Since `ℚ(x, y)` is purely transcendental
over `ℚ` of transcendence degree 2, this says exactly that `S` is unirational over `ℚ`
in the function-field sense: there is a dominant rational map `𝔸² ⤏ S` defined over `ℚ`.

This asserts nothing about the *degree* of that map — the note's value 9 is neither used
nor reproved here — and nothing about the weighted hypersurface `S_Q ⊂ P(1,1,2,3)` of
`DelPezzo/Surface.lean`: identifying `K(S)` with the function field of `S_Q` is a
separate birationality statement that is not formalized. -/
public theorem surfaceFunctionFieldToPlane_injective :
    Function.Injective surfaceFunctionFieldToPlane :=
  surfaceFunctionFieldToPlane.injective

#print axioms surfaceCoordRingToPlane_injective
#print axioms surfaceFunctionFieldToPlane_injective

end ExplicitUnirational
