/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import Mathlib.Algebra.Polynomial.Eval.Irreducible
public import Mathlib.Algebra.Polynomial.FieldDivision
public import Mathlib.FieldTheory.RatFunc.AsPolynomial
public import Mathlib.FieldTheory.RatFunc.IntermediateField
public import Mathlib.FieldTheory.Separable
public import Mathlib.GroupTheory.GroupAction.Blocks
public import Mathlib.GroupTheory.GroupAction.Jordan
public import Mathlib.GroupTheory.GroupAction.Primitive
public import Mathlib.GroupTheory.Perm.ClosureSwap
public import Mathlib.RingTheory.Polynomial.Morse
public import Mathlib.RingTheory.Polynomial.Resultant.Basic
public import Mathlib.Tactic.FieldSimp
public import Mathlib.Tactic.NormNum
public import Mathlib.Tactic.Ring

/-!
# Monodromy of `T⁹ - T - 2t` ([CLOP Lemma 4.3], [CLOP Remark 4.4])

[CLOP Lemma 4.3]: the polynomial `f(T) = T⁹ - T - 2t` over `K = ℂ(t)` is irreducible and
separable. We also target the statement that the Galois group of its splitting field is `S₉`;
this is the concrete instance of [CLOP Remark 4.4], which states the corresponding statement
for the universal family — there `𝔖₉` is the geometric monodromy group of the universal base
scheme `ℬ → 𝒰`, not the Galois group of this single polynomial.

We work with an arbitrary field `F` of characteristic zero in place of `ℂ` (or with the weaker
hypothesis `(2 : F) ≠ 0` when char-zero is not needed). The Galois-theoretic content is unaffected.

## Delivered content

1. **Irreducibility and separability of `f`.** Following [CLOP Lemma 4.3]: the rational function
   `h = (T⁹ - T)/2` satisfies `[F(T) : F(h)] = 9` by `RatFunc.finrank_eq_max_natDegree`, and the
   minimal polynomial of `T` over `F(h)` is irreducible of degree 9. Transporting along the
   transcendental isomorphism `F(t) ≃ F(h)` yields irreducibility of
   `monodromyF = T⁹ - T - 2t ∈ F(t)[T]`. Separability is then char-0.

2. **Critical-point algebra.** If `9α⁸ = 1` then `h(α) = -4α/9`, so the critical-value map is
   injective on the finite critical points; the critical polynomial `9T⁸ - 1` is separable in
   char 0 (eight simple critical points).

3. **Group theory.** A transitive subgroup of a finite symmetric group generated by
   transpositions is the whole symmetric group
   (`closure_of_isSwap_of_isPretransitive` from Mathlib). Jordan's theorem is also available:
   a *preprimitive* subgroup containing a single transposition is already `S_n`
   (`subgroup_eq_top_of_isPreprimitive_of_isSwap_mem`). A transposition forces its two moved
   points into the same block of any nontrivial block system.

4. **Discriminant / algebraic Morse property.** For `f_a = T⁹ - T - a` one has
   `discr f_a = 9⁹ a⁸ - 8⁸`, obtained from the Euclidean algorithm for `Res(f_a, f_a')`.
   Specialising `a = 2t` recovers the discriminant of `monodromyF`. Consequently `f_a` has a
   multiple root if and only if `a` is a critical value, and any specialisation has **at most
   one** multiple root (the algebraic Morse condition of Serre, Topics in Galois Theory §4.4).
   Mathlib's `Polynomial.Splits.toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia`
   then says that any inertia element acts on the roots as the identity or a transposition.

## Remaining gap (item 5)

The algebraic substitute for the topological monodromy step of [CLOP Remark 4.4] is now
partially in place, but **not** complete enough to conclude `Gal(L/K) ≃ S₉`. Precisely:

* Mathlib *does* define inertia groups (`Ideal.inertia`, `ValuationSubring.inertiaSubgroup`)
  and proves `|I_P| = e(P|p)` in the Galois Dedekind setting
  (`Ideal.card_inertia_eq_ramificationIdxIn`), together with the Morse criterion above.
* Mathlib does **not** provide the bridge
  “simple zero of `discr f` ⇒ ramification index `e = 2` at a place of the splitting field”,
  nor “the Galois group of a finite Galois extension of `k(t)` is generated by the inertia
  groups of the ramified places” (the function-field analogue of Minkowski / generation by
  branch loops). The TODO in `Mathlib.RingTheory.Polynomial.Morse` records the number-field
  case of the latter as open.

Without those two lemmas one cannot promote “inertia acts as id or transposition” into
“Gal contains a transposition and is generated by such”, so we deliberately do **not** assert
`Gal(L/K) ≃ S₉`.
-/

noncomputable section

open Polynomial IntermediateField Algebra algebraAdjoinAdjoin
open scoped IntermediateField algebraAdjoinAdjoin

namespace ExplicitUnirational.MonodromyS9

variable {F : Type*} [Field F]

/-! ## Setup: the rational function `h` and the nonic `f` -/

/-- Polynomial representative of `(T⁹ - T)/2`. -/
public def monodromyPoly (F : Type*) [Field F] : F[X] :=
  C (2 : F)⁻¹ * (X ^ 9 - X)

/-- Rational function `h(T) = (T⁹ - T)/2` used in the proof of [CLOP Lemma 4.3]. -/
public def monodromyH (F : Type*) [Field F] : RatFunc F :=
  algebraMap F[X] (RatFunc F) (monodromyPoly F)

/-- The monic nonic `f(T) = T⁹ - T - 2t` over `F(t)`, the polynomial of [CLOP Lemma 4.3]. -/
public def monodromyF (F : Type*) [Field F] : (RatFunc F)[X] :=
  X ^ 9 - X - C (2 * RatFunc.X)

theorem monodromyH_num : (monodromyH F).num = monodromyPoly F := by
  simp only [monodromyH, RatFunc.num_algebraMap]

theorem monodromyH_denom : (monodromyH F).denom = 1 := by
  simp only [monodromyH, RatFunc.denom_algebraMap]

theorem monodromyPoly_natDegree (h2 : (2 : F) ≠ 0) : (monodromyPoly F).natDegree = 9 := by
  have h2' : (2 : F)⁻¹ ≠ 0 := inv_ne_zero h2
  dsimp only [monodromyPoly]
  rw [natDegree_C_mul h2']
  apply le_antisymm
  · exact (natDegree_sub_le _ _).trans <| by
      rw [natDegree_X_pow, natDegree_X]
      exact max_le le_rfl (by norm_num : 1 ≤ 9)
  · apply le_natDegree_of_ne_zero
    simp [coeff_X_pow, coeff_X]

/-- Step towards [CLOP Lemma 4.3]: `[F(T) : F(h)] = 9` for `h = (T⁹ - T)/2`. -/
public theorem monodromyH_finrank (h2 : (2 : F) ≠ 0) :
    Module.finrank F⟮monodromyH F⟯ (RatFunc F) = 9 := by
  rw [RatFunc.finrank_eq_max_natDegree, monodromyH_num, monodromyH_denom,
    monodromyPoly_natDegree h2, natDegree_one, max_eq_left (by norm_num : 0 ≤ 9)]

theorem monodromyH_ne_C (h2 : (2 : F) ≠ 0) : ¬∃ c : F, monodromyH F = RatFunc.C c := by
  intro ⟨c, hc⟩
  have hnum : (monodromyH F).num.natDegree = 9 := by
    rw [monodromyH_num, monodromyPoly_natDegree h2]
  have hnum0 : (monodromyH F).num.natDegree = 0 := by
    rw [hc, RatFunc.num_C]
    exact natDegree_C c
  omega

/-! ## Item 1: irreducibility and separability -/

/-- The minimal polynomial of `T` over `F(h)` is irreducible. -/
public theorem monodromy_minpoly_irreducible (h2 : (2 : F) ≠ 0) :
    Irreducible ((monodromyH F).minpolyX (↥F⟮monodromyH F⟯)) :=
  RatFunc.irreducible_minpolyX _ (monodromyH_ne_C h2)

/-- Separability of the minpoly of `T` over `F(h)` in characteristic zero. -/
public theorem monodromy_minpoly_separable [CharZero F] (h2 : (2 : F) ≠ 0) :
    Separable ((monodromyH F).minpolyX (↥F⟮monodromyH F⟯)) :=
  (monodromy_minpoly_irreducible h2).separable

private theorem monodromy_minpolyX_eq' :
    (monodromyH F).minpolyX (↥F⟮monodromyH F⟯) =
      C (algebraMap F _ (2 : F)⁻¹) * (X ^ 9 - X) -
        C (algebraMap (Algebra.adjoin F {monodromyH F}) _
          ⟨monodromyH F, self_mem_adjoin_singleton F _⟩) := by
  unfold RatFunc.minpolyX
  rw [monodromyH_num, monodromyH_denom, monodromyPoly]
  simp only [Polynomial.map_mul, Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.map_C]
  rw [Polynomial.map_one, mul_one]

private theorem monodromy_C_two_mul_minpoly (h2 : (2 : F) ≠ 0) :
    C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F)) *
        ((monodromyH F).minpolyX (↥F⟮monodromyH F⟯)) =
      X ^ 9 - X -
        C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F) *
            (AdjoinSimple.gen F (monodromyH F) : ↥F⟮monodromyH F⟯)) := by
  rw [monodromy_minpolyX_eq']
  have hinv : (2 : F) * (2 : F)⁻¹ = 1 := mul_inv_cancel₀ h2
  calc
    C (algebraMap F _ (2 : F)) *
          (C (algebraMap F _ (2 : F)⁻¹) * (X ^ 9 - X) -
            C (algebraMap (Algebra.adjoin F {monodromyH F}) _
              ⟨monodromyH F, self_mem_adjoin_singleton F _⟩))
        = C (algebraMap F _ (2 : F)) * C (algebraMap F _ (2 : F)⁻¹) * (X ^ 9 - X) -
            C (algebraMap F _ (2 : F)) *
              C (algebraMap (Algebra.adjoin F {monodromyH F}) _
                ⟨monodromyH F, self_mem_adjoin_singleton F _⟩) := by
            ring
    _ = C (algebraMap F _ ((2 : F) * (2 : F)⁻¹)) * (X ^ 9 - X) -
            C (algebraMap F _ (2 : F) *
              algebraMap (Algebra.adjoin F {monodromyH F}) _
                ⟨monodromyH F, self_mem_adjoin_singleton F _⟩) := by
            simp only [← map_mul, ← map_mul (f := C)]
    _ = X ^ 9 - X -
            C (algebraMap F _ (2 : F) *
              (AdjoinSimple.gen F (monodromyH F) : ↥F⟮monodromyH F⟯)) := by
            rw [hinv, map_one, C_1, one_mul, algebraMap_eq_gen_self]

/-- The monic form `X⁹ - X - 2·h` over `F(h)` is irreducible. -/
public theorem monodromy_monic_over_h_irreducible (h2 : (2 : F) ≠ 0) :
    Irreducible
      (X ^ 9 - X -
        C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F) *
            (AdjoinSimple.gen F (monodromyH F) : ↥F⟮monodromyH F⟯)) :
        (↥F⟮monodromyH F⟯)[X]) := by
  have hunit : IsUnit (C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F)) :
      (↥F⟮monodromyH F⟯)[X]) := by
    rw [isUnit_C]
    exact (algebraMap F (↥F⟮monodromyH F⟯)).isUnit_map (Ne.isUnit h2)
  have heq := monodromy_C_two_mul_minpoly (F := F) h2
  have hassoc : Associated ((monodromyH F).minpolyX (↥F⟮monodromyH F⟯))
      (X ^ 9 - X -
        C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F) *
            (AdjoinSimple.gen F (monodromyH F) : ↥F⟮monodromyH F⟯))) := by
    refine ⟨hunit.unit, ?_⟩
    rw [IsUnit.unit_spec, mul_comm, heq]
  exact hassoc.irreducible (monodromy_minpoly_irreducible h2)

public theorem monodromyF_coeff_nine : (monodromyF F).coeff 9 = 1 := by
  simp only [monodromyF, coeff_sub, coeff_X_pow, coeff_X, coeff_C]
  norm_num

public theorem monodromyF_natDegree : (monodromyF F).natDegree = 9 := by
  refine natDegree_eq_of_le_of_coeff_ne_zero ?_ (by
    rw [monodromyF_coeff_nine]; exact one_ne_zero)
  calc
    (monodromyF F).natDegree
        ≤ max (X ^ 9 - X : (RatFunc F)[X]).natDegree
            (C (2 * RatFunc.X) : (RatFunc F)[X]).natDegree :=
      natDegree_sub_le _ _
    _ = max (X ^ 9 - X : (RatFunc F)[X]).natDegree 0 := by
      rw [natDegree_C]
    _ ≤ max (max (X ^ 9 : (RatFunc F)[X]).natDegree (X : (RatFunc F)[X]).natDegree) 0 := by
      gcongr
      exact natDegree_sub_le _ _
    _ = max (max 9 1) 0 := by
      simp only [natDegree_X_pow, natDegree_X]
    _ = 9 := by decide

public theorem monodromyF_monic : (monodromyF F).Monic := by
  rw [Monic.def, leadingCoeff, monodromyF_natDegree, monodromyF_coeff_nine]

/-- [CLOP Lemma 4.3]: `f(T) = T⁹ - T - 2t` is irreducible over `F(t)` when `2 ≠ 0`. -/
public theorem monodromyF_irreducible (h2 : (2 : F) ≠ 0) : Irreducible (monodromyF F) := by
  have htr := RatFunc.transcendental_of_ne_C (monodromyH F) (monodromyH_ne_C h2)
  let φ : RatFunc F →+* ↥F⟮monodromyH F⟯ :=
    (RatFunc.algEquivOfTranscendental (monodromyH F) htr).toRingHom
  have hφX : φ RatFunc.X = AdjoinSimple.gen F (monodromyH F) := by
    apply Subtype.ext
    change ((RatFunc.algEquivOfTranscendental (monodromyH F) htr) RatFunc.X : RatFunc F) =
      monodromyH F
    rw [RatFunc.algEquivOfTranscendental_X]
  have hφ2 : φ (2 : RatFunc F) = algebraMap F _ (2 : F) := by
    have : (2 : RatFunc F) = algebraMap F (RatFunc F) (2 : F) := by
      simp [map_ofNat]
    rw [this]
    exact (RatFunc.algEquivOfTranscendental (monodromyH F) htr).commutes (2 : F)
  have hmap : (monodromyF F).map φ =
      X ^ 9 - X -
        C (algebraMap F (↥F⟮monodromyH F⟯) (2 : F) *
            (AdjoinSimple.gen F (monodromyH F) : ↥F⟮monodromyH F⟯)) := by
    dsimp only [monodromyF]
    rw [Polynomial.map_sub, Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
      Polynomial.map_C, map_mul, hφ2, hφX]
  exact Monic.irreducible_of_irreducible_map φ (monodromyF F) monodromyF_monic (by
    rw [hmap]
    exact monodromy_monic_over_h_irreducible h2)

/-- Separability of `f` over `F(t)` in characteristic zero. -/
public theorem monodromyF_separable [CharZero F] (h2 : (2 : F) ≠ 0) :
    Separable (monodromyF F) :=
  (monodromyF_irreducible h2).separable

/-- Specialization to `ℚ(t)`: [CLOP Lemma 4.3] with `ℚ` in place of `ℂ`. -/
public theorem monodromyF_irreducible_rat : Irreducible (monodromyF ℚ) :=
  monodromyF_irreducible (by norm_num : (2 : ℚ) ≠ 0)

public theorem monodromyF_separable_rat : Separable (monodromyF ℚ) :=
  monodromyF_separable (by norm_num : (2 : ℚ) ≠ 0)

/-! ## Item 2: critical points of `h` -/

/-- At a finite critical point `α` of `h(T) = (T⁹ - T)/2` (i.e. `9α⁸ = 1`),
one has `h(α) = -4α/9`. -/
public theorem critical_value_formula {K : Type*} [Field K] (α : K)
    (hcrit : (9 : K) * α ^ 8 = 1) (h2 : (2 : K) ≠ 0) :
    (α ^ 9 - α) / 2 = - (4 : K) * α / 9 := by
  have h9 : (9 : K) ≠ 0 := by
    intro h
    rw [h, zero_mul] at hcrit
    exact zero_ne_one hcrit
  -- From 9α⁸ = 1, multiply by α: 9α⁹ = α, so α⁹ = α/9.
  have h' : (9 : K) * α ^ 9 = α := by
    calc
      (9 : K) * α ^ 9 = (9 : K) * α ^ 8 * α := by ring
      _ = 1 * α := by rw [hcrit]
      _ = α := one_mul α
  have hα9 : α ^ 9 = α / 9 := (eq_div_iff h9).mpr (by rw [mul_comm]; exact h')
  -- (α/9 - α)/2 = -4α/9
  rw [hα9]
  field_simp [h2, h9]
  ring

/-- The critical-value map `α ↦ -4α/9` is injective
(hence finite critical values arising from distinct critical points are pairwise distinct). -/
public theorem critical_values_injective {K : Type*} [Field K] (α β : K)
    (heq : - (4 : K) * α / 9 = - (4 : K) * β / 9)
    (h4 : (4 : K) ≠ 0) (h9 : (9 : K) ≠ 0) : α = β := by
  field_simp [h4, h9] at heq
  -- heq : -α = -β
  exact neg_injective heq

/-- The critical polynomial `9T⁸ - 1` is separable in characteristic zero
(so the eight finite critical points are simple). -/
public theorem critical_poly_separable {K : Type*} [Field K] [CharZero K] :
    Separable ((C (9 : K) * X ^ 8 - 1 : K[X])) := by
  have h9 : (9 : K) ≠ 0 := by norm_num
  have h8 : (8 : K) ≠ 0 := by norm_num
  have heq : C (9 : K) * X ^ 8 - 1 = C (9 : K) * (X ^ 8 - C ((9 : K)⁻¹)) := by
    rw [mul_sub, ← C_mul, mul_inv_cancel₀ h9, C_1]
  rw [heq]
  exact Separable.unit_mul (isUnit_C.mpr (Ne.isUnit h9))
    (separable_X_pow_sub_C (9 : K)⁻¹ h8 (inv_ne_zero h9))

/-! ## Item 3: generation of `S_n` by transpositions; Jordan; blocks -/

open Equiv Equiv.Perm MulAction
open scoped Pointwise

/-- A transitive subgroup of a finite symmetric group generated by transpositions is the whole
symmetric group. This is the group-theoretic last step towards the `S₉` statement for
`T⁹ - T - 2t`, the concrete instance of [CLOP Remark 4.4]
(`closure_of_isSwap_of_isPretransitive`). -/
public theorem transitive_closure_swaps_eq_top {α : Type*} [DecidableEq α] [Finite α]
    {S : Set (Perm α)} (hS : ∀ σ ∈ S, σ.IsSwap)
    [MulAction.IsPretransitive (Subgroup.closure S) α] :
    Subgroup.closure S = ⊤ :=
  closure_of_isSwap_of_isPretransitive hS

/-- Packaging: if `G ≤ Sym(α)` equals the closure of a set of transpositions and acts
transitively, then `G` is the full symmetric group. -/
public theorem eq_top_of_generated_by_swaps_of_isPretransitive {α : Type*} [DecidableEq α]
    [Finite α] (G : Subgroup (Perm α)) {S : Set (Perm α)} (hS : ∀ σ ∈ S, σ.IsSwap)
    (hgen : Subgroup.closure S = G) [MulAction.IsPretransitive G α] : G = ⊤ := by
  subst hgen
  exact closure_of_isSwap_of_isPretransitive hS

/-- Jordan's theorem (Wielandt 13.3): a preprimitive permutation group containing a transposition
is the full symmetric group. -/
public theorem eq_top_of_isPreprimitive_of_isSwap_mem {α : Type*} [DecidableEq α] [Finite α]
    (G : Subgroup (Perm α)) [IsPreprimitive G α] {g : Perm α}
    (hg_swap : g.IsSwap) (hg : g ∈ G) : G = ⊤ :=
  subgroup_eq_top_of_isPreprimitive_of_isSwap_mem (G := G) (hG := ‹_›) g hg_swap hg

/-- If a `G`-block contains exactly one of the two points moved by a transposition belonging to
`G`, then the block is a subsingleton. -/
public theorem isBlock_subsingleton_of_isSwap_cuts {α : Type*} [DecidableEq α]
    {G : Subgroup (Perm α)} {B : Set α} (hB : IsBlock (↥G) B)
    {a b : α} (_hab : a ≠ b) (hswap : Equiv.swap a b ∈ G)
    (ha : a ∈ B) (hb : b ∉ B) : B.Subsingleton := by
  classical
  intro x hx y hy
  by_contra hne
  have hex : ∃ z ∈ B, z ≠ a := by
    by_cases hxa : x = a
    · exact ⟨y, hy, fun hya => hne (hxa.trans hya.symm)⟩
    · exact ⟨x, hx, hxa⟩
  obtain ⟨z, hzB, hza⟩ := hex
  have hzb : z ≠ b := fun h => hb (h ▸ hzB)
  set τ : ↥G := ⟨Equiv.swap a b, hswap⟩
  have hz_fixed : (τ : Perm α) z = z := Equiv.swap_apply_of_ne_of_ne hza hzb
  have h_meet : ((τ : ↥G) • B ∩ B).Nonempty := by
    refine ⟨z, ?_, hzB⟩
    exact ⟨z, hzB, by
      change (τ : Perm α) • z = z
      simpa using hz_fixed⟩
  have h_ne : (τ : ↥G) • B ≠ B := by
    intro heq
    have hb' : b ∈ (τ : ↥G) • B :=
      ⟨a, ha, by
        change (τ : Perm α) • a = b
        simp [τ]⟩
    exact hb (heq ▸ hb')
  have h_or := (isBlock_iff_smul_eq_smul_or_disjoint.mp hB) τ (1 : ↥G)
  rw [one_smul] at h_or
  exact h_or.elim (fun h => h_ne h) fun hdisj =>
    (Set.not_disjoint_iff_nonempty_inter.mpr h_meet) hdisj

/-- A transposition in `G` forces both moved points into every non-subsingleton block that
contains one of them. -/
public theorem mem_block_of_isSwap_mem {α : Type*} [DecidableEq α]
    {G : Subgroup (Perm α)} {B : Set α} (hB : IsBlock (↥G) B)
    {a b : α} (hab : a ≠ b) (hswap : Equiv.swap a b ∈ G)
    (ha : a ∈ B) (hnontriv : ¬ B.Subsingleton) : b ∈ B := by
  by_contra hb
  exact hnontriv (isBlock_subsingleton_of_isSwap_cuts hB hab hswap ha hb)

/-- For a pretransitive action on a 9-element set, every non-trivial proper block has
cardinality 3. -/
public theorem ncard_eq_three_of_isBlock_card_nine {G α : Type*} [Group G] [MulAction G α]
    [IsPretransitive G α] [Finite α] (hcard : Nat.card α = 9) {B : Set α}
    (hB : IsBlock G B) (hB_ne : B.Nonempty) (hB_not_sub : ¬ B.Subsingleton)
    (hB_ne_univ : B ≠ Set.univ) : B.ncard = 3 := by
  classical
  letI : Fintype α := Fintype.ofFinite α
  have hdvd0 : B.ncard ∣ Nat.card α := hB.ncard_dvd_card hB_ne
  have hdvd : B.ncard ∣ 9 := by rwa [hcard] at hdvd0
  have hne1 : B.ncard ≠ 1 := fun h =>
    hB_not_sub (Set.ncard_le_one_iff_subsingleton.mp (by omega))
  have hlt : B.ncard < 9 := by
    have hss : B ⊂ Set.univ := Set.ssubset_univ_iff.mpr hB_ne_univ
    have hlt' : B.ncard < (Set.univ : Set α).ncard := Set.ncard_lt_ncard hss (Set.toFinite _)
    have hcard' : (Set.univ : Set α).ncard = 9 := by
      rw [Set.ncard_univ, Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card, hcard]
    omega
  have hmem : B.ncard ∈ Nat.divisors 9 := Nat.mem_divisors.mpr ⟨hdvd, by decide⟩
  have hdiv : Nat.divisors 9 = {1, 3, 9} := by decide
  rw [hdiv] at hmem
  simp only [Finset.mem_insert, Finset.mem_singleton] at hmem
  rcases hmem with h | h | h
  · exact absurd h hne1
  · exact h
  · exact absurd h (ne_of_lt hlt)

/-! ## Item 4: discriminant of `T⁹ - T - a` and the algebraic Morse property -/

/-- The one-parameter nonic `T⁹ - T - a`. -/
public def nonic (K : Type*) [Field K] (a : K) : K[X] :=
  X ^ 9 - X - C a

public theorem monodromyF_eq_nonic (F : Type*) [Field F] :
    monodromyF F = nonic (RatFunc F) (2 * RatFunc.X) := by
  dsimp only [monodromyF, nonic]

public theorem nonic_natDegree {K : Type*} [Field K] (a : K) : (nonic K a).natDegree = 9 := by
  dsimp only [nonic]
  refine natDegree_eq_of_le_of_coeff_ne_zero ?_ ?_
  · calc
      (X ^ 9 - X - C a : K[X]).natDegree
          ≤ max (X ^ 9 - X : K[X]).natDegree (C a).natDegree := natDegree_sub_le _ _
      _ = max (X ^ 9 - X : K[X]).natDegree 0 := by rw [natDegree_C]
      _ ≤ max (max (X ^ 9 : K[X]).natDegree (X : K[X]).natDegree) 0 := by
        gcongr; exact natDegree_sub_le _ _
      _ = max (max 9 1) 0 := by simp only [natDegree_X_pow, natDegree_X]
      _ = 9 := by decide
  · simp [coeff_X_pow, coeff_X]

public theorem nonic_monic {K : Type*} [Field K] (a : K) : (nonic K a).Monic := by
  rw [Monic.def, leadingCoeff, nonic_natDegree]
  dsimp only [nonic]
  simp [coeff_X_pow, coeff_X]

public theorem nonic_derivative {K : Type*} [Field K] (a : K) :
    (nonic K a).derivative = C (9 : K) * X ^ 8 - 1 := by
  dsimp only [nonic]
  simp only [derivative_sub, derivative_X_pow, derivative_X, derivative_C, Nat.cast_ofNat]
  ring

/-- Euclidean step: `T⁹ - T - a = (9T⁸ - 1)·(T/9) + (-(8/9)T - a)`. -/
public theorem nonic_euclidean {K : Type*} [Field K] (a : K) (h9 : (9 : K) ≠ 0) :
    nonic K a =
      (C (9 : K) * X ^ 8 - 1) * (C ((9 : K)⁻¹) * X) +
        (C (-(8 : K) * (9 : K)⁻¹) * X - C a) := by
  dsimp only [nonic]
  have hinv : (9 : K) * (9 : K)⁻¹ = 1 := mul_inv_cancel₀ h9
  have hpow : (C (9 : K) * X ^ 8) * (C ((9 : K)⁻¹) * X) = X ^ 9 := by
    calc
      (C (9 : K) * X ^ 8) * (C ((9 : K)⁻¹) * X)
          = C (9 : K) * C ((9 : K)⁻¹) * (X ^ 8 * X) := by ring
      _ = C ((9 : K) * (9 : K)⁻¹) * (X ^ 8 * X) := by rw [← map_mul C]
      _ = C (1 : K) * (X ^ 8 * X) := by rw [hinv]
      _ = X ^ 8 * X := by simp
      _ = X ^ 9 := by ring
  have hcoef : -((9 : K)⁻¹) + (-(8 : K) * (9 : K)⁻¹) = (-1 : K) := by
    field_simp [h9]
    ring
  have hlin : -(C ((9 : K)⁻¹) * X) + C (-(8 : K) * (9 : K)⁻¹) * X = -X := by
    calc
      -(C ((9 : K)⁻¹) * X) + C (-(8 : K) * (9 : K)⁻¹) * X
          = (C (-((9 : K)⁻¹)) + C (-(8 : K) * (9 : K)⁻¹)) * X := by
            simp [neg_mul, add_mul]
      _ = C (-((9 : K)⁻¹) + (-(8 : K) * (9 : K)⁻¹)) * X := by rw [← map_add C]
      _ = C (-1 : K) * X := by rw [hcoef]
      _ = -X := by simp
  calc
    X ^ 9 - X - C a
        = X ^ 9 + (-X) - C a := by ring
    _ = (C (9 : K) * X ^ 8) * (C ((9 : K)⁻¹) * X) +
          (-(C ((9 : K)⁻¹) * X) + C (-(8 : K) * (9 : K)⁻¹) * X) - C a := by
        rw [hpow, hlin]
    _ = (C (9 : K) * X ^ 8 - 1) * (C ((9 : K)⁻¹) * X) +
          (C (-(8 : K) * (9 : K)⁻¹) * X - C a) := by ring

private theorem nonic_remainder_factor {K : Type*} [Field K] (a : K)
    (h9 : (9 : K) ≠ 0) (h8 : (8 : K) ≠ 0) :
    C (-(8 : K) * (9 : K)⁻¹) * X - C a =
      C (-(8 : K) * (9 : K)⁻¹) * (X - C (-(9 : K) * a * (8 : K)⁻¹)) := by
  have hprod : (-(8 : K) * (9 : K)⁻¹) * (-(9 : K) * a * (8 : K)⁻¹) = a := by
    field_simp [h9, h8]
  rw [mul_sub, ← map_mul C, hprod]

private theorem natDegree_nine_X_pow_eight_sub_one {K : Type*} [Field K] (h9 : (9 : K) ≠ 0) :
    (C (9 : K) * X ^ 8 - 1 : K[X]).natDegree = 8 := by
  refine natDegree_eq_of_le_of_coeff_ne_zero ?_ ?_
  · refine (natDegree_sub_le _ _).trans ?_
    simp only [natDegree_one]
    have : (C (9 : K) * X ^ 8).natDegree ≤ 8 := by
      rw [natDegree_C_mul h9, natDegree_X_pow]
    exact max_le this (by decide)
  · -- coeff 8 of `C 9 * X^8 - 1` is 9
    have h1 : (1 : K[X]).coeff 8 = 0 := by simp [coeff_one]
    simp only [coeff_sub, coeff_C_mul, coeff_X_pow_self, mul_one, h1, sub_zero]
    exact h9

/-- `Res(T⁹ - T - a, 9T⁸ - 1) = 9⁹ a⁸ - 8⁸`. -/
public theorem nonic_resultant_derivative {K : Type*} [Field K] (a : K)
    (h9 : (9 : K) ≠ 0) (h8 : (8 : K) ≠ 0) :
    resultant (nonic K a) (derivative (nonic K a)) =
      (9 : K) ^ 9 * a ^ 8 - (8 : K) ^ 8 := by
  rw [nonic_derivative]
  set g : K[X] := C (9 : K) * X ^ 8 - 1
  set p : K[X] := C ((9 : K)⁻¹) * X
  set r : K[X] := C (-(8 : K) * (9 : K)⁻¹) * X - C a
  have hfp : nonic K a = g * p + r := by
    simpa [g, p, r] using nonic_euclidean (K := K) a h9
  have hg_deg : g.natDegree = 8 := natDegree_nine_X_pow_eight_sub_one h9
  have hp_deg : p.natDegree ≤ 1 := by
    dsimp [p]
    have : (9 : K)⁻¹ ≠ 0 := inv_ne_zero h9
    simp [natDegree_C_mul this, natDegree_X]
  have hr_deg : r.natDegree ≤ 1 := by
    dsimp [r]
    refine (natDegree_sub_le _ _).trans ?_
    refine max_le ?_ (by simp [natDegree_C])
    by_cases hc : (-(8 : K) * (9 : K)⁻¹ : K) = 0
    · simp [hc]
    · rw [natDegree_C_mul hc, natDegree_X]
  have hres_eq : resultant (nonic K a) g 9 8 = resultant r g 9 8 := by
    have hk : p.natDegree + 8 ≤ 9 := (Nat.add_le_add_right hp_deg 8).trans (by decide)
    have := resultant_add_mul_left (f := r) (g := g) (p := p) (m := 9) (n := 8) hk hg_deg.le
    have hsum : r + g * p = nonic K a := by rw [hfp]; ring
    rwa [hsum] at this
  have hres_pad : resultant r g 9 8 = (9 : K) ^ 8 * resultant r g 1 8 := by
    have := resultant_add_left_deg (f := r) (g := g) (m := 1) (n := 8) (k := 8) hr_deg
    simp only [Nat.reduceAdd] at this
    have hsign : ((-1 : K) ^ (8 * 8) : K) = 1 := by norm_num
    have hcoeff : g.coeff 8 = (9 : K) := by
      dsimp [g]
      have h1 : (1 : K[X]).coeff 8 = 0 := by simp [coeff_one]
      simp only [coeff_sub, coeff_C_mul, coeff_X_pow_self, mul_one, h1, sub_zero]
    rw [this, hsign, hcoeff, one_mul]
  have hr_fac : r = C (-(8 : K) * (9 : K)⁻¹) * (X - C (-(9 : K) * a * (8 : K)⁻¹)) :=
    nonic_remainder_factor a h9 h8
  have hres_lin : resultant r g 1 8 =
      (-(8 : K) * (9 : K)⁻¹) ^ 8 * eval (-(9 : K) * a * (8 : K)⁻¹) g := by
    rw [hr_fac, resultant_C_mul_left]
    exact congr_arg _ (resultant_X_sub_C_left (R := K) (g := g) (n := 8)
      (-(9 : K) * a * (8 : K)⁻¹) hg_deg.le)
  have heval : eval (-(9 : K) * a * (8 : K)⁻¹) g =
      (9 : K) * (-(9 : K) * a * (8 : K)⁻¹) ^ 8 - 1 := by
    dsimp [g]; simp [eval_sub, eval_mul, eval_C, eval_pow, eval_X, eval_one]
  have hmain : resultant r g 9 8 = (9 : K) ^ 9 * a ^ 8 - (8 : K) ^ 8 := by
    rw [hres_pad, hres_lin, heval]
    have hpow_c : (-(8 : K) * (9 : K)⁻¹ : K) ^ 8 = (8 : K) ^ 8 * ((9 : K)⁻¹) ^ 8 := by
      rw [mul_pow, neg_pow, Even.neg_one_pow (by decide : Even 8), one_mul]
    have hpow_neg : (-(9 : K) * a * (8 : K)⁻¹ : K) ^ 8 =
        ((9 : K) ^ 8 * a ^ 8 * ((8 : K)⁻¹) ^ 8) := by
      have : (-(9 : K) * a * (8 : K)⁻¹ : K) = -((9 : K) * a * (8 : K)⁻¹) := by ring
      rw [this, neg_pow, Even.neg_one_pow (by decide : Even 8), one_mul, mul_pow, mul_pow]
    rw [hpow_c, hpow_neg]
    field_simp [h9, h8]
  have hnd : (nonic K a).natDegree = 9 := nonic_natDegree a
  -- Default `resultant` uses `natDegree`s; rewrite to the explicit degrees used above.
  have hres_def : resultant (nonic K a) g = resultant (nonic K a) g 9 8 := by
    dsimp only [resultant]
    rw [hnd, hg_deg]
  rw [hres_def, hres_eq, hmain]

/-- Discriminant of `T⁹ - T - a` equals `9⁹ a⁸ - 8⁸`. -/
public theorem nonic_discr {K : Type*} [Field K] (a : K)
    (h9 : (9 : K) ≠ 0) (h8 : (8 : K) ≠ 0) :
    discr (nonic K a) = (9 : K) ^ 9 * a ^ 8 - (8 : K) ^ 8 := by
  have hne : nonic K a ≠ 0 := fun h => by
    have := congr_arg natDegree h; simp [nonic_natDegree] at this
  have hdeg : (0 : WithBot ℕ) < (nonic K a).degree := by
    rw [degree_eq_natDegree hne, nonic_natDegree]
    exact WithBot.coe_lt_coe.mpr (by decide : (0 : ℕ) < 9)
  have hres := nonic_resultant_derivative (K := K) a h9 h8
  have hrel := resultant_deriv (f := nonic K a) hdeg
  have hsign :
      ((-1 : K) ^ ((nonic K a).natDegree * ((nonic K a).natDegree - 1) / 2) : K) = 1 := by
    rw [nonic_natDegree]; norm_num
  have hlead : (nonic K a).leadingCoeff = 1 := (nonic_monic a).leadingCoeff
  have hder_deg : (nonic K a).derivative.natDegree = 8 := by
    rw [nonic_derivative, natDegree_nine_X_pow_eight_sub_one h9]
  -- Align default degrees with those appearing in `resultant_deriv`.
  have hres_def :
      resultant (nonic K a) (nonic K a).derivative =
        resultant (nonic K a) (nonic K a).derivative 9 8 := by
    dsimp only [resultant]
    rw [nonic_natDegree a, hder_deg]
  have hrel' :
      resultant (nonic K a) (nonic K a).derivative 9 8 =
        discr (nonic K a) := by
    have hdeg_eq :
        resultant (nonic K a) (nonic K a).derivative
            (nonic K a).natDegree ((nonic K a).natDegree - 1) =
          resultant (nonic K a) (nonic K a).derivative 9 8 := by
      rw [nonic_natDegree a]
    rw [← hdeg_eq, hrel, hsign, hlead, one_mul, one_mul]
  have : resultant (nonic K a) (nonic K a).derivative = discr (nonic K a) := by
    rw [hres_def, hrel']
  rwa [← this]

/-- Discriminant of `monodromyF` over `F(t)` in characteristic zero. -/
public theorem monodromyF_discr [CharZero F] :
    discr (monodromyF F) =
      (9 : RatFunc F) ^ 9 * (2 * RatFunc.X) ^ 8 - (8 : RatFunc F) ^ 8 := by
  rw [monodromyF_eq_nonic]
  exact nonic_discr (2 * RatFunc.X)
    (by norm_num : (9 : RatFunc F) ≠ 0) (by norm_num : (8 : RatFunc F) ≠ 0)

/-- Factored form: `disc(monodromyF) = 256 · (19683 t⁴ - 256) · (19683 t⁴ + 256)`. -/
public theorem monodromyF_discr_factorized [CharZero F] :
    discr (monodromyF F) =
      (256 : RatFunc F) *
        ((19683 : RatFunc F) * RatFunc.X ^ 4 - (256 : RatFunc F)) *
        ((19683 : RatFunc F) * RatFunc.X ^ 4 + (256 : RatFunc F)) := by
  rw [monodromyF_discr]
  have e1 : (9 : RatFunc F) ^ 9 = (387420489 : RatFunc F) := by norm_num
  have e2 : (8 : RatFunc F) ^ 8 = (16777216 : RatFunc F) := by norm_num
  rw [e1, e2]
  ring

/-- A multiple root of `nonic a` is a critical point. -/
public theorem isMultipleRoot_iff {K : Type*} [Field K] {a α : K}
    (hne : nonic K a ≠ 0) :
    1 < rootMultiplicity α (nonic K a) ↔
      IsRoot (nonic K a) α ∧ (9 : K) * α ^ 8 = 1 := by
  rw [one_lt_rootMultiplicity_iff_isRoot hne, nonic_derivative]
  constructor
  · intro ⟨hr, hd⟩
    refine ⟨hr, ?_⟩
    simp only [IsRoot, eval_sub, eval_mul, eval_C, eval_pow, eval_X, eval_one] at hd
    linear_combination hd
  · intro ⟨hr, hc⟩
    refine ⟨hr, ?_⟩
    simp only [IsRoot, eval_sub, eval_mul, eval_C, eval_pow, eval_X, eval_one]
    linear_combination hc

/-- At a root `α` of `nonic a` one has `a = α⁹ - α`. -/
public theorem eq_of_isRoot_nonic {K : Type*} [Field K] {a α : K}
    (hroot : IsRoot (nonic K a) α) : a = α ^ 9 - α := by
  simp only [IsRoot, nonic, eval_sub, eval_pow, eval_X, eval_C] at hroot
  linear_combination -hroot

/-- Algebraic Morse property: `nonic a` has at most one multiple root. -/
public theorem nonic_at_most_one_multiple_root {K : Type*} [Field K] [CharZero K] (a : K)
    {α β : K}
    (hα : 1 < rootMultiplicity α (nonic K a))
    (hβ : 1 < rootMultiplicity β (nonic K a)) : α = β := by
  have hne : nonic K a ≠ 0 := fun h => by
    have := congr_arg natDegree h; simp [nonic_natDegree] at this
  have hα' := (isMultipleRoot_iff hne).mp hα
  have hβ' := (isMultipleRoot_iff hne).mp hβ
  have h2 : (2 : K) ≠ 0 := by norm_num
  have h4 : (4 : K) ≠ 0 := by norm_num
  have h9 : (9 : K) ≠ 0 := by norm_num
  have haα : a = α ^ 9 - α := eq_of_isRoot_nonic hα'.1
  have haβ : a = β ^ 9 - β := eq_of_isRoot_nonic hβ'.1
  have hαval : (α ^ 9 - α) / 2 = - (4 : K) * α / 9 :=
    critical_value_formula α hα'.2 h2
  have hβval : (β ^ 9 - β) / 2 = - (4 : K) * β / 9 :=
    critical_value_formula β hβ'.2 h2
  have : - (4 : K) * α / 9 = - (4 : K) * β / 9 := by
    calc
      - (4 : K) * α / 9 = (α ^ 9 - α) / 2 := hαval.symm
      _ = a / 2 := by rw [← haα]
      _ = (β ^ 9 - β) / 2 := by rw [haβ]
      _ = - (4 : K) * β / 9 := hβval
  exact critical_values_injective α β this h4 h9

/-- Mathlib's Morse lemma packaged: under the single-collision bound, inertia acts on roots as
the identity or a transposition. -/
public theorem inertia_toPerm_eq_one_or_isSwap
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] [IsDomain S]
    {G : Type*} [Group G] [MulSemiringAction G S] [SMulCommClass G R S]
    {f : R[X]} [DecidableEq (f.rootSet S)]
    (hf : (f.map (algebraMap R S)).Splits) (p : Ideal S) [p.IsPrime]
    (hp : (f.rootSet S).ncard ≤ (f.rootSet (S ⧸ p)).ncard + 1)
    (g : G) (hg : g ∈ p.inertia G) :
    MulAction.toPermHom G (f.rootSet S) g = 1 ∨
      (MulAction.toPermHom G (f.rootSet S) g).IsSwap :=
  hf.toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia p hp g hg

/-! ## Axiom audit for headline theorems -/

#print axioms monodromyF_irreducible_rat
#print axioms monodromyF_separable_rat
#print axioms monodromyH_finrank
#print axioms critical_value_formula
#print axioms critical_poly_separable
#print axioms transitive_closure_swaps_eq_top
#print axioms eq_top_of_isPreprimitive_of_isSwap_mem
#print axioms isBlock_subsingleton_of_isSwap_cuts
#print axioms ncard_eq_three_of_isBlock_card_nine
#print axioms nonic_discr
#print axioms monodromyF_discr
#print axioms monodromyF_discr_factorized
#print axioms nonic_at_most_one_multiple_root
#print axioms inertia_toPerm_eq_one_or_isSwap

end ExplicitUnirational.MonodromyS9
