/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.FunctionField.MulThree
public import Mathlib.FieldTheory.RatFunc.AsPolynomial
public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.Tactic.Ring
public import Mathlib.Tactic.NormNum

/-!
# Coprimality certificates for `Φ₃` and `ΨSq₃` on the note's explicit curves

Discharges `IsCoprime (W.Φ 3) (W.ΨSq 3)` for the Weierstrass model of note eq. (3.7)
over `ℚ(z)`, yielding an unconditional degree-nine statement via `finrank_mulThreeX`.

The Bézout pair is generated by the extended Euclidean algorithm over `ℚ(z)`, cleared of
denominators as `D = z⁴ · q₈(z)²`, and checked as an identity in `MvPolynomial (Fin 2) ℚ`
by `ring`. Since `ΨSq 3 = Ψ₃²`, coprimality with `Ψ₃` plus `IsCoprime.pow_right` yields the
claim for `ΨSq 3`.

The companion model (5.6) over `ℚ(t)(λ)` is not included here: the same method applies
(cleared witnesses are small — `U` of degree 3 and `V` of degree 8 in `X`, with common
denominator `5184 λ⁴ q₋² q₊²`), but was deprioritized after the degree-nine corollary for
(3.7) was obtained.
-/

set_option maxHeartbeats 800000

noncomputable section

open MvPolynomial
open scoped IntermediateField

namespace ExplicitUnirational

/-! ## Arithmetic surface over `ℚ(z)` (note (3.7)) -/

/-- Base field `ℚ(z)` for the model (3.7). -/
public abbrev KQ : Type := RatFunc ℚ

/-- The quartic `P(z)` of note eq. (3.5). -/
public noncomputable def noteP : KQ :=
  4 * RatFunc.X ^ 4 - 23 * RatFunc.X ^ 3 - 18 * RatFunc.X ^ 2 + RatFunc.X - 4

/-- The short Weierstrass model of note eq. (3.7) over `ℚ(z)`. -/
public noncomputable def noteCurveQ : WeierstrassCurve KQ where
  a₁ := 0
  a₂ := 0
  a₃ := 0
  a₄ := RatFunc.X ^ 2 * (3 - RatFunc.X)
  a₆ := (RatFunc.X / 4) * noteP

/-! ### Bézout certificate (`X 0 = z`, `X 1 =` elliptic `X`) -/

private noncomputable def psi3Mv : MvPolynomial (Fin 2) ℚ :=
  3 * (X 1) ^4
    - 6 * (X 0) ^3 * (X 1) ^2
    + 18 * (X 0) ^2 * (X 1) ^2
    + 12 * (X 0) ^5 * (X 1)
    - 69 * (X 0) ^4 * (X 1)
    - 54 * (X 0) ^3 * (X 1)
    + 3 * (X 0) ^2 * (X 1)
    - 12 * (X 0) * (X 1)
    - (X 0) ^6
    + 6 * (X 0) ^5
    - 9 * (X 0) ^4

private noncomputable def phi3Mv : MvPolynomial (Fin 2) ℚ :=
  (X 1) ^9
    + 12 * (X 0) ^3 * (X 1) ^7
    - 36 * (X 0) ^2 * (X 1) ^7
    - 96 * (X 0) ^5 * (X 1) ^6
    + 552 * (X 0) ^4 * (X 1) ^6
    + 432 * (X 0) ^3 * (X 1) ^6
    - 24 * (X 0) ^2 * (X 1) ^6
    + 96 * (X 0) * (X 1) ^6
    + 30 * (X 0) ^6 * (X 1) ^5
    - 180 * (X 0) ^5 * (X 1) ^5
    + 270 * (X 0) ^4 * (X 1) ^5
    + 24 * (X 0) ^8 * (X 1) ^4
    - 210 * (X 0) ^7 * (X 1) ^4
    + 306 * (X 0) ^6 * (X 1) ^4
    + 330 * (X 0) ^5 * (X 1) ^4
    - 42 * (X 0) ^4 * (X 1) ^4
    + 72 * (X 0) ^3 * (X 1) ^4
    + 48 * (X 0) ^10 * (X 1) ^3
    - 588 * (X 0) ^9 * (X 1) ^3
    + 1479 * (X 0) ^8 * (X 1) ^3
    + 1536 * (X 0) ^7 * (X 1) ^3
    + 1710 * (X 0) ^6 * (X 1) ^3
    + 444 * (X 0) ^5 * (X 1) ^3
    + 435 * (X 0) ^4 * (X 1) ^3
    - 24 * (X 0) ^3 * (X 1) ^3
    + 48 * (X 0) ^2 * (X 1) ^3
    + 48 * (X 0) ^11 * (X 1) ^2
    - 564 * (X 0) ^10 * (X 1) ^2
    + 1872 * (X 0) ^9 * (X 1) ^2
    - 1176 * (X 0) ^8 * (X 1) ^2
    - 2064 * (X 0) ^7 * (X 1) ^2
    + 396 * (X 0) ^6 * (X 1) ^2
    - 432 * (X 0) ^5 * (X 1) ^2
    - 96 * (X 0) ^13 * (X 1)
    + 1401 * (X 0) ^12 * (X 1)
    - 5730 * (X 0) ^11 * (X 1)
    + 2400 * (X 0) ^10 * (X 1)
    + 12600 * (X 0) ^9 * (X 1)
    + 4269 * (X 0) ^8 * (X 1)
    + 1794 * (X 0) ^7 * (X 1)
    + 2658 * (X 0) ^6 * (X 1)
    - 240 * (X 0) ^5 * (X 1)
    + 288 * (X 0) ^4 * (X 1)
    + 64 * (X 0) ^15
    - 1112 * (X 0) ^14
    + 5602 * (X 0) ^13
    - 2777 * (X 0) ^12
    - 24290 * (X 0) ^11
    - 19237 * (X 0) ^10
    - 9054 * (X 0) ^9
    - 8859 * (X 0) ^8
    - 3414 * (X 0) ^7
    - 671 * (X 0) ^6
    - 876 * (X 0) ^5
    + 48 * (X 0) ^4
    - 64 * (X 0) ^3

private noncomputable def bezoutUMv : MvPolynomial (Fin 2) ℚ :=
  756 * (X 1) ^3
    - 1620 * (X 0) ^3 * (X 1)
    + 4860 * (X 0) ^2 * (X 1)
    + 2916 * (X 0) ^5
    - 16767 * (X 0) ^4
    - 13122 * (X 0) ^3
    + 729 * (X 0) ^2
    - 2916 * (X 0)

private noncomputable def bezoutVMv : MvPolynomial (Fin 2) ℚ :=
  -252 * (X 1) ^8
    - 2988 * (X 0) ^3 * (X 1) ^6
    + 8964 * (X 0) ^2 * (X 1) ^6
    + 24228 * (X 0) ^5 * (X 1) ^5
    - 139311 * (X 0) ^4 * (X 1) ^5
    - 109026 * (X 0) ^3 * (X 1) ^5
    + 6057 * (X 0) ^2 * (X 1) ^5
    - 24228 * (X 0) * (X 1) ^5
    - 7140 * (X 0) ^6 * (X 1) ^4
    + 42840 * (X 0) ^5 * (X 1) ^4
    - 64260 * (X 0) ^4 * (X 1) ^4
    - 9144 * (X 0) ^8 * (X 1) ^3
    + 80010 * (X 0) ^7 * (X 1) ^3
    - 116586 * (X 0) ^6 * (X 1) ^3
    - 125730 * (X 0) ^5 * (X 1) ^3
    + 16002 * (X 0) ^4 * (X 1) ^3
    - 27432 * (X 0) ^3 * (X 1) ^3
    - 15696 * (X 0) ^10 * (X 1) ^2
    + 190500 * (X 0) ^9 * (X 1) ^2
    - 467649 * (X 0) ^8 * (X 1) ^2
    - 550224 * (X 0) ^7 * (X 1) ^2
    - 511218 * (X 0) ^6 * (X 1) ^2
    - 145188 * (X 0) ^5 * (X 1) ^2
    - 142245 * (X 0) ^4 * (X 1) ^2
    + 7848 * (X 0) ^3 * (X 1) ^2
    - 15696 * (X 0) ^2 * (X 1) ^2
    - 9948 * (X 0) ^11 * (X 1)
    + 116889 * (X 0) ^10 * (X 1)
    - 387972 * (X 0) ^9 * (X 1)
    + 243726 * (X 0) ^8 * (X 1)
    + 427764 * (X 0) ^7 * (X 1)
    - 82071 * (X 0) ^6 * (X 1)
    + 89532 * (X 0) ^5 * (X 1)
    + 31968 * (X 0) ^13
    - 467632 * (X 0) ^12
    + 1921278 * (X 0) ^11
    - 858546 * (X 0) ^10
    - 4077108 * (X 0) ^9
    - 1510596 * (X 0) ^8
    - 597402 * (X 0) ^7
    - 885114 * (X 0) ^6
    + 79920 * (X 0) ^5
    - 95904 * (X 0) ^4

private noncomputable def bezoutDMv : MvPolynomial (Fin 2) ℚ :=
  186624 * (X 0) ^20
    - 4347648 * (X 0) ^19
    + 34799968 * (X 0) ^18
    - 92402928 * (X 0) ^17
    - 82179495 * (X 0) ^16
    + 376575912 * (X 0) ^15
    + 581293692 * (X 0) ^14
    + 397021608 * (X 0) ^13
    + 325092150 * (X 0) ^12
    + 221014440 * (X 0) ^11
    + 81979452 * (X 0) ^10
    + 45682056 * (X 0) ^9
    + 20832633 * (X 0) ^8
    + 1761264 * (X 0) ^7
    + 3429216 * (X 0) ^6
    - 186624 * (X 0) ^5
    + 186624 * (X 0) ^4




private noncomputable def prePsi4Mv : MvPolynomial (Fin 2) ℚ :=
  2 * (X 1) ^ 6
    - 10 * (X 0) ^ 3 * (X 1) ^ 4
    + 30 * (X 0) ^ 2 * (X 1) ^ 4
    + 40 * (X 0) ^ 5 * (X 1) ^ 3
    - 230 * (X 0) ^ 4 * (X 1) ^ 3
    - 180 * (X 0) ^ 3 * (X 1) ^ 3
    + 10 * (X 0) ^ 2 * (X 1) ^ 3
    - 40 * (X 0) * (X 1) ^ 3
    - 10 * (X 0) ^ 6 * (X 1) ^ 2
    + 60 * (X 0) ^ 5 * (X 1) ^ 2
    - 90 * (X 0) ^ 4 * (X 1) ^ 2
    + 8 * (X 0) ^ 8 * (X 1)
    - 70 * (X 0) ^ 7 * (X 1)
    + 102 * (X 0) ^ 6 * (X 1)
    + 110 * (X 0) ^ 5 * (X 1)
    - 14 * (X 0) ^ 4 * (X 1)
    + 24 * (X 0) ^ 3 * (X 1)
    - 16 * (X 0) ^ 10
    + 186 * (X 0) ^ 9
    - 403 * (X 0) ^ 8
    - 782 * (X 0) ^ 7
    - 300 * (X 0) ^ 6
    - 148 * (X 0) ^ 5
    - 145 * (X 0) ^ 4
    + 8 * (X 0) ^ 3
    - 16 * (X 0) ^ 2

private noncomputable def psi2SqMv : MvPolynomial (Fin 2) ℚ :=
  4 * (X 1) ^ 3
    - 4 * (X 0) ^ 3 * (X 1)
    + 12 * (X 0) ^ 2 * (X 1)
    + 4 * (X 0) ^ 5
    - 23 * (X 0) ^ 4
    - 18 * (X 0) ^ 3
    + (X 0) ^ 2
    - 4 * (X 0)


/-- Abstract short-Weierstrass formula for `Φ₃` as a multivariate identity. -/
private theorem phi3Mv_formula :
    phi3Mv = (X 1) * psi3Mv ^ 2 - prePsi4Mv * psi2SqMv := by
  unfold phi3Mv psi3Mv prePsi4Mv psi2SqMv
  ring

private theorem bezout_identity_mv :
    bezoutUMv * phi3Mv + bezoutVMv * psi3Mv = bezoutDMv := by
  unfold bezoutUMv phi3Mv bezoutVMv psi3Mv bezoutDMv
  ring

private theorem bezoutDMv_ne_zero : bezoutDMv ≠ 0 := by
  intro h
  have h1 := congrArg (eval (![1, 0] : Fin 2 → ℚ)) h
  rw [map_zero, bezoutDMv] at h1
  simp at h1
  norm_num at h1

/-- Substitution `X 0 ↦ C z`, `X 1 ↦ X` into `ℚ(z)[X]`. -/
private noncomputable def sigmaQ : Fin 2 → Polynomial KQ :=
  ![Polynomial.C (RatFunc.X : KQ), Polynomial.X]

private noncomputable def evalQ : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] Polynomial KQ :=
  aeval sigmaQ

private theorem four_ne_zero_KQ : (4 : KQ) ≠ 0 := by norm_num

private theorem noteCurveQ_b₂ : noteCurveQ.b₂ = 0 := by
  simp [WeierstrassCurve.b₂, noteCurveQ]

private theorem noteCurveQ_b₄ : noteCurveQ.b₄ = 2 * noteCurveQ.a₄ := by
  simp [WeierstrassCurve.b₄, noteCurveQ]

private theorem noteCurveQ_b₆ : noteCurveQ.b₆ = 4 * noteCurveQ.a₆ := by
  simp [WeierstrassCurve.b₆, noteCurveQ]

private theorem noteCurveQ_b₈ : noteCurveQ.b₈ = -noteCurveQ.a₄ ^ 2 := by
  simp only [WeierstrassCurve.b₈, noteCurveQ]
  ring

/-- Expand `evalQ` of a multivariate certificate. -/
private theorem evalQ_expand (p : MvPolynomial (Fin 2) ℚ) :
    evalQ p = aeval (![Polynomial.C (RatFunc.X : KQ), Polynomial.X] : Fin 2 → Polynomial KQ) p :=
  rfl

private theorem noteCurveQ_Ψ₃_eq : noteCurveQ.Ψ₃ = evalQ psi3Mv := by
  -- Expand the certificate first (no divisions).
  have hrhs :
      evalQ psi3Mv =
        (3 : Polynomial KQ) * Polynomial.X ^ 4
          + Polynomial.C (-(6 : KQ) * RatFunc.X ^ 3 + 18 * RatFunc.X ^ 2) * Polynomial.X ^ 2
          + Polynomial.C
              ((12 : KQ) * RatFunc.X ^ 5 - 69 * RatFunc.X ^ 4 - 54 * RatFunc.X ^ 3
                + 3 * RatFunc.X ^ 2 - 12 * RatFunc.X) * Polynomial.X
          + Polynomial.C (-(RatFunc.X : KQ) ^ 6 + 6 * RatFunc.X ^ 5 - 9 * RatFunc.X ^ 4) := by
    unfold psi3Mv evalQ sigmaQ
    simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
      Matrix.cons_val_zero, Matrix.cons_val_one]
    ring
  rw [hrhs]
  -- Expand Mathlib's `Ψ₃` for the short model and clear the `/4` in `a₆`.
  rw [WeierstrassCurve.Ψ₃, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆, noteCurveQ_b₈]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  -- Pull scalar factors into `Polynomial.C` and drop zero terms.
  simp only [← map_ofNat (f := Polynomial.C), ← Polynomial.C_mul, Polynomial.C_0, zero_mul,
    add_zero]
  ring_nf

private theorem noteCurveQ_preΨ₄_eq : noteCurveQ.preΨ₄ = evalQ prePsi4Mv := by
  rw [WeierstrassCurve.preΨ₄, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆, noteCurveQ_b₈]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  unfold prePsi4Mv evalQ sigmaQ
  simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat, map_one,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  ring_nf
  simp only [Polynomial.C_0, mul_zero, zero_mul, add_zero, zero_add, sub_zero, neg_zero]

private theorem noteCurveQ_Ψ₂Sq_eq : noteCurveQ.Ψ₂Sq = evalQ psi2SqMv := by
  rw [WeierstrassCurve.Ψ₂Sq, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  unfold psi2SqMv evalQ sigmaQ
  simp only [map_add, map_sub, map_mul, map_pow, aeval_X, map_ofNat, map_one,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  ring_nf
  simp only [Polynomial.C_0, mul_zero, add_zero]

private theorem evalQ_X1 : evalQ (X 1) = Polynomial.X := by
  simp [evalQ, sigmaQ, aeval_X]

private theorem noteCurveQ_Φ_eq : noteCurveQ.Φ 3 = evalQ phi3Mv := by
  have hΦ : noteCurveQ.Φ 3 =
      Polynomial.X * noteCurveQ.Ψ₃ ^ 2 - noteCurveQ.preΨ₄ * noteCurveQ.Ψ₂Sq :=
    WeierstrassCurve.Φ_three (W := noteCurveQ)
  rw [hΦ, noteCurveQ_Ψ₃_eq, noteCurveQ_preΨ₄_eq, noteCurveQ_Ψ₂Sq_eq, phi3Mv_formula]
  simp only [map_sub, map_mul, map_pow, evalQ_X1]

private noncomputable def bezoutDQ : KQ :=
  186624 * RatFunc.X ^ 20 - 4347648 * RatFunc.X ^ 19 + 34799968 * RatFunc.X ^ 18
    - 92402928 * RatFunc.X ^ 17 - 82179495 * RatFunc.X ^ 16 + 376575912 * RatFunc.X ^ 15
    + 581293692 * RatFunc.X ^ 14 + 397021608 * RatFunc.X ^ 13 + 325092150 * RatFunc.X ^ 12
    + 221014440 * RatFunc.X ^ 11 + 81979452 * RatFunc.X ^ 10 + 45682056 * RatFunc.X ^ 9
    + 20832633 * RatFunc.X ^ 8 + 1761264 * RatFunc.X ^ 7 + 3429216 * RatFunc.X ^ 6
    - 186624 * RatFunc.X ^ 5 + 186624 * RatFunc.X ^ 4

private theorem evalQ_bezoutD : (evalQ bezoutDMv : Polynomial KQ) = Polynomial.C bezoutDQ := by
  unfold evalQ sigmaQ bezoutDMv bezoutDQ
  simp only [map_add, map_sub, map_mul, map_pow, aeval_X, map_ofNat, Matrix.cons_val_zero]

private theorem bezoutDQ_ne_zero : bezoutDQ ≠ 0 := by
  -- Image of a nonzero element of `ℚ[z]` under the injective map into `ℚ(z)`.
  set p : Polynomial ℚ :=
    186624 * Polynomial.X ^ 20 - 4347648 * Polynomial.X ^ 19 + 34799968 * Polynomial.X ^ 18
      - 92402928 * Polynomial.X ^ 17 - 82179495 * Polynomial.X ^ 16
      + 376575912 * Polynomial.X ^ 15 + 581293692 * Polynomial.X ^ 14
      + 397021608 * Polynomial.X ^ 13 + 325092150 * Polynomial.X ^ 12
      + 221014440 * Polynomial.X ^ 11 + 81979452 * Polynomial.X ^ 10
      + 45682056 * Polynomial.X ^ 9 + 20832633 * Polynomial.X ^ 8
      + 1761264 * Polynomial.X ^ 7 + 3429216 * Polynomial.X ^ 6
      - 186624 * Polynomial.X ^ 5 + 186624 * Polynomial.X ^ 4 with hp_def
  have h20 : p.coeff 20 = (186624 : ℚ) := by
    simp [p, Polynomial.coeff_X_pow]
  have hp : p ≠ 0 := fun h =>
    (by norm_num : (186624 : ℚ) ≠ 0) (h20 ▸ congrArg (fun q : Polynomial ℚ => q.coeff 20) h)
  have h : bezoutDQ = algebraMap (Polynomial ℚ) KQ p := by
    simp only [bezoutDQ, p, map_add, map_sub, map_mul, map_pow, map_ofNat, RatFunc.algebraMap_X]
  rw [h]
  simpa [map_zero] using (FaithfulSMul.algebraMap_injective (Polynomial ℚ) KQ).ne hp

private theorem isCoprime_Φ_Ψ₃_noteCurveQ :
    IsCoprime (noteCurveQ.Φ 3) noteCurveQ.Ψ₃ := by
  rw [noteCurveQ_Φ_eq, noteCurveQ_Ψ₃_eq]
  refine ⟨(evalQ bezoutUMv) * Polynomial.C bezoutDQ⁻¹,
    (evalQ bezoutVMv) * Polynomial.C bezoutDQ⁻¹, ?_⟩
  have hid :
      (evalQ bezoutUMv) * (evalQ phi3Mv) + (evalQ bezoutVMv) * (evalQ psi3Mv)
        = evalQ bezoutDMv := by
    simpa [← map_mul, ← map_add] using
      congrArg (AlgHom.toRingHom evalQ) bezout_identity_mv
  have hD : bezoutDQ ≠ 0 := bezoutDQ_ne_zero
  calc
    (evalQ bezoutUMv) * Polynomial.C bezoutDQ⁻¹ * (evalQ phi3Mv)
        + (evalQ bezoutVMv) * Polynomial.C bezoutDQ⁻¹ * (evalQ psi3Mv)
      = Polynomial.C bezoutDQ⁻¹
          * ((evalQ bezoutUMv) * (evalQ phi3Mv) + (evalQ bezoutVMv) * (evalQ psi3Mv)) := by
        ring
    _ = Polynomial.C bezoutDQ⁻¹ * evalQ bezoutDMv := by rw [hid]
    _ = Polynomial.C bezoutDQ⁻¹ * Polynomial.C bezoutDQ := by rw [evalQ_bezoutD]
    _ = Polynomial.C (bezoutDQ⁻¹ * bezoutDQ) := by rw [← Polynomial.C_mul]
    _ = Polynomial.C 1 := by rw [inv_mul_cancel₀ hD]
    _ = 1 := by simp

/-- **Coprimality of `Φ₃` and `ΨSq₃` for the model (3.7).** -/
public theorem isCoprime_Φ_ΨSq_noteCurveQ :
    IsCoprime (noteCurveQ.Φ 3) (noteCurveQ.ΨSq 3) := by
  simpa [WeierstrassCurve.ΨSq_three] using
    (isCoprime_Φ_Ψ₃_noteCurveQ.pow_right (n := 2))

private theorem three_ne_zero_KQ : (3 : KQ) ≠ 0 := by
  exact_mod_cast (three_ne_zero : (3 : ℚ) ≠ 0)

/-- **Unconditional degree-nine statement for the model (3.7).**

The `x`-line over `ℚ(z)` is a degree-exactly-`9` extension of the subfield generated by
`x ∘ [3]`. -/
public theorem finrank_mulThreeX_noteCurveQ :
    Module.finrank KQ⟮mulThreeX noteCurveQ⟯ (RatFunc KQ) = 9 :=
  finrank_mulThreeX noteCurveQ three_ne_zero_KQ isCoprime_Φ_ΨSq_noteCurveQ

/-! ## Axiom audit -/

#print axioms isCoprime_Φ_ΨSq_noteCurveQ
#print axioms finrank_mulThreeX_noteCurveQ

end ExplicitUnirational
