/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import ExplicitUnirational.FunctionField.MulThree
public import Mathlib.FieldTheory.RatFunc.AsPolynomial
public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.Tactic.Ring
public import Mathlib.Tactic.NormNum

/-!
# Coprimality certificates for `Φ₃` and `ΨSq₃` on the explicit curves of [CLOP §4.1], [CLOP §4.2]

Discharges `IsCoprime (W.Φ 3) (W.ΨSq 3)` for the Weierstrass model of [CLOP §4.1]
(the equation for `J_η`) over `ℚ(z)`, yielding an unconditional degree-nine statement
via `finrank_mulThreeX`.

The Bézout pair is generated by the extended Euclidean algorithm over `ℚ(z)`, cleared of
denominators as `D = z⁴ · q₈(z)²`, and checked as an identity in `MvPolynomial (Fin 2) ℚ`
by `ring`. Since `ΨSq 3 = Ψ₃²`, coprimality with `Ψ₃` plus `IsCoprime.pow_right` yields the
claim for `ΨSq 3`.

Also discharges the same coprimality for the companion model of [CLOP §4.2] (the equation
for `J_η`) over `ℚ(t)(λ)`,
yielding the unconditional `finrank_mulThreeX_noteCurveCt = 9`. The Bézout pair (degrees 3 and 8
in the elliptic variable) is cleared over `ℚ[t, λ]` and checked by `ring` in
`MvPolynomial (Fin 3) ℚ`; nonvanishing of the denominator follows by injectivity of
`ℚ(t)[λ] → ℚ(t)(λ)`.
-/

set_option maxHeartbeats 8000000
set_option maxRecDepth 10000

noncomputable section

open MvPolynomial
open scoped IntermediateField

namespace ExplicitUnirational

/-! ## Arithmetic surface over `ℚ(z)` (the model of [CLOP §4.1]) -/

/-- Base field `ℚ(z)` for the model of [CLOP §4.1] (the equation for `J_η`). -/
public abbrev KQ : Type := RatFunc ℚ

/-- The quartic `P(z)` of [CLOP §4.1] — the quartic factor of `c₆(g)`. -/
public noncomputable def noteP : KQ :=
  4 * RatFunc.X ^ 4 - 23 * RatFunc.X ^ 3 - 18 * RatFunc.X ^ 2 + RatFunc.X - 4

/-- The short Weierstrass model of [CLOP §4.1] (the equation for `J_η`) over `ℚ(z)`. -/
public noncomputable def noteCurveQ : WeierstrassCurve KQ where
  a₁ := 0
  a₂ := 0
  a₃ := 0
  a₄ := RatFunc.X ^ 2 * (3 - RatFunc.X)
  a₆ := (RatFunc.X / 4) * noteP

/-! ### Bézout certificate (`X 0 = z`, `X 1 =` elliptic `X`) -/

private noncomputable def psi3Mv : MvPolynomial (Fin 2) ℚ :=
  3 * (X 1) ^4
    - 6 * (X 0) ^3 * (X 1) ^2
    + 18 * (X 0) ^2 * (X 1) ^2
    + 12 * (X 0) ^5 * (X 1)
    - 69 * (X 0) ^4 * (X 1)
    - 54 * (X 0) ^3 * (X 1)
    + 3 * (X 0) ^2 * (X 1)
    - 12 * (X 0) * (X 1)
    - (X 0) ^6
    + 6 * (X 0) ^5
    - 9 * (X 0) ^4

private noncomputable def phi3Mv : MvPolynomial (Fin 2) ℚ :=
  (X 1) ^9
    + 12 * (X 0) ^3 * (X 1) ^7
    - 36 * (X 0) ^2 * (X 1) ^7
    - 96 * (X 0) ^5 * (X 1) ^6
    + 552 * (X 0) ^4 * (X 1) ^6
    + 432 * (X 0) ^3 * (X 1) ^6
    - 24 * (X 0) ^2 * (X 1) ^6
    + 96 * (X 0) * (X 1) ^6
    + 30 * (X 0) ^6 * (X 1) ^5
    - 180 * (X 0) ^5 * (X 1) ^5
    + 270 * (X 0) ^4 * (X 1) ^5
    + 24 * (X 0) ^8 * (X 1) ^4
    - 210 * (X 0) ^7 * (X 1) ^4
    + 306 * (X 0) ^6 * (X 1) ^4
    + 330 * (X 0) ^5 * (X 1) ^4
    - 42 * (X 0) ^4 * (X 1) ^4
    + 72 * (X 0) ^3 * (X 1) ^4
    + 48 * (X 0) ^10 * (X 1) ^3
    - 588 * (X 0) ^9 * (X 1) ^3
    + 1479 * (X 0) ^8 * (X 1) ^3
    + 1536 * (X 0) ^7 * (X 1) ^3
    + 1710 * (X 0) ^6 * (X 1) ^3
    + 444 * (X 0) ^5 * (X 1) ^3
    + 435 * (X 0) ^4 * (X 1) ^3
    - 24 * (X 0) ^3 * (X 1) ^3
    + 48 * (X 0) ^2 * (X 1) ^3
    + 48 * (X 0) ^11 * (X 1) ^2
    - 564 * (X 0) ^10 * (X 1) ^2
    + 1872 * (X 0) ^9 * (X 1) ^2
    - 1176 * (X 0) ^8 * (X 1) ^2
    - 2064 * (X 0) ^7 * (X 1) ^2
    + 396 * (X 0) ^6 * (X 1) ^2
    - 432 * (X 0) ^5 * (X 1) ^2
    - 96 * (X 0) ^13 * (X 1)
    + 1401 * (X 0) ^12 * (X 1)
    - 5730 * (X 0) ^11 * (X 1)
    + 2400 * (X 0) ^10 * (X 1)
    + 12600 * (X 0) ^9 * (X 1)
    + 4269 * (X 0) ^8 * (X 1)
    + 1794 * (X 0) ^7 * (X 1)
    + 2658 * (X 0) ^6 * (X 1)
    - 240 * (X 0) ^5 * (X 1)
    + 288 * (X 0) ^4 * (X 1)
    + 64 * (X 0) ^15
    - 1112 * (X 0) ^14
    + 5602 * (X 0) ^13
    - 2777 * (X 0) ^12
    - 24290 * (X 0) ^11
    - 19237 * (X 0) ^10
    - 9054 * (X 0) ^9
    - 8859 * (X 0) ^8
    - 3414 * (X 0) ^7
    - 671 * (X 0) ^6
    - 876 * (X 0) ^5
    + 48 * (X 0) ^4
    - 64 * (X 0) ^3

private noncomputable def bezoutUMv : MvPolynomial (Fin 2) ℚ :=
  756 * (X 1) ^3
    - 1620 * (X 0) ^3 * (X 1)
    + 4860 * (X 0) ^2 * (X 1)
    + 2916 * (X 0) ^5
    - 16767 * (X 0) ^4
    - 13122 * (X 0) ^3
    + 729 * (X 0) ^2
    - 2916 * (X 0)

private noncomputable def bezoutVMv : MvPolynomial (Fin 2) ℚ :=
  -252 * (X 1) ^8
    - 2988 * (X 0) ^3 * (X 1) ^6
    + 8964 * (X 0) ^2 * (X 1) ^6
    + 24228 * (X 0) ^5 * (X 1) ^5
    - 139311 * (X 0) ^4 * (X 1) ^5
    - 109026 * (X 0) ^3 * (X 1) ^5
    + 6057 * (X 0) ^2 * (X 1) ^5
    - 24228 * (X 0) * (X 1) ^5
    - 7140 * (X 0) ^6 * (X 1) ^4
    + 42840 * (X 0) ^5 * (X 1) ^4
    - 64260 * (X 0) ^4 * (X 1) ^4
    - 9144 * (X 0) ^8 * (X 1) ^3
    + 80010 * (X 0) ^7 * (X 1) ^3
    - 116586 * (X 0) ^6 * (X 1) ^3
    - 125730 * (X 0) ^5 * (X 1) ^3
    + 16002 * (X 0) ^4 * (X 1) ^3
    - 27432 * (X 0) ^3 * (X 1) ^3
    - 15696 * (X 0) ^10 * (X 1) ^2
    + 190500 * (X 0) ^9 * (X 1) ^2
    - 467649 * (X 0) ^8 * (X 1) ^2
    - 550224 * (X 0) ^7 * (X 1) ^2
    - 511218 * (X 0) ^6 * (X 1) ^2
    - 145188 * (X 0) ^5 * (X 1) ^2
    - 142245 * (X 0) ^4 * (X 1) ^2
    + 7848 * (X 0) ^3 * (X 1) ^2
    - 15696 * (X 0) ^2 * (X 1) ^2
    - 9948 * (X 0) ^11 * (X 1)
    + 116889 * (X 0) ^10 * (X 1)
    - 387972 * (X 0) ^9 * (X 1)
    + 243726 * (X 0) ^8 * (X 1)
    + 427764 * (X 0) ^7 * (X 1)
    - 82071 * (X 0) ^6 * (X 1)
    + 89532 * (X 0) ^5 * (X 1)
    + 31968 * (X 0) ^13
    - 467632 * (X 0) ^12
    + 1921278 * (X 0) ^11
    - 858546 * (X 0) ^10
    - 4077108 * (X 0) ^9
    - 1510596 * (X 0) ^8
    - 597402 * (X 0) ^7
    - 885114 * (X 0) ^6
    + 79920 * (X 0) ^5
    - 95904 * (X 0) ^4

private noncomputable def bezoutDMv : MvPolynomial (Fin 2) ℚ :=
  186624 * (X 0) ^20
    - 4347648 * (X 0) ^19
    + 34799968 * (X 0) ^18
    - 92402928 * (X 0) ^17
    - 82179495 * (X 0) ^16
    + 376575912 * (X 0) ^15
    + 581293692 * (X 0) ^14
    + 397021608 * (X 0) ^13
    + 325092150 * (X 0) ^12
    + 221014440 * (X 0) ^11
    + 81979452 * (X 0) ^10
    + 45682056 * (X 0) ^9
    + 20832633 * (X 0) ^8
    + 1761264 * (X 0) ^7
    + 3429216 * (X 0) ^6
    - 186624 * (X 0) ^5
    + 186624 * (X 0) ^4




private noncomputable def prePsi4Mv : MvPolynomial (Fin 2) ℚ :=
  2 * (X 1) ^ 6
    - 10 * (X 0) ^ 3 * (X 1) ^ 4
    + 30 * (X 0) ^ 2 * (X 1) ^ 4
    + 40 * (X 0) ^ 5 * (X 1) ^ 3
    - 230 * (X 0) ^ 4 * (X 1) ^ 3
    - 180 * (X 0) ^ 3 * (X 1) ^ 3
    + 10 * (X 0) ^ 2 * (X 1) ^ 3
    - 40 * (X 0) * (X 1) ^ 3
    - 10 * (X 0) ^ 6 * (X 1) ^ 2
    + 60 * (X 0) ^ 5 * (X 1) ^ 2
    - 90 * (X 0) ^ 4 * (X 1) ^ 2
    + 8 * (X 0) ^ 8 * (X 1)
    - 70 * (X 0) ^ 7 * (X 1)
    + 102 * (X 0) ^ 6 * (X 1)
    + 110 * (X 0) ^ 5 * (X 1)
    - 14 * (X 0) ^ 4 * (X 1)
    + 24 * (X 0) ^ 3 * (X 1)
    - 16 * (X 0) ^ 10
    + 186 * (X 0) ^ 9
    - 403 * (X 0) ^ 8
    - 782 * (X 0) ^ 7
    - 300 * (X 0) ^ 6
    - 148 * (X 0) ^ 5
    - 145 * (X 0) ^ 4
    + 8 * (X 0) ^ 3
    - 16 * (X 0) ^ 2

private noncomputable def psi2SqMv : MvPolynomial (Fin 2) ℚ :=
  4 * (X 1) ^ 3
    - 4 * (X 0) ^ 3 * (X 1)
    + 12 * (X 0) ^ 2 * (X 1)
    + 4 * (X 0) ^ 5
    - 23 * (X 0) ^ 4
    - 18 * (X 0) ^ 3
    + (X 0) ^ 2
    - 4 * (X 0)


/-- Abstract short-Weierstrass formula for `Φ₃` as a multivariate identity. -/
private theorem phi3Mv_formula :
    phi3Mv = (X 1) * psi3Mv ^ 2 - prePsi4Mv * psi2SqMv := by
  unfold phi3Mv psi3Mv prePsi4Mv psi2SqMv
  ring

private theorem bezout_identity_mv :
    bezoutUMv * phi3Mv + bezoutVMv * psi3Mv = bezoutDMv := by
  unfold bezoutUMv phi3Mv bezoutVMv psi3Mv bezoutDMv
  ring

private theorem bezoutDMv_ne_zero : bezoutDMv ≠ 0 := by
  intro h
  have h1 := congrArg (eval (![1, 0] : Fin 2 → ℚ)) h
  rw [map_zero, bezoutDMv] at h1
  simp at h1
  norm_num at h1

/-- Substitution `X 0 ↦ C z`, `X 1 ↦ X` into `ℚ(z)[X]`. -/
private noncomputable def sigmaQ : Fin 2 → Polynomial KQ :=
  ![Polynomial.C (RatFunc.X : KQ), Polynomial.X]

private noncomputable def evalQ : MvPolynomial (Fin 2) ℚ →ₐ[ℚ] Polynomial KQ :=
  aeval sigmaQ

private theorem four_ne_zero_KQ : (4 : KQ) ≠ 0 := by norm_num

private theorem noteCurveQ_b₂ : noteCurveQ.b₂ = 0 := by
  simp [WeierstrassCurve.b₂, noteCurveQ]

private theorem noteCurveQ_b₄ : noteCurveQ.b₄ = 2 * noteCurveQ.a₄ := by
  simp [WeierstrassCurve.b₄, noteCurveQ]

private theorem noteCurveQ_b₆ : noteCurveQ.b₆ = 4 * noteCurveQ.a₆ := by
  simp [WeierstrassCurve.b₆, noteCurveQ]

private theorem noteCurveQ_b₈ : noteCurveQ.b₈ = -noteCurveQ.a₄ ^ 2 := by
  simp only [WeierstrassCurve.b₈, noteCurveQ]
  ring

/-- Expand `evalQ` of a multivariate certificate. -/
private theorem evalQ_expand (p : MvPolynomial (Fin 2) ℚ) :
    evalQ p = aeval (![Polynomial.C (RatFunc.X : KQ), Polynomial.X] : Fin 2 → Polynomial KQ) p :=
  rfl

private theorem noteCurveQ_Ψ₃_eq : noteCurveQ.Ψ₃ = evalQ psi3Mv := by
  -- Expand the certificate first (no divisions).
  have hrhs :
      evalQ psi3Mv =
        (3 : Polynomial KQ) * Polynomial.X ^ 4
          + Polynomial.C (-(6 : KQ) * RatFunc.X ^ 3 + 18 * RatFunc.X ^ 2) * Polynomial.X ^ 2
          + Polynomial.C
              ((12 : KQ) * RatFunc.X ^ 5 - 69 * RatFunc.X ^ 4 - 54 * RatFunc.X ^ 3
                + 3 * RatFunc.X ^ 2 - 12 * RatFunc.X) * Polynomial.X
          + Polynomial.C (-(RatFunc.X : KQ) ^ 6 + 6 * RatFunc.X ^ 5 - 9 * RatFunc.X ^ 4) := by
    unfold psi3Mv evalQ sigmaQ
    simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
      Matrix.cons_val_zero, Matrix.cons_val_one]
    ring
  rw [hrhs]
  -- Expand Mathlib's `Ψ₃` for the short model and clear the `/4` in `a₆`.
  rw [WeierstrassCurve.Ψ₃, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆, noteCurveQ_b₈]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  -- Pull scalar factors into `Polynomial.C` and drop zero terms.
  simp only [← map_ofNat (f := Polynomial.C), ← Polynomial.C_mul, Polynomial.C_0, zero_mul,
    add_zero]
  ring_nf

private theorem noteCurveQ_preΨ₄_eq : noteCurveQ.preΨ₄ = evalQ prePsi4Mv := by
  rw [WeierstrassCurve.preΨ₄, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆, noteCurveQ_b₈]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  unfold prePsi4Mv evalQ sigmaQ
  simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat, map_one,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  ring_nf
  simp only [Polynomial.C_0, mul_zero, zero_mul, add_zero, zero_add, sub_zero, neg_zero]

private theorem noteCurveQ_Ψ₂Sq_eq : noteCurveQ.Ψ₂Sq = evalQ psi2SqMv := by
  rw [WeierstrassCurve.Ψ₂Sq, noteCurveQ_b₂, noteCurveQ_b₄, noteCurveQ_b₆]
  simp only [noteCurveQ, noteP]
  field_simp [four_ne_zero_KQ]
  unfold psi2SqMv evalQ sigmaQ
  simp only [map_add, map_sub, map_mul, map_pow, aeval_X, map_ofNat, map_one,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  ring_nf
  simp only [Polynomial.C_0, mul_zero, add_zero]

private theorem evalQ_X1 : evalQ (X 1) = Polynomial.X := by
  simp [evalQ, sigmaQ, aeval_X]

private theorem noteCurveQ_Φ_eq : noteCurveQ.Φ 3 = evalQ phi3Mv := by
  have hΦ : noteCurveQ.Φ 3 =
      Polynomial.X * noteCurveQ.Ψ₃ ^ 2 - noteCurveQ.preΨ₄ * noteCurveQ.Ψ₂Sq :=
    WeierstrassCurve.Φ_three (W := noteCurveQ)
  rw [hΦ, noteCurveQ_Ψ₃_eq, noteCurveQ_preΨ₄_eq, noteCurveQ_Ψ₂Sq_eq, phi3Mv_formula]
  simp only [map_sub, map_mul, map_pow, evalQ_X1]

private noncomputable def bezoutDQ : KQ :=
  186624 * RatFunc.X ^ 20 - 4347648 * RatFunc.X ^ 19 + 34799968 * RatFunc.X ^ 18
    - 92402928 * RatFunc.X ^ 17 - 82179495 * RatFunc.X ^ 16 + 376575912 * RatFunc.X ^ 15
    + 581293692 * RatFunc.X ^ 14 + 397021608 * RatFunc.X ^ 13 + 325092150 * RatFunc.X ^ 12
    + 221014440 * RatFunc.X ^ 11 + 81979452 * RatFunc.X ^ 10 + 45682056 * RatFunc.X ^ 9
    + 20832633 * RatFunc.X ^ 8 + 1761264 * RatFunc.X ^ 7 + 3429216 * RatFunc.X ^ 6
    - 186624 * RatFunc.X ^ 5 + 186624 * RatFunc.X ^ 4

private theorem evalQ_bezoutD : (evalQ bezoutDMv : Polynomial KQ) = Polynomial.C bezoutDQ := by
  unfold evalQ sigmaQ bezoutDMv bezoutDQ
  simp only [map_add, map_sub, map_mul, map_pow, aeval_X, map_ofNat, Matrix.cons_val_zero]

private theorem bezoutDQ_ne_zero : bezoutDQ ≠ 0 := by
  -- Image of a nonzero element of `ℚ[z]` under the injective map into `ℚ(z)`.
  set p : Polynomial ℚ :=
    186624 * Polynomial.X ^ 20 - 4347648 * Polynomial.X ^ 19 + 34799968 * Polynomial.X ^ 18
      - 92402928 * Polynomial.X ^ 17 - 82179495 * Polynomial.X ^ 16
      + 376575912 * Polynomial.X ^ 15 + 581293692 * Polynomial.X ^ 14
      + 397021608 * Polynomial.X ^ 13 + 325092150 * Polynomial.X ^ 12
      + 221014440 * Polynomial.X ^ 11 + 81979452 * Polynomial.X ^ 10
      + 45682056 * Polynomial.X ^ 9 + 20832633 * Polynomial.X ^ 8
      + 1761264 * Polynomial.X ^ 7 + 3429216 * Polynomial.X ^ 6
      - 186624 * Polynomial.X ^ 5 + 186624 * Polynomial.X ^ 4 with hp_def
  have h20 : p.coeff 20 = (186624 : ℚ) := by
    simp [p, Polynomial.coeff_X_pow]
  have hp : p ≠ 0 := fun h =>
    (by norm_num : (186624 : ℚ) ≠ 0) (h20 ▸ congrArg (fun q : Polynomial ℚ => q.coeff 20) h)
  have h : bezoutDQ = algebraMap (Polynomial ℚ) KQ p := by
    simp only [bezoutDQ, p, map_add, map_sub, map_mul, map_pow, map_ofNat, RatFunc.algebraMap_X]
  rw [h]
  simpa [map_zero] using (FaithfulSMul.algebraMap_injective (Polynomial ℚ) KQ).ne hp

private theorem isCoprime_Φ_Ψ₃_noteCurveQ :
    IsCoprime (noteCurveQ.Φ 3) noteCurveQ.Ψ₃ := by
  rw [noteCurveQ_Φ_eq, noteCurveQ_Ψ₃_eq]
  refine ⟨(evalQ bezoutUMv) * Polynomial.C bezoutDQ⁻¹,
    (evalQ bezoutVMv) * Polynomial.C bezoutDQ⁻¹, ?_⟩
  have hid :
      (evalQ bezoutUMv) * (evalQ phi3Mv) + (evalQ bezoutVMv) * (evalQ psi3Mv)
        = evalQ bezoutDMv := by
    simpa [← map_mul, ← map_add] using
      congrArg (AlgHom.toRingHom evalQ) bezout_identity_mv
  have hD : bezoutDQ ≠ 0 := bezoutDQ_ne_zero
  calc
    (evalQ bezoutUMv) * Polynomial.C bezoutDQ⁻¹ * (evalQ phi3Mv)
        + (evalQ bezoutVMv) * Polynomial.C bezoutDQ⁻¹ * (evalQ psi3Mv)
      = Polynomial.C bezoutDQ⁻¹
          * ((evalQ bezoutUMv) * (evalQ phi3Mv) + (evalQ bezoutVMv) * (evalQ psi3Mv)) := by
        ring
    _ = Polynomial.C bezoutDQ⁻¹ * evalQ bezoutDMv := by rw [hid]
    _ = Polynomial.C bezoutDQ⁻¹ * Polynomial.C bezoutDQ := by rw [evalQ_bezoutD]
    _ = Polynomial.C (bezoutDQ⁻¹ * bezoutDQ) := by rw [← Polynomial.C_mul]
    _ = Polynomial.C 1 := by rw [inv_mul_cancel₀ hD]
    _ = 1 := by simp

/-- **Coprimality of `Φ₃` and `ΨSq₃` for the model of [CLOP §4.1].** -/
public theorem isCoprime_Φ_ΨSq_noteCurveQ :
    IsCoprime (noteCurveQ.Φ 3) (noteCurveQ.ΨSq 3) := by
  simpa [WeierstrassCurve.ΨSq_three] using
    (isCoprime_Φ_Ψ₃_noteCurveQ.pow_right (n := 2))

private theorem three_ne_zero_KQ : (3 : KQ) ≠ 0 := by
  exact_mod_cast (three_ne_zero : (3 : ℚ) ≠ 0)

/-- **Unconditional degree-nine statement for the model of [CLOP §4.1].**

The `x`-line over `ℚ(z)` is a degree-exactly-`9` extension of the subfield generated by
`x ∘ [3]`. -/
public theorem finrank_mulThreeX_noteCurveQ :
    Module.finrank KQ⟮mulThreeX noteCurveQ⟯ (RatFunc KQ) = 9 :=
  finrank_mulThreeX noteCurveQ three_ne_zero_KQ isCoprime_Φ_ΨSq_noteCurveQ





/-! ## Arithmetic surface over `ℚ(t)(λ)` (the model of [CLOP §4.2]) -/

/-- Base field `ℚ(t)` for the model of [CLOP §4.2] (the equation for `J_η`). -/
public abbrev Kt : Type := RatFunc ℚ

/-- Base field `ℚ(t)(λ)` for the model of [CLOP §4.2]. Nested `RatFunc` elaborates cleanly and
keeps the parameter `t` and the pencil coordinate `λ` as separate indeterminates. -/
public abbrev KCt : Type := RatFunc Kt

/-- The parameter `t ∈ ℚ(t)` lifted to `ℚ(t)(λ)`. -/
public noncomputable def noteT : KCt :=
  algebraMap Kt KCt (RatFunc.X : Kt)

/-- The short Weierstrass model of [CLOP §4.2] (the equation for `J_η`) over `ℚ(t)(λ)`.
`y² = x³ - 3 λ² x - λ⁵ - 27 t² λ⁴ - λ`. -/
public noncomputable def noteCurveCt : WeierstrassCurve KCt where
  a₁ := 0
  a₂ := 0
  a₃ := 0
  a₄ := -3 * RatFunc.X ^ 2
  a₆ := -RatFunc.X ^ 5 - 27 * noteT ^ 2 * RatFunc.X ^ 4 - RatFunc.X

/-! ### Bézout certificate (`X 0 = t`, `X 1 = λ`, `X 2 =` elliptic `X`)

The cleared denominator is `5184 · λ⁴ · q₋(λ)² · q₊(λ)²`, where
`q_±(λ) = λ⁴ + 27t²λ³ ± 2λ² + 1` are the quartic factors of the discriminant
(not displayed in [CLOP]). -/

private noncomputable def psi3MvCt : MvPolynomial (Fin 3) ℚ :=
  3 * (X 2) ^4
    - 18 * (X 1) ^2 * (X 2) ^2
    - 12 * (X 1) ^5 * (X 2)
    - 324 * (X 0) ^2 * (X 1) ^4 * (X 2)
    - 12 * (X 1) * (X 2)
    - 9 * (X 1) ^4
private noncomputable def phi3MvCt : MvPolynomial (Fin 3) ℚ :=
  (X 2) ^9
    + 36 * (X 1) ^2 * (X 2) ^7
    + 96 * (X 1) ^5 * (X 2) ^6
    + 2592 * (X 0) ^2 * (X 1) ^4 * (X 2) ^6
    + 96 * (X 1) * (X 2) ^6
    + 270 * (X 1) ^4 * (X 2) ^5
    - 72 * (X 1) ^7 * (X 2) ^4
    - 1944 * (X 0) ^2 * (X 1) ^6 * (X 2) ^4
    - 72 * (X 1) ^3 * (X 2) ^4
    + 48 * (X 1) ^10 * (X 2) ^3
    + 2592 * (X 0) ^2 * (X 1) ^9 * (X 2) ^3
    + 34992 * (X 0) ^4 * (X 1) ^8 * (X 2) ^3
    - 876 * (X 1) ^6 * (X 2) ^3
    + 2592 * (X 0) ^2 * (X 1) ^5 * (X 2) ^3
    + 48 * (X 1) ^2 * (X 2) ^3
    - 432 * (X 1) ^9 * (X 2) ^2
    - 11664 * (X 0) ^2 * (X 1) ^8 * (X 2) ^2
    - 432 * (X 1) ^5 * (X 2) ^2
    - 288 * (X 1) ^12 * (X 2)
    - 15552 * (X 0) ^2 * (X 1) ^11 * (X 2)
    - 209952 * (X 0) ^4 * (X 1) ^10 * (X 2)
    + 153 * (X 1) ^8 * (X 2)
    - 15552 * (X 0) ^2 * (X 1) ^7 * (X 2)
    - 288 * (X 1) ^4 * (X 2)
    - 64 * (X 1) ^15
    - 5184 * (X 0) ^2 * (X 1) ^14
    - 139968 * (X 0) ^4 * (X 1) ^13
    - 1259712 * (X 0) ^6 * (X 1) ^12
    + 24 * (X 1) ^11
    - 4536 * (X 0) ^2 * (X 1) ^10
    - 139968 * (X 0) ^4 * (X 1) ^9
    + 24 * (X 1) ^7
    - 5184 * (X 0) ^2 * (X 1) ^6
    - 64 * (X 1) ^3
private noncomputable def prePsi4MvCt : MvPolynomial (Fin 3) ℚ :=
  2 * (X 2) ^6
    - 30 * (X 1) ^2 * (X 2) ^4
    - 40 * (X 1) ^5 * (X 2) ^3
    - 1080 * (X 0) ^2 * (X 1) ^4 * (X 2) ^3
    - 40 * (X 1) * (X 2) ^3
    - 90 * (X 1) ^4 * (X 2) ^2
    - 24 * (X 1) ^7 * (X 2)
    - 648 * (X 0) ^2 * (X 1) ^6 * (X 2)
    - 24 * (X 1) ^3 * (X 2)
    - 16 * (X 1) ^10
    - 864 * (X 0) ^2 * (X 1) ^9
    - 11664 * (X 0) ^4 * (X 1) ^8
    + 22 * (X 1) ^6
    - 864 * (X 0) ^2 * (X 1) ^5
    - 16 * (X 1) ^2
private noncomputable def psi2SqMvCt : MvPolynomial (Fin 3) ℚ :=
  4 * (X 2) ^3
    - 12 * (X 1) ^2 * (X 2)
    - 4 * (X 1) ^5
    - 108 * (X 0) ^2 * (X 1) ^4
    - 4 * (X 1)
private noncomputable def bezoutUMvCt : MvPolynomial (Fin 3) ℚ :=
  21 * (X 2) ^3
    - 135 * (X 1) ^2 * (X 2)
    - 81 * (X 1) ^5
    - 2187 * (X 0) ^2 * (X 1) ^4
    - 81 * (X 1)
private noncomputable def bezoutVMvCt : MvPolynomial (Fin 3) ℚ :=
  - 7 * (X 2) ^8
    - 249 * (X 1) ^2 * (X 2) ^6
    - 673 * (X 1) ^5 * (X 2) ^5
    - 18171 * (X 0) ^2 * (X 1) ^4 * (X 2) ^5
    - 673 * (X 1) * (X 2) ^5
    - 1785 * (X 1) ^4 * (X 2) ^4
    + 762 * (X 1) ^7 * (X 2) ^3
    + 20574 * (X 0) ^2 * (X 1) ^6 * (X 2) ^3
    + 762 * (X 1) ^3 * (X 2) ^3
    - 436 * (X 1) ^10 * (X 2) ^2
    - 23544 * (X 0) ^2 * (X 1) ^9 * (X 2) ^2
    - 317844 * (X 0) ^4 * (X 1) ^8 * (X 2) ^2
    + 6625 * (X 1) ^6 * (X 2) ^2
    - 23544 * (X 0) ^2 * (X 1) ^5 * (X 2) ^2
    - 436 * (X 1) ^2 * (X 2) ^2
    + 2487 * (X 1) ^9 * (X 2)
    + 67149 * (X 0) ^2 * (X 1) ^8 * (X 2)
    + 2487 * (X 1) ^5 * (X 2)
    + 2664 * (X 1) ^12
    + 143856 * (X 0) ^2 * (X 1) ^11
    + 1942056 * (X 0) ^4 * (X 1) ^10
    - 3888 * (X 1) ^8
    + 143856 * (X 0) ^2 * (X 1) ^7
    + 2664 * (X 1) ^4
private noncomputable def bezoutDMvCt : MvPolynomial (Fin 3) ℚ :=
  5184 * (X 1) ^20
    + 559872 * (X 0) ^2 * (X 1) ^19
    + 22674816 * (X 0) ^4 * (X 1) ^18
    + 408146688 * (X 0) ^6 * (X 1) ^17
    + 2754990144 * (X 0) ^8 * (X 1) ^16
    - 20736 * (X 1) ^16
    - 559872 * (X 0) ^2 * (X 1) ^15
    + 15116544 * (X 0) ^4 * (X 1) ^14
    + 408146688 * (X 0) ^6 * (X 1) ^13
    + 31104 * (X 1) ^12
    - 559872 * (X 0) ^2 * (X 1) ^11
    + 22674816 * (X 0) ^4 * (X 1) ^10
    - 20736 * (X 1) ^8
    + 559872 * (X 0) ^2 * (X 1) ^7
    + 5184 * (X 1) ^4

/-- Abstract short-Weierstrass formula for `Φ₃` as a multivariate identity
(the model of [CLOP §4.2]). -/
private theorem phi3MvCt_formula :
    phi3MvCt = (X 2) * psi3MvCt ^ 2 - prePsi4MvCt * psi2SqMvCt := by
  unfold phi3MvCt psi3MvCt prePsi4MvCt psi2SqMvCt
  ring

private theorem bezout_identity_mv_ct :
    bezoutUMvCt * phi3MvCt + bezoutVMvCt * psi3MvCt = bezoutDMvCt := by
  unfold bezoutUMvCt phi3MvCt bezoutVMvCt psi3MvCt bezoutDMvCt
  ring

private theorem bezoutDMvCt_ne_zero : bezoutDMvCt ≠ 0 := by
  intro h
  have h1 := congrArg (eval (![0, 2, 0] : Fin 3 → ℚ)) h
  rw [map_zero, bezoutDMvCt] at h1
  simp [eval_add, eval_mul, eval_pow, eval_X] at h1
  norm_num at h1

/-- Lower-degree part of the cleared Bézout denominator (degrees `≤ 19` in `λ`). -/
private noncomputable def bezoutD_polyCt_rest : Polynomial Kt :=
  Polynomial.C ((559872 : Kt) * (RatFunc.X : Kt) ^2) * Polynomial.X ^19
    + Polynomial.C ((22674816 : Kt) * (RatFunc.X : Kt) ^4) * Polynomial.X ^18
    + Polynomial.C ((408146688 : Kt) * (RatFunc.X : Kt) ^6) * Polynomial.X ^17
    + Polynomial.C ((2754990144 : Kt) * (RatFunc.X : Kt) ^8 + (-20736 : Kt)) * Polynomial.X ^16
    + Polynomial.C ((-559872 : Kt) * (RatFunc.X : Kt) ^2) * Polynomial.X ^15
    + Polynomial.C ((15116544 : Kt) * (RatFunc.X : Kt) ^4) * Polynomial.X ^14
    + Polynomial.C ((408146688 : Kt) * (RatFunc.X : Kt) ^6) * Polynomial.X ^13
    + Polynomial.C ((31104 : Kt)) * Polynomial.X ^12
    + Polynomial.C ((-559872 : Kt) * (RatFunc.X : Kt) ^2) * Polynomial.X ^11
    + Polynomial.C ((22674816 : Kt) * (RatFunc.X : Kt) ^4) * Polynomial.X ^10
    + Polynomial.C ((-20736 : Kt)) * Polynomial.X ^8
    + Polynomial.C ((559872 : Kt) * (RatFunc.X : Kt) ^2) * Polynomial.X ^7
    + Polynomial.C ((5184 : Kt)) * Polynomial.X ^4

/-- The cleared Bézout denominator as a polynomial in `λ` over `ℚ(t)`.
Leading term `5184 λ²⁰`. -/
private noncomputable def bezoutD_polyCt : Polynomial Kt :=
  Polynomial.C (5184 : Kt) * Polynomial.X ^ 20 + bezoutD_polyCt_rest

/-- The cleared Bézout denominator in `ℚ(t)(λ)`. -/
private noncomputable def bezoutDCt : KCt :=
  algebraMap (Polynomial Kt) KCt bezoutD_polyCt

/-- Substitution `X 0 ↦ C t`, `X 1 ↦ C λ`, `X 2 ↦ X` into `ℚ(t)(λ)[X]`. -/
private noncomputable def sigmaCt : Fin 3 → Polynomial KCt :=
  ![Polynomial.C noteT, Polynomial.C (RatFunc.X : KCt), Polynomial.X]

private noncomputable def evalCt : MvPolynomial (Fin 3) ℚ →ₐ[ℚ] Polynomial KCt :=
  aeval sigmaCt

private theorem noteCurveCt_b₂ : noteCurveCt.b₂ = 0 := by
  simp [WeierstrassCurve.b₂, noteCurveCt]

private theorem noteCurveCt_b₄ : noteCurveCt.b₄ = 2 * noteCurveCt.a₄ := by
  simp [WeierstrassCurve.b₄, noteCurveCt]

private theorem noteCurveCt_b₆ : noteCurveCt.b₆ = 4 * noteCurveCt.a₆ := by
  simp [WeierstrassCurve.b₆, noteCurveCt]

private theorem noteCurveCt_b₈ : noteCurveCt.b₈ = -noteCurveCt.a₄ ^ 2 := by
  simp only [WeierstrassCurve.b₈, noteCurveCt]
  ring

private theorem sigmaCt_zero : sigmaCt 0 = Polynomial.C noteT := rfl
private theorem sigmaCt_one : sigmaCt 1 = Polynomial.C (RatFunc.X : KCt) := rfl
private theorem sigmaCt_two : sigmaCt 2 = Polynomial.X := rfl

private theorem noteCurveCt_Ψ₂Sq_eq : noteCurveCt.Ψ₂Sq = evalCt psi2SqMvCt := by
  have hrhs :
      evalCt psi2SqMvCt =
        4 * Polynomial.X ^ 3
          + Polynomial.C (-(12 : KCt) * RatFunc.X ^ 2) * Polynomial.X
          + Polynomial.C (-(4 : KCt) * RatFunc.X ^ 5 - 108 * noteT ^ 2 * RatFunc.X ^ 4
              - 4 * RatFunc.X) := by
    unfold psi2SqMvCt evalCt
    simp only [map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
      sigmaCt_zero, sigmaCt_one, sigmaCt_two, noteT]
    ring
  rw [hrhs, WeierstrassCurve.Ψ₂Sq, noteCurveCt_b₂, noteCurveCt_b₄, noteCurveCt_b₆]
  simp only [noteCurveCt]
  ring_nf
  simp only [map_ofNat, map_neg, map_mul, map_pow, map_sub, noteT, Polynomial.C_0,
    mul_zero, add_zero]
  ring

private theorem noteCurveCt_Ψ₃_eq : noteCurveCt.Ψ₃ = evalCt psi3MvCt := by
  have hrhs :
      evalCt psi3MvCt =
        (3 : Polynomial KCt) * Polynomial.X ^ 4
          + Polynomial.C (-(18 : KCt) * RatFunc.X ^ 2) * Polynomial.X ^ 2
          + Polynomial.C (-(12 : KCt) * RatFunc.X ^ 5 - 324 * noteT ^ 2 * RatFunc.X ^ 4
              - 12 * RatFunc.X) * Polynomial.X
          + Polynomial.C (-(9 : KCt) * RatFunc.X ^ 4) := by
    unfold psi3MvCt evalCt
    simp only [map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
      sigmaCt_zero, sigmaCt_one, sigmaCt_two, noteT]
    ring
  rw [hrhs, WeierstrassCurve.Ψ₃, noteCurveCt_b₂, noteCurveCt_b₄, noteCurveCt_b₆, noteCurveCt_b₈]
  simp only [noteCurveCt]
  ring_nf
  simp only [map_ofNat, map_neg, map_mul, map_pow, map_sub, noteT, Polynomial.C_0,
    mul_zero, add_zero]
  ring

private theorem noteCurveCt_preΨ₄_eq : noteCurveCt.preΨ₄ = evalCt prePsi4MvCt := by
  have hrhs :
      evalCt prePsi4MvCt =
        2 * Polynomial.X ^ 6
          + Polynomial.C (-(30 : KCt) * RatFunc.X ^ 2) * Polynomial.X ^ 4
          + Polynomial.C (-(40 : KCt) * RatFunc.X ^ 5 - 1080 * noteT ^ 2 * RatFunc.X ^ 4
              - 40 * RatFunc.X) * Polynomial.X ^ 3
          + Polynomial.C (-(90 : KCt) * RatFunc.X ^ 4) * Polynomial.X ^ 2
          + Polynomial.C (-(24 : KCt) * RatFunc.X ^ 7 - 648 * noteT ^ 2 * RatFunc.X ^ 6
              - 24 * RatFunc.X ^ 3) * Polynomial.X
          + Polynomial.C (-(16 : KCt) * RatFunc.X ^ 10 - 864 * noteT ^ 2 * RatFunc.X ^ 9
              - 11664 * noteT ^ 4 * RatFunc.X ^ 8 + 22 * RatFunc.X ^ 6
              - 864 * noteT ^ 2 * RatFunc.X ^ 5 - 16 * RatFunc.X ^ 2) := by
    unfold prePsi4MvCt evalCt
    simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
      sigmaCt_zero, sigmaCt_one, sigmaCt_two, noteT]
    ring
  rw [hrhs, WeierstrassCurve.preΨ₄, noteCurveCt_b₂, noteCurveCt_b₄, noteCurveCt_b₆, noteCurveCt_b₈]
  simp only [noteCurveCt]
  ring_nf
  simp only [map_ofNat, map_neg, map_mul, map_pow, map_sub, noteT, Polynomial.C_0,
    mul_zero, add_zero]
  ring

private theorem evalCt_X2 : evalCt (X 2) = Polynomial.X := by
  simp [evalCt, aeval_X, sigmaCt_two]

private theorem noteCurveCt_Φ_eq : noteCurveCt.Φ 3 = evalCt phi3MvCt := by
  have hΦ : noteCurveCt.Φ 3 =
      Polynomial.X * noteCurveCt.Ψ₃ ^ 2 - noteCurveCt.preΨ₄ * noteCurveCt.Ψ₂Sq :=
    WeierstrassCurve.Φ_three (W := noteCurveCt)
  rw [hΦ, noteCurveCt_Ψ₃_eq, noteCurveCt_preΨ₄_eq, noteCurveCt_Ψ₂Sq_eq, phi3MvCt_formula]
  simp only [map_sub, map_mul, map_pow, evalCt_X2]

private theorem evalCt_bezoutD : (evalCt bezoutDMvCt : Polynomial KCt) = Polynomial.C bezoutDCt := by
  unfold evalCt bezoutDMvCt bezoutDCt bezoutD_polyCt bezoutD_polyCt_rest
  simp only [map_add, map_sub, map_mul, map_pow, map_neg, aeval_X, map_ofNat,
    sigmaCt_zero, sigmaCt_one, noteT]
  -- Identify `algebraMap (Polynomial Kt) KCt (C t)` with `noteT = algebraMap Kt KCt t`,
  -- and `algebraMap (Polynomial Kt) KCt X` with `RatFunc.X`.
  simp only [RatFunc.algebraMap_C, RatFunc.algebraMap_eq_C, RatFunc.algebraMap_X]
  ring_nf

private theorem bezoutD_polyCt_rest_natDegree_lt :
    bezoutD_polyCt_rest.natDegree < 20 := by
  unfold bezoutD_polyCt_rest
  compute_degree!

private theorem bezoutDCt_ne_zero : bezoutDCt ≠ 0 := by
  have h20 : bezoutD_polyCt.coeff 20 = (5184 : Kt) := by
    unfold bezoutD_polyCt
    rw [Polynomial.coeff_add, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
      if_pos rfl, mul_one,
      Polynomial.coeff_eq_zero_of_natDegree_lt bezoutD_polyCt_rest_natDegree_lt, add_zero]
  have hp : bezoutD_polyCt ≠ 0 := fun hp0 => by
    have hKt : (5184 : Kt) = 0 := by
      have h := congrArg (fun q : Polynomial Kt => q.coeff 20) hp0
      rw [h20, Polynomial.coeff_zero] at h
      exact h
    have hQ : (5184 : ℚ) = 0 := by
      have h' : algebraMap ℚ Kt (5184 : ℚ) = algebraMap ℚ Kt (0 : ℚ) := by
        convert hKt <;> simp
      exact (FaithfulSMul.algebraMap_injective ℚ Kt).eq_iff.mp h'
    norm_num at hQ
  simpa [bezoutDCt, map_zero] using
    (FaithfulSMul.algebraMap_injective (Polynomial Kt) KCt).ne hp

private theorem isCoprime_Φ_Ψ₃_noteCurveCt :
    IsCoprime (noteCurveCt.Φ 3) noteCurveCt.Ψ₃ := by
  rw [noteCurveCt_Φ_eq, noteCurveCt_Ψ₃_eq]
  refine ⟨(evalCt bezoutUMvCt) * Polynomial.C bezoutDCt⁻¹,
    (evalCt bezoutVMvCt) * Polynomial.C bezoutDCt⁻¹, ?_⟩
  have hid :
      (evalCt bezoutUMvCt) * (evalCt phi3MvCt) + (evalCt bezoutVMvCt) * (evalCt psi3MvCt)
        = evalCt bezoutDMvCt := by
    simpa [← map_mul, ← map_add] using
      congrArg (AlgHom.toRingHom evalCt) bezout_identity_mv_ct
  have hD : bezoutDCt ≠ 0 := bezoutDCt_ne_zero
  calc
    (evalCt bezoutUMvCt) * Polynomial.C bezoutDCt⁻¹ * (evalCt phi3MvCt)
        + (evalCt bezoutVMvCt) * Polynomial.C bezoutDCt⁻¹ * (evalCt psi3MvCt)
      = Polynomial.C bezoutDCt⁻¹
          * ((evalCt bezoutUMvCt) * (evalCt phi3MvCt)
              + (evalCt bezoutVMvCt) * (evalCt psi3MvCt)) := by
        ring
    _ = Polynomial.C bezoutDCt⁻¹ * evalCt bezoutDMvCt := by rw [hid]
    _ = Polynomial.C bezoutDCt⁻¹ * Polynomial.C bezoutDCt := by rw [evalCt_bezoutD]
    _ = Polynomial.C (bezoutDCt⁻¹ * bezoutDCt) := by rw [← Polynomial.C_mul]
    _ = Polynomial.C 1 := by rw [inv_mul_cancel₀ hD]
    _ = 1 := by simp

/-- **Coprimality of `Φ₃` and `ΨSq₃` for the model of [CLOP §4.2].** -/
public theorem isCoprime_Φ_ΨSq_noteCurveCt :
    IsCoprime (noteCurveCt.Φ 3) (noteCurveCt.ΨSq 3) := by
  simpa [WeierstrassCurve.ΨSq_three] using
    (isCoprime_Φ_Ψ₃_noteCurveCt.pow_right (n := 2))

private theorem three_ne_zero_KCt : (3 : KCt) ≠ 0 := by
  exact_mod_cast (three_ne_zero : (3 : ℚ) ≠ 0)

/-- **Unconditional degree-nine statement for the model of [CLOP §4.2].**

The `x`-line over `ℚ(t)(λ)` is a degree-exactly-`9` extension of the subfield generated by
`x ∘ [3]`. -/
public theorem finrank_mulThreeX_noteCurveCt :
    Module.finrank KCt⟮mulThreeX noteCurveCt⟯ (RatFunc KCt) = 9 :=
  finrank_mulThreeX noteCurveCt three_ne_zero_KCt isCoprime_Φ_ΨSq_noteCurveCt

/-! ## Axiom audit -/

#print axioms isCoprime_Φ_ΨSq_noteCurveQ
#print axioms finrank_mulThreeX_noteCurveQ
#print axioms isCoprime_Φ_ΨSq_noteCurveCt
#print axioms finrank_mulThreeX_noteCurveCt

end ExplicitUnirational
