/-
Copyright (c) 2026 Matthew R. Ballard.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matthew R. Ballard
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Degree
public import Mathlib.FieldTheory.RatFunc.IntermediateField

/-!
# The degree of multiplication by three on the `x`-line

[CLOP Lemma 3.4], specialized as in [CLOP Example 3.5], proves that `α_λ : C → Jac(C)`,
`P ↦ 3P`, has degree `9` by identifying it,
after a translation, with the isogeny `[3]` and quoting `deg [3] = 3 ^ 2`. Formalizing that
argument needs `Pic³` of a genus-one curve and the degree of an isogeny, neither of which is
available in Mathlib.

This module replaces it with an elementary computation. The `x`-coordinate of multiplication
by three is the rational function `Φ₃ / ΨSq₃`, and Mathlib supplies the exact degrees
`deg Φₙ = n²` and `deg ΨSqₙ = n² - 1`. With `RatFunc.finrank_eq_max_natDegree` this gives
`max 9 8 = 9` directly.

Coprimality of `Φ₃` and `ΨSq₃` is an explicit hypothesis rather than a proof obligation here:
it is absent from Mathlib, and it is genuinely required, since `finrank_eq_max_natDegree` is
stated about `num`/`denom` -- a common factor `d` would give `9 - d.natDegree` instead of `9`.
Discharging it for the two explicit curves of [CLOP §4.1] and [CLOP §4.2] is a separate
work package.
-/

noncomputable section

open Polynomial
open scoped IntermediateField

namespace ExplicitUnirational

variable {F : Type*} [Field F]

/-- The `x`-coordinate of multiplication by three, as a rational function. -/
public noncomputable def mulThreeX (W : WeierstrassCurve F) : RatFunc F :=
  algebraMap F[X] (RatFunc F) (W.Φ 3) / algebraMap F[X] (RatFunc F) (W.ΨSq 3)

open scoped Classical in
/-- Coprime polynomials over a field have `gcd` equal to `1`. -/
private theorem gcd_eq_one_of_isCoprime {p q : F[X]} (hcop : IsCoprime p q) :
    gcd p q = 1 := by
  have h : IsUnit (gcd p q) := gcd_isUnit_iff_isRelPrime.mpr hcop.isRelPrime
  simpa using normalize_eq_one.mpr h

open scoped Classical in
/-- With a coprime presentation, the reduced numerator has the numerator's degree. -/
private theorem natDegree_num_div {p q : F[X]} (hq : q ≠ 0) (hcop : IsCoprime p q) :
    (algebraMap F[X] (RatFunc F) p / algebraMap F[X] (RatFunc F) q).num.natDegree
      = p.natDegree := by
  rw [RatFunc.num_div, gcd_eq_one_of_isCoprime hcop]
  simp only [EuclideanDomain.div_one]
  exact natDegree_C_mul (inv_ne_zero (leadingCoeff_ne_zero.mpr hq))

open scoped Classical in
/-- With a coprime presentation, the reduced denominator has the denominator's degree. -/
private theorem natDegree_denom_div {p q : F[X]} (hq : q ≠ 0) (hcop : IsCoprime p q) :
    (algebraMap F[X] (RatFunc F) p / algebraMap F[X] (RatFunc F) q).denom.natDegree
      = q.natDegree := by
  rw [RatFunc.denom_div _ hq, gcd_eq_one_of_isCoprime hcop]
  simp only [EuclideanDomain.div_one]
  exact natDegree_C_mul (inv_ne_zero (leadingCoeff_ne_zero.mpr hq))

/-- **The degree of multiplication by three is nine.**

The elementary replacement for the isogeny-degree half of [CLOP Lemma 3.4]: the `x`-line is an
extension of degree exactly `9` over the subfield generated by the `x`-coordinate of `[3]`. -/
public theorem finrank_mulThreeX (W : WeierstrassCurve F) (h3 : (3 : F) ≠ 0)
    (hcop : IsCoprime (W.Φ 3) (W.ΨSq 3)) :
    Module.finrank F⟮mulThreeX W⟯ (RatFunc F) = 9 := by
  have h3' : ((3 : ℤ) : F) ≠ 0 := by exact_mod_cast h3
  have hq : W.ΨSq 3 ≠ 0 := W.ΨSq_ne_zero h3'
  rw [RatFunc.finrank_eq_max_natDegree, mulThreeX, natDegree_num_div hq hcop,
    natDegree_denom_div hq hcop, W.natDegree_Φ 3, W.natDegree_ΨSq h3']
  decide

end ExplicitUnirational
